/*
**
** The C code is generated by ATS/Postiats
** The compilation time is: 2014-8-6: 19h: 5m
**
*/

/*
** include runtime header files
*/
#ifndef _ATS_CCOMP_HEADER_NONE
#include "pats_ccomp_config.h"
#include "pats_ccomp_basics.h"
#include "pats_ccomp_typedefs.h"
#include "pats_ccomp_instrset.h"
#include "pats_ccomp_memalloc.h"
#ifndef _ATS_CCOMP_EXCEPTION_NONE
#include "pats_ccomp_memalloca.h"
#include "pats_ccomp_exception.h"
#endif // end of [_ATS_CCOMP_EXCEPTION_NONE]
#endif /* _ATS_CCOMP_HEADER_NONE */


/*
** include prelude cats files
*/
#ifndef _ATS_CCOMP_PRELUDE_NONE
//
#include "prelude/CATS/basics.cats"
#include "prelude/CATS/integer.cats"
#include "prelude/CATS/pointer.cats"
#include "prelude/CATS/bool.cats"
#include "prelude/CATS/char.cats"
#include "prelude/CATS/integer_ptr.cats"
#include "prelude/CATS/integer_fixed.cats"
#include "prelude/CATS/float.cats"
#include "prelude/CATS/memory.cats"
#include "prelude/CATS/string.cats"
#include "prelude/CATS/strptr.cats"
//
#include "prelude/CATS/filebas.cats"
//
#include "prelude/CATS/list.cats"
#include "prelude/CATS/option.cats"
#include "prelude/CATS/array.cats"
#include "prelude/CATS/arrayptr.cats"
#include "prelude/CATS/arrayref.cats"
#include "prelude/CATS/matrix.cats"
#include "prelude/CATS/matrixptr.cats"
//
#endif /* _ATS_CCOMP_PRELUDE_NONE */
/*
** for user-supplied prelude
*/
#ifdef _ATS_CCOMP_PRELUDE_USER
//
#include _ATS_CCOMP_PRELUDE_USER
//
#endif /* _ATS_CCOMP_PRELUDE_USER */

/*
staload-prologues(beg)
*/
/*
/ats2/prelude/DATS/pointer.dats: 1533(line=44, offs=1) -- 1572(line=44, offs=40)
*/
/*
/ats2/prelude/DATS/integer.dats: 1636(line=51, offs=1) -- 1675(line=51, offs=40)
*/
/*
/ats2/prelude/DATS/integer_fixed.dats: 1641(line=51, offs=1) -- 1680(line=51, offs=40)
*/
/*
/ats2/prelude/DATS/memory.dats: 1410(line=38, offs=1) -- 1449(line=39, offs=32)
*/
/*
/ats2/prelude/DATS/string.dats: 1609(line=48, offs=1) -- 1648(line=48, offs=40)
*/
/*
/ats2/prelude/DATS/strptr.dats: 1609(line=48, offs=1) -- 1648(line=48, offs=40)
*/
/*
/ats2/prelude/DATS/strptr.dats: 1671(line=52, offs=1) -- 1718(line=52, offs=48)
*/
/*
/ats2/prelude/DATS/integer.dats: 1636(line=51, offs=1) -- 1675(line=51, offs=40)
*/
/*
/ats2/prelude/DATS/filebas.dats: 1613(line=48, offs=1) -- 1652(line=48, offs=40)
*/
/*
/ats2/prelude/DATS/filebas.dats: 1675(line=52, offs=1) -- 1722(line=52, offs=48)
*/
/*
/ats2/prelude/DATS/integer.dats: 1636(line=51, offs=1) -- 1675(line=51, offs=40)
*/
/*
/ats2/prelude/DATS/filebas.dats: 1745(line=56, offs=1) -- 1783(line=56, offs=39)
*/
/*
/ats2/libc/SATS/stdio.sats: 1380(line=35, offs=1) -- 1418(line=37, offs=3)
*/

#include "libc/CATS/stdio.cats"
/*
/ats2/libc/SATS/stdio.sats: 1791(line=56, offs=1) -- 1833(line=58, offs=27)
*/
/*
/ats2/libc/sys/SATS/types.sats: 1390(line=36, offs=1) -- 1432(line=38, offs=3)
*/

#include "libc/sys/CATS/types.cats"
/*
/ats2/prelude/DATS/filebas.dats: 1861(line=61, offs=1) -- 1901(line=61, offs=41)
*/
/*
/ats2/libc/sys/SATS/stat.sats: 1390(line=36, offs=1) -- 1431(line=38, offs=3)
*/

#include "libc/sys/CATS/stat.cats"
/*
/ats2/libc/sys/SATS/stat.sats: 1776(line=53, offs=1) -- 1818(line=54, offs=35)
*/
/*
/ats2/libc/sys/SATS/types.sats: 1390(line=36, offs=1) -- 1432(line=38, offs=3)
*/

#include "libc/sys/CATS/types.cats"
/*
/ats2/prelude/DATS/filebas.dats: 15159(line=816, offs=1) -- 15189(line=816, offs=31)
*/
/*
/ats2/libc/SATS/stdio.sats: 1380(line=35, offs=1) -- 1418(line=37, offs=3)
*/

#include "libc/CATS/stdio.cats"
/*
/ats2/libc/SATS/stdio.sats: 1791(line=56, offs=1) -- 1833(line=58, offs=27)
*/
/*
/ats2/libc/sys/SATS/types.sats: 1390(line=36, offs=1) -- 1432(line=38, offs=3)
*/

#include "libc/sys/CATS/types.cats"
/*
/ats2/prelude/DATS/list.dats: 1527(line=44, offs=1) -- 1566(line=44, offs=40)
*/
/*
/ats2/prelude/DATS/list.dats: 1567(line=45, offs=1) -- 1613(line=45, offs=47)
*/
/*
/ats2/prelude/DATS/unsafe.dats: 1532(line=44, offs=1) -- 1566(line=44, offs=35)
*/
/*
/ats2/prelude/DATS/list_vt.dats: 1536(line=44, offs=1) -- 1575(line=44, offs=40)
*/
/*
/ats2/prelude/DATS/list_vt_mergesort.dats: 1546(line=44, offs=1) -- 1585(line=44, offs=40)
*/
/*
/ats2/prelude/DATS/list_vt_quicksort.dats: 1546(line=44, offs=1) -- 1585(line=44, offs=40)
*/
/*
/ats2/prelude/DATS/array.dats: 1534(line=44, offs=1) -- 1573(line=44, offs=40)
*/
/*
/ats2/prelude/DATS/array.dats: 1574(line=45, offs=1) -- 1616(line=45, offs=43)
*/
/*
/ats2/prelude/DATS/array_bsearch.dats: 1531(line=44, offs=1) -- 1570(line=44, offs=40)
*/
/*
/ats2/prelude/DATS/array_quicksort.dats: 1531(line=44, offs=1) -- 1570(line=44, offs=40)
*/
/*
/ats2/prelude/DATS/arrayptr.dats: 1532(line=44, offs=1) -- 1571(line=44, offs=40)
*/
/*
/ats2/prelude/DATS/arrayref.dats: 1532(line=44, offs=1) -- 1571(line=44, offs=40)
*/
/*
/ats2/prelude/DATS/matrix.dats: 1535(line=44, offs=1) -- 1574(line=44, offs=40)
*/
/*
/ats2/prelude/DATS/matrixptr.dats: 1538(line=44, offs=1) -- 1577(line=44, offs=40)
*/
/*
/ats2/prelude/DATS/matrixref.dats: 1538(line=44, offs=1) -- 1577(line=44, offs=40)
*/
/*
/ats2/prelude/DATS/stream.dats: 1570(line=48, offs=1) -- 1609(line=48, offs=40)
*/
/*
/ats2/prelude/DATS/stream_vt.dats: 1573(line=48, offs=1) -- 1612(line=48, offs=40)
*/
/*
/ats2/prelude/DATS/unsafe.dats: 1532(line=44, offs=1) -- 1566(line=44, offs=35)
*/
/*
/ats2/prelude/DATS/checkast.dats: 1531(line=44, offs=1) -- 1570(line=45, offs=32)
*/
/*
/vagrant/file.sats: 1(line=1, offs=1) -- 27(line=1, offs=27)
*/
/*
/vagrant/stream.sats: 1(line=1, offs=1) -- 21(line=1, offs=21)
*/
/*
/vagrant/file.sats: 29(line=2, offs=1) -- 48(line=2, offs=20)
*/
/*
/vagrant/pair.sats: 1(line=1, offs=1) -- 21(line=1, offs=21)
*/
/*
/vagrant/token.sats: 1(line=1, offs=1) -- 20(line=1, offs=20)
*/
/*
/vagrant/token.sats: 22(line=2, offs=1) -- 45(line=2, offs=24)
*/
/*
/vagrant/file.sats: 50(line=3, offs=1) -- 73(line=3, offs=24)
*/
/*
/ats2/libc/SATS/stdio.sats: 1380(line=35, offs=1) -- 1418(line=37, offs=3)
*/

#include "libc/CATS/stdio.cats"
/*
/ats2/libc/SATS/stdio.sats: 1791(line=56, offs=1) -- 1833(line=58, offs=27)
*/
/*
/ats2/libc/sys/SATS/types.sats: 1390(line=36, offs=1) -- 1432(line=38, offs=3)
*/

#include "libc/sys/CATS/types.cats"
/*
/vagrant/stream.sats: 1(line=1, offs=1) -- 21(line=1, offs=21)
*/
/*
/vagrant/pair.sats: 1(line=1, offs=1) -- 21(line=1, offs=21)
*/
/*
/vagrant/token.sats: 1(line=1, offs=1) -- 20(line=1, offs=20)
*/
/*
/vagrant/token.sats: 22(line=2, offs=1) -- 45(line=2, offs=24)
*/
/*
/vagrant/stream.dats: 30(line=3, offs=1) -- 51(line=3, offs=22)
*/
/*
/vagrant/stream.sats: 1(line=1, offs=1) -- 21(line=1, offs=21)
*/
/*
/vagrant/stream.dats: 53(line=4, offs=1) -- 73(line=4, offs=21)
*/
/*
/vagrant/location.dats: 30(line=3, offs=1) -- 53(line=3, offs=24)
*/
/*
staload-prologues(end)
*/
/*
typedefs-for-tyrecs-and-tysums(beg)
*/
typedef
struct {
#if(0)
int contag ;
#endif
atstkind_t0ype(atstype_char) atslab__0; 
atstkind_type(atstype_ptrk) atslab__1; 
} postiats_tysum_0 ;
typedef
struct {
#if(0)
int contag ;
#endif
atstkind_t0ype(atstype_int) atslab__0; 
atstkind_t0ype(atstype_int) atslab__1; 
} postiats_tysum_1 ;
typedef
struct {
#if(1)
int contag ;
#endif
atstkind_type(atstype_ptrk) atslab__0; 
atstype_boxed atslab__1; 
} postiats_tysum_2 ;
typedef
struct {
#if(0)
int contag ;
#endif
atstkind_t0ype(atstype_char) atslab__0; 
atstype_boxed atslab__1; 
} postiats_tysum_3 ;
typedef
struct {
#if(0)
int contag ;
#endif
atstype_boxed atslab__0; 
atstkind_type(atstype_ptrk) atslab__1; 
} postiats_tysum_4 ;
/*
typedefs-for-tyrecs-and-tysums(end)
*/
/*
dynconlst-declaration(beg)
*/
/*
dynconlst-declaration(end)
*/
/*
dyncstlst-declaration(beg)
*/
ATSdyncst_mac(atspre_int2char0)
ATSdyncst_mac(atslib_fgetc0)
ATSdyncst_mac(atspre_g0int2int_int_int)
ATSdyncst_mac(atspre_g0int_eq_int)
ATSdyncst_mac(atslib_feof0)
ATSdyncst_extfun(atslib_fclose0_exn, (atstkind_type(atstype_ptrk)), atsvoid_t0ype) ;
ATSdyncst_mac(atspre_eq_char0_char0)
ATSdyncst_mac(atspre_g0int_add_int)
ATSdyncst_extfun(atslib_fopen_ref_exn, (atstkind_type(atstype_ptrk), atstkind_type(atstype_ptrk)), atstkind_type(atstype_ptrk)) ;
ATSdyncst_mac(atspre_file_mode_r)
/*
dyncstlst-declaration(end)
*/
/*
dynvalist-implementation(beg)
*/
/*
dynvalist-implementation(end)
*/
/*
exnconlst-declaration(beg)
*/
#ifndef _ATS_CCOMP_EXCEPTION_NONE
extern void the_atsexncon_initize (atstype_exncon *d2c, char *exnmsg) ;
#endif // end of [_ATS_CCOMP_EXCEPTION_NONE]
/*
exnconlst-declaration(end)
*/
/*
assumelst-declaration(beg)
*/
/*
assumelst-declaration(end)
*/
/*
extypelst-declaration(beg)
*/
/*
extypelst-declaration(end)
*/
#if(0)
ATSglobaldec()
atstkind_type(atstype_ptrk)
_057_vagrant_057_file_056_sats__filestream(atstkind_type(atstype_ptrk)) ;
#endif // end of [QUALIFIED]

ATSstaticdec()
atstkind_type(atstype_ptrk)
tostream_1(atstkind_type(atstype_ptrk)) ;

#if(0)
#if(0)
ATSglobaldec()
atstkind_t0ype(atstype_bool)
ATSLIB_056_prelude__eq_g0int_int__2(atstkind_t0ype(atstyvar_type(tk)), atstkind_t0ype(atstype_int)) ;
#endif // end of [QUALIFIED]
#endif // end of [TEMPLATE]

ATSstaticdec()
atstkind_t0ype(atstype_bool)
ATSLIB_056_prelude__eq_g0int_int__2__1(atstkind_t0ype(atstype_int), atstkind_t0ype(atstype_int)) ;

ATSstaticdec()
atstype_boxed
__patsfun_6(atstkind_type(atstype_ptrk), atstkind_t0ype(atstype_char)) ;

ATSstaticdec()
atstype_boxed
__patsfun_7() ;

ATSstaticdec()
atstkind_type(atstype_ptrk)
appendloc_8(atstkind_type(atstype_ptrk), atstkind_type(atstype_ptrk), atstkind_t0ype(atstype_int), atstkind_t0ype(atstype_int)) ;

ATSstaticdec()
atstype_boxed
__patsfun_9() ;

ATSstaticdec()
atstype_boxed
__patsfun_10(atstkind_type(atstype_ptrk), atstkind_t0ype(atstype_int), atstype_boxed, atstkind_t0ype(atstype_char), atstkind_type(atstype_ptrk)) ;

ATSstaticdec()
atstype_boxed
__patsfun_12(atstkind_type(atstype_ptrk), atstkind_t0ype(atstype_int), atstkind_t0ype(atstype_int), atstype_boxed, atstkind_t0ype(atstype_char), atstkind_type(atstype_ptrk)) ;

typedef struct
{
atstype_funptr cfun ;
atstkind_type(atstype_ptrk) env0 ;
atstkind_t0ype(atstype_char) env1 ;
} __patsfun_6__closure_t0ype ;
ATSstaticdec()
atstype_boxed
__patsfun_6__cfun
(
__patsfun_6__closure_t0ype *p_cenv
)
{
ATSFCreturn(__patsfun_6(p_cenv->env0, p_cenv->env1)) ;
} /* end of [cfun] */
ATSstaticdec()
atstype_cloptr
__patsfun_6__closureinit
(
__patsfun_6__closure_t0ype *p_cenv, atstkind_type(atstype_ptrk) env0, atstkind_t0ype(atstype_char) env1
)
{
p_cenv->env0 = env0 ;
p_cenv->env1 = env1 ;
p_cenv->cfun = __patsfun_6__cfun ;
return p_cenv ;
} /* end of [closureinit] */
ATSstaticdec()
atstype_cloptr
__patsfun_6__closurerize
(
atstkind_type(atstype_ptrk) env0, atstkind_t0ype(atstype_char) env1
)
{
return __patsfun_6__closureinit(ATS_MALLOC(sizeof(__patsfun_6__closure_t0ype)), env0, env1) ;
} /* end of [closurerize] */

typedef struct
{
atstype_funptr cfun ;
} __patsfun_7__closure_t0ype ;
ATSstaticdec()
atstype_boxed
__patsfun_7__cfun
(
__patsfun_7__closure_t0ype *p_cenv
)
{
ATSFCreturn(__patsfun_7()) ;
} /* end of [cfun] */
ATSstaticdec()
atstype_cloptr
__patsfun_7__closureinit
(
__patsfun_7__closure_t0ype *p_cenv
)
{
p_cenv->cfun = __patsfun_7__cfun ;
return p_cenv ;
} /* end of [closureinit] */
ATSstaticdec()
atstype_cloptr
__patsfun_7__closurerize
(
// argumentless
)
{
return __patsfun_7__closureinit(ATS_MALLOC(sizeof(__patsfun_7__closure_t0ype))) ;
} /* end of [closurerize] */

typedef struct
{
atstype_funptr cfun ;
} __patsfun_9__closure_t0ype ;
ATSstaticdec()
atstype_boxed
__patsfun_9__cfun
(
__patsfun_9__closure_t0ype *p_cenv
)
{
ATSFCreturn(__patsfun_9()) ;
} /* end of [cfun] */
ATSstaticdec()
atstype_cloptr
__patsfun_9__closureinit
(
__patsfun_9__closure_t0ype *p_cenv
)
{
p_cenv->cfun = __patsfun_9__cfun ;
return p_cenv ;
} /* end of [closureinit] */
ATSstaticdec()
atstype_cloptr
__patsfun_9__closurerize
(
// argumentless
)
{
return __patsfun_9__closureinit(ATS_MALLOC(sizeof(__patsfun_9__closure_t0ype))) ;
} /* end of [closurerize] */

typedef struct
{
atstype_funptr cfun ;
atstkind_type(atstype_ptrk) env0 ;
atstkind_t0ype(atstype_int) env1 ;
atstype_boxed env2 ;
atstkind_t0ype(atstype_char) env3 ;
atstkind_type(atstype_ptrk) env4 ;
} __patsfun_10__closure_t0ype ;
ATSstaticdec()
atstype_boxed
__patsfun_10__cfun
(
__patsfun_10__closure_t0ype *p_cenv
)
{
ATSFCreturn(__patsfun_10(p_cenv->env0, p_cenv->env1, p_cenv->env2, p_cenv->env3, p_cenv->env4)) ;
} /* end of [cfun] */
ATSstaticdec()
atstype_cloptr
__patsfun_10__closureinit
(
__patsfun_10__closure_t0ype *p_cenv, atstkind_type(atstype_ptrk) env0, atstkind_t0ype(atstype_int) env1, atstype_boxed env2, atstkind_t0ype(atstype_char) env3, atstkind_type(atstype_ptrk) env4
)
{
p_cenv->env0 = env0 ;
p_cenv->env1 = env1 ;
p_cenv->env2 = env2 ;
p_cenv->env3 = env3 ;
p_cenv->env4 = env4 ;
p_cenv->cfun = __patsfun_10__cfun ;
return p_cenv ;
} /* end of [closureinit] */
ATSstaticdec()
atstype_cloptr
__patsfun_10__closurerize
(
atstkind_type(atstype_ptrk) env0, atstkind_t0ype(atstype_int) env1, atstype_boxed env2, atstkind_t0ype(atstype_char) env3, atstkind_type(atstype_ptrk) env4
)
{
return __patsfun_10__closureinit(ATS_MALLOC(sizeof(__patsfun_10__closure_t0ype)), env0, env1, env2, env3, env4) ;
} /* end of [closurerize] */

typedef struct
{
atstype_funptr cfun ;
atstkind_type(atstype_ptrk) env0 ;
atstkind_t0ype(atstype_int) env1 ;
atstkind_t0ype(atstype_int) env2 ;
atstype_boxed env3 ;
atstkind_t0ype(atstype_char) env4 ;
atstkind_type(atstype_ptrk) env5 ;
} __patsfun_12__closure_t0ype ;
ATSstaticdec()
atstype_boxed
__patsfun_12__cfun
(
__patsfun_12__closure_t0ype *p_cenv
)
{
ATSFCreturn(__patsfun_12(p_cenv->env0, p_cenv->env1, p_cenv->env2, p_cenv->env3, p_cenv->env4, p_cenv->env5)) ;
} /* end of [cfun] */
ATSstaticdec()
atstype_cloptr
__patsfun_12__closureinit
(
__patsfun_12__closure_t0ype *p_cenv, atstkind_type(atstype_ptrk) env0, atstkind_t0ype(atstype_int) env1, atstkind_t0ype(atstype_int) env2, atstype_boxed env3, atstkind_t0ype(atstype_char) env4, atstkind_type(atstype_ptrk) env5
)
{
p_cenv->env0 = env0 ;
p_cenv->env1 = env1 ;
p_cenv->env2 = env2 ;
p_cenv->env3 = env3 ;
p_cenv->env4 = env4 ;
p_cenv->env5 = env5 ;
p_cenv->cfun = __patsfun_12__cfun ;
return p_cenv ;
} /* end of [closureinit] */
ATSstaticdec()
atstype_cloptr
__patsfun_12__closurerize
(
atstkind_type(atstype_ptrk) env0, atstkind_t0ype(atstype_int) env1, atstkind_t0ype(atstype_int) env2, atstype_boxed env3, atstkind_t0ype(atstype_char) env4, atstkind_type(atstype_ptrk) env5
)
{
return __patsfun_12__closureinit(ATS_MALLOC(sizeof(__patsfun_12__closure_t0ype)), env0, env1, env2, env3, env4, env5) ;
} /* end of [closurerize] */

/*
/vagrant/file.dats: 278(line=14, offs=22) -- 1055(line=37, offs=2)
*/
/*
local: 
global: filestream$0$0(level=0)
local: 
global: 
*/
ATSglobaldec()
atstkind_type(atstype_ptrk)
_057_vagrant_057_file_056_sats__filestream(atstkind_type(atstype_ptrk) arg0)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret0, atstkind_type(atstype_ptrk)) ;
ATStmpdec(tmp30, atstkind_type(atstype_ptrk)) ;
ATStmpdec(tmp31, atstkind_type(atstype_ptrk)) ;
/* tmpvardeclst(end) */
/* funbodyinstrlst(beg) */
/*
emit_instr: loc0 = /vagrant/file.dats: 267(line=14, offs=11) -- 1055(line=37, offs=2)
*/
ATSINSlab(__patsflab_filestream):
/*
emit_instr: loc0 = /vagrant/file.dats: 287(line=14, offs=31) -- 1055(line=37, offs=2)
*/
/*
letpush(beg)
*/
/*
emit_instr: loc0 = /vagrant/file.dats: 976(line=35, offs=13) -- 1009(line=35, offs=46)
*/
ATSINSmove(tmp30, atslib_fopen_ref_exn(arg0, atspre_file_mode_r)) ;

/*
letpush(end)
*/

/*
emit_instr: loc0 = /vagrant/file.dats: 1032(line=36, offs=22) -- 1045(line=36, offs=35)
*/
ATSINSmove(tmp31, tostream_1(tmp30)) ;

/*
emit_instr: loc0 = /vagrant/file.dats: 1021(line=36, offs=11) -- 1052(line=36, offs=42)
*/
ATSINSmove(tmpret0, appendloc_8(arg0, tmp31, ATSPMVi0nt(1), ATSPMVi0nt(1))) ;

/*
emit_instr: loc0 = /vagrant/file.dats: 287(line=14, offs=31) -- 1055(line=37, offs=2)
*/
/*
INSletpop()
*/
/* funbodyinstrlst(end) */
ATSreturn(tmpret0) ;
} /* end of [_057_vagrant_057_file_056_sats__filestream] */

/*
/vagrant/file.dats: 304(line=15, offs=6) -- 543(line=23, offs=5)
*/
/*
local: tostream_1$0(level=1)
global: tostream_1$0(level=1)
local: 
global: 
*/
ATSstaticdec()
atstkind_type(atstype_ptrk)
tostream_1(atstkind_type(atstype_ptrk) arg0)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret1, atstkind_type(atstype_ptrk)) ;
ATStmpdec(tmp2, atstkind_t0ype(atstype_char)) ;
ATStmpdec(tmp3, atstkind_t0ype(atstype_int)) ;
ATStmpdec(tmp4, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp9, atstkind_t0ype(atstype_int)) ;
ATStmpdec_void(tmp12, atsvoid_t0ype) ;
/* tmpvardeclst(end) */
/* funbodyinstrlst(beg) */
/*
emit_instr: loc0 = /vagrant/file.dats: 304(line=15, offs=6) -- 543(line=23, offs=5)
*/
ATSINSlab(__patsflab_tostream_1):
/*
emit_instr: loc0 = /vagrant/file.dats: 355(line=15, offs=57) -- 543(line=23, offs=5)
*/
/*
letpush(beg)
*/
/*
emit_instr: loc0 = /vagrant/file.dats: 381(line=16, offs=22) -- 391(line=16, offs=32)
*/
ATSINSmove(tmp3, atslib_fgetc0(arg0)) ;

/*
emit_instr: loc0 = /vagrant/file.dats: 370(line=16, offs=11) -- 391(line=16, offs=32)
*/
ATSINSmove(tmp2, atspre_int2char0(tmp3)) ;

/*
letpush(end)
*/

/*
emit_instr: loc0 = /vagrant/file.dats: 405(line=18, offs=6) -- 415(line=18, offs=16)
*/
ATSINSmove(tmp9, atslib_feof0(arg0)) ;

/*
emit_instr: loc0 = /vagrant/file.dats: 405(line=18, offs=6) -- 420(line=18, offs=21)
*/
ATSINSmove(tmp4, ATSLIB_056_prelude__eq_g0int_int__2__1(tmp9, ATSPMVi0nt(0))) ;

/*
emit_instr: loc0 = /vagrant/file.dats: 402(line=18, offs=3) -- 536(line=22, offs=4)
*/
ATSif(
tmp4
) ATSthen() {
/*
emit_instr: loc0 = /vagrant/file.dats: 429(line=19, offs=8) -- 465(line=19, offs=44)
*/
ATSINSmove_delay(tmpret1, atstype_boxed, ATSPMVcfunlab(-1, __patsfun_6, (arg0, tmp2))) ;
} ATSelse() {
/*
emit_instr: loc0 = /vagrant/file.dats: 474(line=20, offs=8) -- 536(line=22, offs=4)
*/
/*
letpush(beg)
*/
/*
emit_instr: loc0 = /vagrant/file.dats: 514(line=21, offs=12) -- 530(line=21, offs=28)
*/
ATSINSmove_void(tmp12, atslib_fclose0_exn(arg0)) ;

/*
letpush(end)
*/

/*
emit_instr: loc0 = /vagrant/file.dats: 474(line=20, offs=8) -- 493(line=20, offs=27)
*/
ATSINSmove_delay(tmpret1, atstype_boxed, ATSPMVcfunlab(-1, __patsfun_7, ())) ;
/*
emit_instr: loc0 = /vagrant/file.dats: 474(line=20, offs=8) -- 536(line=22, offs=4)
*/
/*
INSletpop()
*/
} /* ATSendif */
/*
emit_instr: loc0 = /vagrant/file.dats: 355(line=15, offs=57) -- 543(line=23, offs=5)
*/
/*
INSletpop()
*/
/* funbodyinstrlst(end) */
ATSreturn(tmpret1) ;
} /* end of [tostream_1] */

#if(0)
/*
/ats2/prelude/DATS/integer.dats: 29101(line=802, offs=14) -- 29141(line=802, offs=54)
*/
/*
local: 
global: eq_g0int_int$2$0(level=0)
local: 
global: 
*/
ATSglobaldec()
/*
imparg = tk(4433)
tmparg = S2Evar(tk(4433))
tmpsub = None()
*/
atstkind_t0ype(atstype_bool)
ATSLIB_056_prelude__eq_g0int_int__2(atstkind_t0ype(atstyvar_type(tk)) arg0, atstkind_t0ype(atstype_int) arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret5, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp6, atstkind_t0ype(atstyvar_type(tk))) ;
/* tmpvardeclst(end) */
/* funbodyinstrlst(beg) */
/*
emit_instr: loc0 = /ats2/prelude/DATS/integer.dats: 29088(line=802, offs=1) -- 29141(line=802, offs=54)
*/
ATSINSlab(__patsflab_eq_g0int_int):
/*
emit_instr: loc0 = /ats2/prelude/DATS/integer.dats: 29127(line=802, offs=40) -- 29139(line=802, offs=52)
*/
ATSINSmove(tmp6, PMVtmpltcst(g0int2int<S2Eextkind(atstype_int), S2Evar(tk(4433))>)(arg1)) ;

/*
emit_instr: loc0 = /ats2/prelude/DATS/integer.dats: 29110(line=802, offs=23) -- 29141(line=802, offs=54)
*/
ATSINSmove(tmpret5, PMVtmpltcst(g0int_eq<S2Evar(tk(4433))>)(arg0, tmp6)) ;

/* funbodyinstrlst(end) */
ATSreturn(tmpret5) ;
} /* end of [ATSLIB_056_prelude__eq_g0int_int__2] */
#endif // end of [TEMPLATE]

/*
/ats2/prelude/DATS/integer.dats: 29101(line=802, offs=14) -- 29141(line=802, offs=54)
*/
/*
local: 
global: eq_g0int_int$2$1(level=2)
local: 
global: 
*/
ATSstaticdec()
/*
imparg = tk(4433)
tmparg = S2Evar(tk(4433))
tmpsub = Some(tk(4433) -> S2Eextkind(atstype_int))
*/
atstkind_t0ype(atstype_bool)
ATSLIB_056_prelude__eq_g0int_int__2__1(atstkind_t0ype(atstype_int) arg0, atstkind_t0ype(atstype_int) arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret5__1, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp6__1, atstkind_t0ype(atstype_int)) ;
/* tmpvardeclst(end) */
/* funbodyinstrlst(beg) */
/*
emit_instr: loc0 = /ats2/prelude/DATS/integer.dats: 29088(line=802, offs=1) -- 29141(line=802, offs=54)
*/
ATSINSlab(__patsflab_eq_g0int_int):
/*
emit_instr: loc0 = /ats2/prelude/DATS/integer.dats: 29127(line=802, offs=40) -- 29139(line=802, offs=52)
*/
ATSINSmove(tmp6__1, atspre_g0int2int_int_int(arg1)) ;

/*
emit_instr: loc0 = /ats2/prelude/DATS/integer.dats: 29110(line=802, offs=23) -- 29141(line=802, offs=54)
*/
ATSINSmove(tmpret5__1, atspre_g0int_eq_int(arg0, tmp6__1)) ;

/* funbodyinstrlst(end) */
ATSreturn(tmpret5__1) ;
} /* end of [ATSLIB_056_prelude__eq_g0int_int__2__1] */

/*
/vagrant/file.dats: 429(line=19, offs=8) -- 465(line=19, offs=44)
*/
/*
local: tostream_1$0(level=1)
global: tostream_1$0(level=1), __patsfun_6$0(level=2)
local: file$3491(2)(HSEapp(HSEcst(atstkind_type); HSEs2exp(S2Eextkind(atstype_ptrk)))), c$3492(2)(HSEapp(HSEcst(atstkind_t0ype); HSEs2exp(S2Eextkind(atstype_char))))
global: file$3491(2)(HSEapp(HSEcst(atstkind_type); HSEs2exp(S2Eextkind(atstype_ptrk)))), c$3492(2)(HSEapp(HSEcst(atstkind_t0ype); HSEs2exp(S2Eextkind(atstype_char))))
*/
ATSstaticdec()
atstype_boxed
__patsfun_6(atstkind_type(atstype_ptrk) env0, atstkind_t0ype(atstype_char) env1)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret10, atstype_boxed) ;
ATStmpdec(tmp11, atstkind_type(atstype_ptrk)) ;
/* tmpvardeclst(end) */
/* funbodyinstrlst(beg) */
/*
emit_instr: loc0 = /vagrant/file.dats: 429(line=19, offs=8) -- 465(line=19, offs=44)
*/
ATSINSlab(__patsflab___patsfun_6):
/*
emit_instr: loc0 = /vagrant/file.dats: 450(line=19, offs=29) -- 463(line=19, offs=42)
*/
ATSINSmove(tmp11, tostream_1(env0)) ;

/*
emit_instr: loc0 = /vagrant/file.dats: 437(line=19, offs=16) -- 464(line=19, offs=43)
*/

ATSINSmove_con1(tmpret10, postiats_tysum_0) ;
#if(0)
ATSINSstore_con_tag(tmpret10, 0) ;
#endif
ATSINSstore_con_ofs(tmpret10, postiats_tysum_0, atslab__0, env1) ;
ATSINSstore_con_ofs(tmpret10, postiats_tysum_0, atslab__1, tmp11) ;

/* funbodyinstrlst(end) */
ATSreturn(tmpret10) ;
} /* end of [__patsfun_6] */

/*
/vagrant/file.dats: 474(line=20, offs=8) -- 493(line=20, offs=27)
*/
/*
local: 
global: __patsfun_7$0(level=2)
local: 
global: 
*/
ATSstaticdec()
atstype_boxed
__patsfun_7()
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret13, atstype_boxed) ;
/* tmpvardeclst(end) */
/* funbodyinstrlst(beg) */
/*
emit_instr: loc0 = /vagrant/file.dats: 474(line=20, offs=8) -- 493(line=20, offs=27)
*/
ATSINSlab(__patsflab___patsfun_7):
/*
emit_instr: loc0 = /vagrant/file.dats: 482(line=20, offs=16) -- 492(line=20, offs=26)
*/

ATSINSmove_con0(tmpret13, 0) ;

/* funbodyinstrlst(end) */
ATSreturn(tmpret13) ;
} /* end of [__patsfun_7] */

/*
/vagrant/file.dats: 552(line=25, offs=6) -- 960(line=33, offs=5)
*/
/*
local: appendloc_8$0(level=1)
global: appendloc_8$0(level=1)
local: path$3489(1)(HSEapp(HSEcst(atstkind_type); HSEs2exp(S2Eextkind(atstype_ptrk))))
global: path$3489(1)(HSEapp(HSEcst(atstkind_type); HSEs2exp(S2Eextkind(atstype_ptrk))))
*/
ATSstaticdec()
atstkind_type(atstype_ptrk)
appendloc_8(atstkind_type(atstype_ptrk) env0, atstkind_type(atstype_ptrk) arg0, atstkind_t0ype(atstype_int) arg1, atstkind_t0ype(atstype_int) arg2)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret14, atstkind_type(atstype_ptrk)) ;
ATStmpdec(tmp15, atstype_boxed) ;
ATStmpdec(tmp16, atstype_boxed) ;
ATStmpdec(tmp17, atstype_boxed) ;
ATStmpdec(tmp18, atstkind_t0ype(atstype_char)) ;
ATStmpdec(tmp19, atstkind_type(atstype_ptrk)) ;
ATStmpdec(tmp21, atstkind_t0ype(atstype_bool)) ;
/* tmpvardeclst(end) */
/* funbodyinstrlst(beg) */
/*
emit_instr: loc0 = /vagrant/file.dats: 552(line=25, offs=6) -- 960(line=33, offs=5)
*/
ATSINSlab(__patsflab_appendloc_8):
/*
emit_instr: loc0 = /vagrant/file.dats: 656(line=25, offs=110) -- 960(line=33, offs=5)
*/
/*
letpush(beg)
*/
/*
emit_instr: loc0 = /vagrant/file.dats: 692(line=26, offs=32) -- 707(line=26, offs=47)
*/

ATSINSmove_con1(tmp16, postiats_tysum_1) ;
#if(0)
ATSINSstore_con_tag(tmp16, 0) ;
#endif
ATSINSstore_con_ofs(tmp16, postiats_tysum_1, atslab__0, arg1) ;
ATSINSstore_con_ofs(tmp16, postiats_tysum_1, atslab__1, arg2) ;

/*
emit_instr: loc0 = /vagrant/file.dats: 677(line=26, offs=17) -- 708(line=26, offs=48)
*/

ATSINSmove_con1(tmp15, postiats_tysum_2) ;
#if(1)
ATSINSstore_con_tag(tmp15, 2) ;
#endif
ATSINSstore_con_ofs(tmp15, postiats_tysum_2, atslab__0, env0) ;
ATSINSstore_con_ofs(tmp15, postiats_tysum_2, atslab__1, tmp16) ;

/*
letpush(end)
*/

/*
emit_instr: loc0 = /vagrant/file.dats: 720(line=27, offs=11) -- 722(line=27, offs=13)
*/
ATSINSmove_lazyeval(tmp17, atstype_boxed, arg0) ;
/*
emit_instr: loc0 = /vagrant/file.dats: 714(line=27, offs=5) -- 954(line=32, offs=75)
*/
ATScaseofbeg()
/*
** ibranchlst-beg
*/
ATSbranchbeg() ;
/*
emit_instr: loc0 = /vagrant/file.dats: 731(line=28, offs=5) -- 741(line=28, offs=15)
*/
__atstmplab0:
/*
emit_instr: loc0 = /vagrant/file.dats: 720(line=27, offs=11) -- 722(line=27, offs=13)
*/
if (ATSCKptriscons(tmp17)) { ATSgoto(__atstmplab3) ; }
/*
emit_instr: loc0 = /vagrant/file.dats: 741(line=28, offs=15) -- 741(line=28, offs=15)
*/
__atstmplab1:
/*
emit_instr: loc0 = : 0(line=0, offs=0) -- 0(line=0, offs=0)
*/
/*
ibranch-mbody:
*/
/*
emit_instr: loc0 = /vagrant/file.dats: 745(line=28, offs=19) -- 762(line=28, offs=36)
*/
ATSINSmove_delay(tmpret14, atstype_boxed, ATSPMVcfunlab(-1, __patsfun_9, ())) ;
ATSbranchend() ;

ATSbranchbeg() ;
/*
emit_instr: loc0 = /vagrant/file.dats: 768(line=29, offs=5) -- 784(line=29, offs=21)
*/
__atstmplab2:
/*
emit_instr: loc0 = /vagrant/file.dats: 720(line=27, offs=11) -- 722(line=27, offs=13)
*/
if (ATSCKptrisnull(tmp17)) { ATSINScaseof_fail("/vagrant/file.dats: 714(line=27, offs=5) -- 954(line=32, offs=75)") ; }
/*
emit_instr: loc0 = /vagrant/file.dats: 784(line=29, offs=21) -- 784(line=29, offs=21)
*/
__atstmplab3:
/*
emit_instr: loc0 = /vagrant/file.dats: 778(line=29, offs=15) -- 779(line=29, offs=16)
*/
ATSINSmove(tmp18, ATSSELcon(tmp17, postiats_tysum_0, atslab__0)) ;
/*
emit_instr: loc0 = /vagrant/file.dats: 781(line=29, offs=18) -- 783(line=29, offs=20)
*/
ATSINSmove(tmp19, ATSSELcon(tmp17, postiats_tysum_0, atslab__1)) ;
/*
emit_instr: loc0 = : 0(line=0, offs=0) -- 0(line=0, offs=0)
*/
/*
ibranch-mbody:
*/
/*
emit_instr: loc0 = /vagrant/file.dats: 796(line=30, offs=7) -- 804(line=30, offs=15)
*/
ATSINSmove(tmp21, atspre_eq_char0_char0(tmp18, ATSPMVchar('\n'))) ;

/*
emit_instr: loc0 = /vagrant/file.dats: 793(line=30, offs=4) -- 954(line=32, offs=75)
*/
ATSif(
tmp21
) ATSthen() {
/*
emit_instr: loc0 = /vagrant/file.dats: 814(line=31, offs=9) -- 878(line=31, offs=73)
*/
ATSINSmove_delay(tmpret14, atstype_boxed, ATSPMVcfunlab(-1, __patsfun_10, (env0, arg1, tmp15, tmp18, tmp19))) ;
} ATSelse() {
/*
emit_instr: loc0 = /vagrant/file.dats: 888(line=32, offs=9) -- 954(line=32, offs=75)
*/
ATSINSmove_delay(tmpret14, atstype_boxed, ATSPMVcfunlab(-1, __patsfun_12, (env0, arg1, arg2, tmp15, tmp18, tmp19))) ;
} /* ATSendif */
ATSbranchend() ;

/*
** ibranchlst-end
*/
ATScaseofend()

/*
emit_instr: loc0 = /vagrant/file.dats: 656(line=25, offs=110) -- 960(line=33, offs=5)
*/
/*
INSletpop()
*/
/* funbodyinstrlst(end) */
ATSreturn(tmpret14) ;
} /* end of [appendloc_8] */

/*
/vagrant/file.dats: 745(line=28, offs=19) -- 762(line=28, offs=36)
*/
/*
local: 
global: __patsfun_9$0(level=2)
local: 
global: 
*/
ATSstaticdec()
atstype_boxed
__patsfun_9()
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret20, atstype_boxed) ;
/* tmpvardeclst(end) */
/* funbodyinstrlst(beg) */
/*
emit_instr: loc0 = /vagrant/file.dats: 745(line=28, offs=19) -- 762(line=28, offs=36)
*/
ATSINSlab(__patsflab___patsfun_9):
/*
emit_instr: loc0 = /vagrant/file.dats: 752(line=28, offs=26) -- 762(line=28, offs=36)
*/

ATSINSmove_con0(tmpret20, 0) ;

/* funbodyinstrlst(end) */
ATSreturn(tmpret20) ;
} /* end of [__patsfun_9] */

/*
/vagrant/file.dats: 814(line=31, offs=9) -- 878(line=31, offs=73)
*/
/*
local: appendloc_8$0(level=1)
global: appendloc_8$0(level=1), __patsfun_10$0(level=2)
local: path$3489(1)(HSEapp(HSEcst(atstkind_type); HSEs2exp(S2Eextkind(atstype_ptrk)))), line$3495(2)(HSEapp(HSEcst(atstkind_t0ype); HSEs2exp(S2Eextkind(atstype_int)))), current$3497(2)(HSEcst(location)), x$3498(2)(HSEapp(HSEcst(atstkind_t0ype); HSEs2exp(S2Eextkind(atstype_char)))), xs$3499(2)(HSEapp(HSEcst(atstkind_type); HSEs2exp(S2Eextkind(atstype_ptrk))))
global: path$3489(1)(HSEapp(HSEcst(atstkind_type); HSEs2exp(S2Eextkind(atstype_ptrk)))), line$3495(2)(HSEapp(HSEcst(atstkind_t0ype); HSEs2exp(S2Eextkind(atstype_int)))), current$3497(2)(HSEcst(location)), x$3498(2)(HSEapp(HSEcst(atstkind_t0ype); HSEs2exp(S2Eextkind(atstype_char)))), xs$3499(2)(HSEapp(HSEcst(atstkind_type); HSEs2exp(S2Eextkind(atstype_ptrk))))
*/
ATSstaticdec()
atstype_boxed
__patsfun_10(atstkind_type(atstype_ptrk) env0, atstkind_t0ype(atstype_int) env1, atstype_boxed env2, atstkind_t0ype(atstype_char) env3, atstkind_type(atstype_ptrk) env4)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret22, atstype_boxed) ;
ATStmpdec(tmp23, atstype_boxed) ;
ATStmpdec(tmp24, atstkind_type(atstype_ptrk)) ;
ATStmpdec(tmp25, atstkind_t0ype(atstype_int)) ;
/* tmpvardeclst(end) */
/* funbodyinstrlst(beg) */
/*
emit_instr: loc0 = /vagrant/file.dats: 814(line=31, offs=9) -- 878(line=31, offs=73)
*/
ATSINSlab(__patsflab___patsfun_10):
/*
emit_instr: loc0 = /vagrant/file.dats: 832(line=31, offs=27) -- 849(line=31, offs=44)
*/

ATSINSmove_con1(tmp23, postiats_tysum_3) ;
#if(0)
ATSINSstore_con_tag(tmp23, 0) ;
#endif
ATSINSstore_con_ofs(tmp23, postiats_tysum_3, atslab__0, env3) ;
ATSINSstore_con_ofs(tmp23, postiats_tysum_3, atslab__1, env2) ;

/*
emit_instr: loc0 = /vagrant/file.dats: 866(line=31, offs=61) -- 872(line=31, offs=67)
*/
ATSINSmove(tmp25, atspre_g0int_add_int(env1, ATSPMVi0nt(1))) ;

/*
emit_instr: loc0 = /vagrant/file.dats: 851(line=31, offs=46) -- 876(line=31, offs=71)
*/
ATSINSmove(tmp24, appendloc_8(env0, env4, tmp25, ATSPMVi0nt(1))) ;

/*
emit_instr: loc0 = /vagrant/file.dats: 822(line=31, offs=17) -- 877(line=31, offs=72)
*/

ATSINSmove_con1(tmpret22, postiats_tysum_4) ;
#if(0)
ATSINSstore_con_tag(tmpret22, 0) ;
#endif
ATSINSstore_con_ofs(tmpret22, postiats_tysum_4, atslab__0, tmp23) ;
ATSINSstore_con_ofs(tmpret22, postiats_tysum_4, atslab__1, tmp24) ;

/* funbodyinstrlst(end) */
ATSreturn(tmpret22) ;
} /* end of [__patsfun_10] */

/*
/vagrant/file.dats: 888(line=32, offs=9) -- 954(line=32, offs=75)
*/
/*
local: appendloc_8$0(level=1)
global: appendloc_8$0(level=1), __patsfun_12$0(level=2)
local: path$3489(1)(HSEapp(HSEcst(atstkind_type); HSEs2exp(S2Eextkind(atstype_ptrk)))), line$3495(2)(HSEapp(HSEcst(atstkind_t0ype); HSEs2exp(S2Eextkind(atstype_int)))), col$3496(2)(HSEapp(HSEcst(atstkind_t0ype); HSEs2exp(S2Eextkind(atstype_int)))), current$3497(2)(HSEcst(location)), x$3498(2)(HSEapp(HSEcst(atstkind_t0ype); HSEs2exp(S2Eextkind(atstype_char)))), xs$3499(2)(HSEapp(HSEcst(atstkind_type); HSEs2exp(S2Eextkind(atstype_ptrk))))
global: path$3489(1)(HSEapp(HSEcst(atstkind_type); HSEs2exp(S2Eextkind(atstype_ptrk)))), line$3495(2)(HSEapp(HSEcst(atstkind_t0ype); HSEs2exp(S2Eextkind(atstype_int)))), col$3496(2)(HSEapp(HSEcst(atstkind_t0ype); HSEs2exp(S2Eextkind(atstype_int)))), current$3497(2)(HSEcst(location)), x$3498(2)(HSEapp(HSEcst(atstkind_t0ype); HSEs2exp(S2Eextkind(atstype_char)))), xs$3499(2)(HSEapp(HSEcst(atstkind_type); HSEs2exp(S2Eextkind(atstype_ptrk))))
*/
ATSstaticdec()
atstype_boxed
__patsfun_12(atstkind_type(atstype_ptrk) env0, atstkind_t0ype(atstype_int) env1, atstkind_t0ype(atstype_int) env2, atstype_boxed env3, atstkind_t0ype(atstype_char) env4, atstkind_type(atstype_ptrk) env5)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret26, atstype_boxed) ;
ATStmpdec(tmp27, atstype_boxed) ;
ATStmpdec(tmp28, atstkind_type(atstype_ptrk)) ;
ATStmpdec(tmp29, atstkind_t0ype(atstype_int)) ;
/* tmpvardeclst(end) */
/* funbodyinstrlst(beg) */
/*
emit_instr: loc0 = /vagrant/file.dats: 888(line=32, offs=9) -- 954(line=32, offs=75)
*/
ATSINSlab(__patsflab___patsfun_12):
/*
emit_instr: loc0 = /vagrant/file.dats: 906(line=32, offs=27) -- 923(line=32, offs=44)
*/

ATSINSmove_con1(tmp27, postiats_tysum_3) ;
#if(0)
ATSINSstore_con_tag(tmp27, 0) ;
#endif
ATSINSstore_con_ofs(tmp27, postiats_tysum_3, atslab__0, env4) ;
ATSINSstore_con_ofs(tmp27, postiats_tysum_3, atslab__1, env3) ;

/*
emit_instr: loc0 = /vagrant/file.dats: 946(line=32, offs=67) -- 951(line=32, offs=72)
*/
ATSINSmove(tmp29, atspre_g0int_add_int(env2, ATSPMVi0nt(1))) ;

/*
emit_instr: loc0 = /vagrant/file.dats: 925(line=32, offs=46) -- 952(line=32, offs=73)
*/
ATSINSmove(tmp28, appendloc_8(env0, env5, env1, tmp29)) ;

/*
emit_instr: loc0 = /vagrant/file.dats: 896(line=32, offs=17) -- 953(line=32, offs=74)
*/

ATSINSmove_con1(tmpret26, postiats_tysum_4) ;
#if(0)
ATSINSstore_con_tag(tmpret26, 0) ;
#endif
ATSINSstore_con_ofs(tmpret26, postiats_tysum_4, atslab__0, tmp27) ;
ATSINSstore_con_ofs(tmpret26, postiats_tysum_4, atslab__1, tmp28) ;

/* funbodyinstrlst(end) */
ATSreturn(tmpret26) ;
} /* end of [__patsfun_12] */

#if(0)
/*
** for initialization(dynloading)
*/
atsvoid_t0ype
_057_vagrant_057_file_056_dats__dynload()
{
ATSdynload0(
_057_vagrant_057_file_056_dats__dynloadflag
) ;
ATSif(
ATSCKiseqz(
_057_vagrant_057_file_056_dats__dynloadflag
)
) ATSthen() {
ATSdynloadset(_057_vagrant_057_file_056_dats__dynloadflag) ;
/*
dynexnlst-initize(beg)
*/
/*
dynexnlst-initize(end)
*/
} /* ATSendif */
ATSreturn_void() ;
} /* end of [*_dynload] */
#endif // end of [#if(0)]
