/*
**
** The C code is generated by ATS/Postiats
** The compilation time is: 2014-8-6: 19h: 5m
**
*/

/*
** include runtime header files
*/
#ifndef _ATS_CCOMP_HEADER_NONE
#include "pats_ccomp_config.h"
#include "pats_ccomp_basics.h"
#include "pats_ccomp_typedefs.h"
#include "pats_ccomp_instrset.h"
#include "pats_ccomp_memalloc.h"
#ifndef _ATS_CCOMP_EXCEPTION_NONE
#include "pats_ccomp_memalloca.h"
#include "pats_ccomp_exception.h"
#endif // end of [_ATS_CCOMP_EXCEPTION_NONE]
#endif /* _ATS_CCOMP_HEADER_NONE */


/*
** include prelude cats files
*/
#ifndef _ATS_CCOMP_PRELUDE_NONE
//
#include "prelude/CATS/basics.cats"
#include "prelude/CATS/integer.cats"
#include "prelude/CATS/pointer.cats"
#include "prelude/CATS/bool.cats"
#include "prelude/CATS/char.cats"
#include "prelude/CATS/integer_ptr.cats"
#include "prelude/CATS/integer_fixed.cats"
#include "prelude/CATS/float.cats"
#include "prelude/CATS/memory.cats"
#include "prelude/CATS/string.cats"
#include "prelude/CATS/strptr.cats"
//
#include "prelude/CATS/filebas.cats"
//
#include "prelude/CATS/list.cats"
#include "prelude/CATS/option.cats"
#include "prelude/CATS/array.cats"
#include "prelude/CATS/arrayptr.cats"
#include "prelude/CATS/arrayref.cats"
#include "prelude/CATS/matrix.cats"
#include "prelude/CATS/matrixptr.cats"
//
#endif /* _ATS_CCOMP_PRELUDE_NONE */
/*
** for user-supplied prelude
*/
#ifdef _ATS_CCOMP_PRELUDE_USER
//
#include _ATS_CCOMP_PRELUDE_USER
//
#endif /* _ATS_CCOMP_PRELUDE_USER */

/*
staload-prologues(beg)
*/
/*
staload-prologues(end)
*/
/*
typedefs-for-tyrecs-and-tysums(beg)
*/
typedef
struct {
#if(0)
int contag ;
#endif
atstkind_t0ype(atstype_int) atslab__0; 
atstkind_t0ype(atstype_int) atslab__1; 
} postiats_tysum_0 ;
typedef
struct {
#if(1)
int contag ;
#endif
atstkind_type(atstype_ptrk) atslab__0; 
atstype_boxed atslab__1; 
} postiats_tysum_1 ;
typedef
struct {
#if(1)
int contag ;
#endif
atstkind_type(atstype_ptrk) atslab__0; 
atstype_boxed atslab__1; 
atstype_boxed atslab__2; 
} postiats_tysum_2 ;
/*
typedefs-for-tyrecs-and-tysums(end)
*/
/*
dynconlst-declaration(beg)
*/
/*
dynconlst-declaration(end)
*/
/*
dyncstlst-declaration(beg)
*/
ATSdyncst_mac(atspre_fprint_string)
ATSdyncst_extfun(_057_vagrant_057_location_056_sats__fprint_position, (atstkind_type(atstype_ptrk), atstype_boxed), atsvoid_t0ype) ;
/*
dyncstlst-declaration(end)
*/
/*
dynvalist-implementation(beg)
*/
/*
dynvalist-implementation(end)
*/
/*
exnconlst-declaration(beg)
*/
#ifndef _ATS_CCOMP_EXCEPTION_NONE
extern void the_atsexncon_initize (atstype_exncon *d2c, char *exnmsg) ;
#endif // end of [_ATS_CCOMP_EXCEPTION_NONE]
/*
exnconlst-declaration(end)
*/
/*
assumelst-declaration(beg)
*/
/*
assumelst-declaration(end)
*/
/*
extypelst-declaration(beg)
*/
/*
extypelst-declaration(end)
*/
#if(0)
ATSglobaldec()
atsvoid_t0ype
_057_vagrant_057_location_056_sats__fprint_position(atstkind_type(atstype_ptrk), atstype_boxed) ;
#endif // end of [QUALIFIED]

#if(0)
ATSglobaldec()
atsvoid_t0ype
_057_vagrant_057_location_056_sats__fprint_location(atstkind_type(atstype_ptrk), atstype_boxed) ;
#endif // end of [QUALIFIED]

/*
/vagrant/location.dats: 83(line=5, offs=27) -- 183(line=6, offs=86)
*/
/*
local: 
global: fprint_position$0$0(level=0)
local: 
global: 
*/
ATSglobaldec()
atsvoid_t0ype
_057_vagrant_057_location_056_sats__fprint_position(atstkind_type(atstype_ptrk) arg0, atstype_boxed arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec_void(tmpret0, atsvoid_t0ype) ;
ATStmpdec(tmp1, atstkind_t0ype(atstype_int)) ;
ATStmpdec(tmp2, atstkind_t0ype(atstype_int)) ;
/* tmpvardeclst(end) */
/* funbodyinstrlst(beg) */
/*
emit_instr: loc0 = /vagrant/location.dats: 67(line=5, offs=11) -- 183(line=6, offs=86)
*/
ATSINSlab(__patsflab_fprint_position):
/*
emit_instr: loc0 = /vagrant/location.dats: 99(line=6, offs=2) -- 183(line=6, offs=86)
*/
ATScaseofbeg()
/*
** ibranchlst-beg
*/
ATSbranchbeg() ;
/*
emit_instr: loc0 = /vagrant/location.dats: 112(line=6, offs=15) -- 127(line=6, offs=30)
*/
__atstmplab0:
/*
emit_instr: loc0 = /vagrant/location.dats: 89(line=5, offs=33) -- 92(line=5, offs=36)
*/
#if(0)

#endif
/*
emit_instr: loc0 = /vagrant/location.dats: 127(line=6, offs=30) -- 127(line=6, offs=30)
*/
__atstmplab1:
/*
emit_instr: loc0 = /vagrant/location.dats: 117(line=6, offs=20) -- 121(line=6, offs=24)
*/
ATSINSmove(tmp1, ATSSELcon(arg1, postiats_tysum_0, atslab__0)) ;
/*
emit_instr: loc0 = /vagrant/location.dats: 123(line=6, offs=26) -- 126(line=6, offs=29)
*/
ATSINSmove(tmp2, ATSSELcon(arg1, postiats_tysum_0, atslab__1)) ;
/*
emit_instr: loc0 = : 0(line=0, offs=0) -- 0(line=0, offs=0)
*/
/*
ibranch-mbody:
*/
/*
emit_instr: loc0 = /vagrant/location.dats: 131(line=6, offs=34) -- 183(line=6, offs=86)
*/
ATSINSmove_void(tmpret0, fprintf(arg0, ATSPMVstring("%d:%d"), tmp1, tmp2)) ;
ATSbranchend() ;

/*
** ibranchlst-end
*/
ATScaseofend()

/* funbodyinstrlst(end) */
ATSreturn_void(tmpret0) ;
} /* end of [_057_vagrant_057_location_056_sats__fprint_position] */

/*
/vagrant/location.dats: 213(line=8, offs=27) -- 700(line=23, offs=3)
*/
/*
local: 
global: fprint_location$1$0(level=0)
local: 
global: 
*/
ATSglobaldec()
atsvoid_t0ype
_057_vagrant_057_location_056_sats__fprint_location(atstkind_type(atstype_ptrk) arg0, atstype_boxed arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec_void(tmpret3, atsvoid_t0ype) ;
ATStmpdec(tmp4, atstkind_type(atstype_ptrk)) ;
ATStmpdec(tmp5, atstype_boxed) ;
ATStmpdec(tmp6, atstkind_type(atstype_ptrk)) ;
ATStmpdec(tmp7, atstype_boxed) ;
ATStmpdec(tmp8, atstype_boxed) ;
ATStmpdec_void(tmp9, atsvoid_t0ype) ;
ATStmpdec_void(tmp10, atsvoid_t0ype) ;
ATStmpdec_void(tmp11, atsvoid_t0ype) ;
ATStmpdec_void(tmp12, atsvoid_t0ype) ;
ATStmpdec_void(tmp13, atsvoid_t0ype) ;
ATStmpdec_void(tmp14, atsvoid_t0ype) ;
ATStmpdec_void(tmp15, atsvoid_t0ype) ;
ATStmpdec_void(tmp16, atsvoid_t0ype) ;
/* tmpvardeclst(end) */
/* funbodyinstrlst(beg) */
/*
emit_instr: loc0 = /vagrant/location.dats: 197(line=8, offs=11) -- 700(line=23, offs=3)
*/
ATSINSlab(__patsflab_fprint_location):
/*
emit_instr: loc0 = /vagrant/location.dats: 229(line=9, offs=2) -- 700(line=23, offs=3)
*/
ATScaseofbeg()
/*
** ibranchlst-beg
*/
ATSbranchbeg() ;
/*
emit_instr: loc0 = /vagrant/location.dats: 246(line=10, offs=4) -- 253(line=10, offs=11)
*/
__atstmplab2:
/*
emit_instr: loc0 = /vagrant/location.dats: 219(line=8, offs=33) -- 222(line=8, offs=36)
*/
ATSifnot(ATSPATCKcon0(arg1, 0)) { ATSgoto(__atstmplab4) ; }
/*
emit_instr: loc0 = /vagrant/location.dats: 253(line=10, offs=11) -- 253(line=10, offs=11)
*/
__atstmplab3:
/*
emit_instr: loc0 = : 0(line=0, offs=0) -- 0(line=0, offs=0)
*/
/*
ibranch-mbody:
*/
/*
emit_instr: loc0 = /vagrant/location.dats: 263(line=10, offs=21) -- 283(line=10, offs=41)
*/
ATSINSmove_void(tmpret3, atspre_fprint_string(arg0, ATSPMVstring("none"))) ;

ATSbranchend() ;

ATSbranchbeg() ;
/*
emit_instr: loc0 = /vagrant/location.dats: 288(line=11, offs=4) -- 296(line=11, offs=12)
*/
__atstmplab4:
/*
emit_instr: loc0 = /vagrant/location.dats: 219(line=8, offs=33) -- 222(line=8, offs=36)
*/
ATSifnot(ATSPATCKcon0(arg1, 1)) { ATSgoto(__atstmplab6) ; }
/*
emit_instr: loc0 = /vagrant/location.dats: 296(line=11, offs=12) -- 296(line=11, offs=12)
*/
__atstmplab5:
/*
emit_instr: loc0 = : 0(line=0, offs=0) -- 0(line=0, offs=0)
*/
/*
ibranch-mbody:
*/
/*
emit_instr: loc0 = /vagrant/location.dats: 306(line=11, offs=22) -- 327(line=11, offs=43)
*/
ATSINSmove_void(tmpret3, atspre_fprint_string(arg0, ATSPMVstring("stdin"))) ;

ATSbranchend() ;

ATSbranchbeg() ;
/*
emit_instr: loc0 = /vagrant/location.dats: 332(line=12, offs=4) -- 349(line=12, offs=21)
*/
__atstmplab6:
/*
emit_instr: loc0 = /vagrant/location.dats: 219(line=8, offs=33) -- 222(line=8, offs=36)
*/
ATSifnot(ATSPATCKcon1(arg1, 2)) { ATSgoto(__atstmplab8) ; }
/*
emit_instr: loc0 = /vagrant/location.dats: 349(line=12, offs=21) -- 349(line=12, offs=21)
*/
__atstmplab7:
/*
emit_instr: loc0 = /vagrant/location.dats: 341(line=12, offs=13) -- 345(line=12, offs=17)
*/
ATSINSmove(tmp4, ATSSELcon(arg1, postiats_tysum_1, atslab__0)) ;
/*
emit_instr: loc0 = /vagrant/location.dats: 347(line=12, offs=19) -- 348(line=12, offs=20)
*/
ATSINSmove(tmp5, ATSSELcon(arg1, postiats_tysum_1, atslab__1)) ;
/*
emit_instr: loc0 = : 0(line=0, offs=0) -- 0(line=0, offs=0)
*/
/*
ibranch-mbody:
*/
/*
emit_instr: loc0 = /vagrant/location.dats: 355(line=12, offs=27) -- 483(line=16, offs=3)
*/
/*
letpush(beg)
*/
/*
emit_instr: loc0 = /vagrant/location.dats: 377(line=13, offs=11) -- 423(line=13, offs=57)
*/
ATSINSmove_void(tmp9, fprintf(arg0, ATSPMVstring("%s ["), tmp4)) ;
/*
emit_instr: loc0 = /vagrant/location.dats: 435(line=14, offs=11) -- 450(line=14, offs=26)
*/
ATSINSmove_void(tmp10, _057_vagrant_057_location_056_sats__fprint_position(arg0, tmp5)) ;

/*
emit_instr: loc0 = /vagrant/location.dats: 462(line=15, offs=11) -- 479(line=15, offs=28)
*/
ATSINSmove_void(tmp11, atspre_fprint_string(arg0, ATSPMVstring("]"))) ;

/*
letpush(end)
*/

/*
emit_instr: loc0 = /vagrant/location.dats: 355(line=12, offs=27) -- 357(line=12, offs=29)
*/
ATSINSmove_void(tmpret3, ATSempty()) ;
/*
emit_instr: loc0 = /vagrant/location.dats: 355(line=12, offs=27) -- 483(line=16, offs=3)
*/
/*
INSletpop()
*/
ATSbranchend() ;

ATSbranchbeg() ;
/*
emit_instr: loc0 = /vagrant/location.dats: 488(line=17, offs=4) -- 510(line=17, offs=26)
*/
__atstmplab8:
/*
emit_instr: loc0 = /vagrant/location.dats: 219(line=8, offs=33) -- 222(line=8, offs=36)
*/
#if(0)
ATSifnot(ATSPATCKcon1(arg1, 3)) { ATSINSdeadcode_fail() ; }
#endif
/*
emit_instr: loc0 = /vagrant/location.dats: 510(line=17, offs=26) -- 510(line=17, offs=26)
*/
__atstmplab9:
/*
emit_instr: loc0 = /vagrant/location.dats: 499(line=17, offs=15) -- 503(line=17, offs=19)
*/
ATSINSmove(tmp6, ATSSELcon(arg1, postiats_tysum_2, atslab__0)) ;
/*
emit_instr: loc0 = /vagrant/location.dats: 505(line=17, offs=21) -- 506(line=17, offs=22)
*/
ATSINSmove(tmp7, ATSSELcon(arg1, postiats_tysum_2, atslab__1)) ;
/*
emit_instr: loc0 = /vagrant/location.dats: 508(line=17, offs=24) -- 509(line=17, offs=25)
*/
ATSINSmove(tmp8, ATSSELcon(arg1, postiats_tysum_2, atslab__2)) ;
/*
emit_instr: loc0 = : 0(line=0, offs=0) -- 0(line=0, offs=0)
*/
/*
ibranch-mbody:
*/
/*
emit_instr: loc0 = /vagrant/location.dats: 514(line=17, offs=30) -- 700(line=23, offs=3)
*/
/*
letpush(beg)
*/
/*
emit_instr: loc0 = /vagrant/location.dats: 536(line=18, offs=11) -- 582(line=18, offs=57)
*/
ATSINSmove_void(tmp12, fprintf(arg0, ATSPMVstring("%s ["), tmp6)) ;
/*
emit_instr: loc0 = /vagrant/location.dats: 594(line=19, offs=11) -- 609(line=19, offs=26)
*/
ATSINSmove_void(tmp13, _057_vagrant_057_location_056_sats__fprint_position(arg0, tmp7)) ;

/*
emit_instr: loc0 = /vagrant/location.dats: 621(line=20, offs=11) -- 640(line=20, offs=30)
*/
ATSINSmove_void(tmp14, atspre_fprint_string(arg0, ATSPMVstring(" - "))) ;

/*
emit_instr: loc0 = /vagrant/location.dats: 652(line=21, offs=11) -- 667(line=21, offs=26)
*/
ATSINSmove_void(tmp15, _057_vagrant_057_location_056_sats__fprint_position(arg0, tmp8)) ;

/*
emit_instr: loc0 = /vagrant/location.dats: 679(line=22, offs=11) -- 696(line=22, offs=28)
*/
ATSINSmove_void(tmp16, atspre_fprint_string(arg0, ATSPMVstring("]"))) ;

/*
letpush(end)
*/

/*
emit_instr: loc0 = /vagrant/location.dats: 514(line=17, offs=30) -- 516(line=17, offs=32)
*/
ATSINSmove_void(tmpret3, ATSempty()) ;
/*
emit_instr: loc0 = /vagrant/location.dats: 514(line=17, offs=30) -- 700(line=23, offs=3)
*/
/*
INSletpop()
*/
ATSbranchend() ;

/*
** ibranchlst-end
*/
ATScaseofend()

/* funbodyinstrlst(end) */
ATSreturn_void(tmpret3) ;
} /* end of [_057_vagrant_057_location_056_sats__fprint_location] */

#if(0)
/*
** for initialization(dynloading)
*/
atsvoid_t0ype
_057_vagrant_057_location_056_dats__dynload()
{
ATSdynload0(
_057_vagrant_057_location_056_dats__dynloadflag
) ;
ATSif(
ATSCKiseqz(
_057_vagrant_057_location_056_dats__dynloadflag
)
) ATSthen() {
ATSdynloadset(_057_vagrant_057_location_056_dats__dynloadflag) ;
/*
dynexnlst-initize(beg)
*/
/*
dynexnlst-initize(end)
*/
} /* ATSendif */
ATSreturn_void() ;
} /* end of [*_dynload] */
#endif // end of [#if(0)]
