/*
**
** The C code is generated by ATS/Postiats
** The compilation time is: 2014-8-6: 19h: 5m
**
*/

/*
** include runtime header files
*/
#ifndef _ATS_CCOMP_HEADER_NONE
#include "pats_ccomp_config.h"
#include "pats_ccomp_basics.h"
#include "pats_ccomp_typedefs.h"
#include "pats_ccomp_instrset.h"
#include "pats_ccomp_memalloc.h"
#ifndef _ATS_CCOMP_EXCEPTION_NONE
#include "pats_ccomp_memalloca.h"
#include "pats_ccomp_exception.h"
#endif // end of [_ATS_CCOMP_EXCEPTION_NONE]
#endif /* _ATS_CCOMP_HEADER_NONE */


/*
** include prelude cats files
*/
#ifndef _ATS_CCOMP_PRELUDE_NONE
//
#include "prelude/CATS/basics.cats"
#include "prelude/CATS/integer.cats"
#include "prelude/CATS/pointer.cats"
#include "prelude/CATS/bool.cats"
#include "prelude/CATS/char.cats"
#include "prelude/CATS/integer_ptr.cats"
#include "prelude/CATS/integer_fixed.cats"
#include "prelude/CATS/float.cats"
#include "prelude/CATS/memory.cats"
#include "prelude/CATS/string.cats"
#include "prelude/CATS/strptr.cats"
//
#include "prelude/CATS/filebas.cats"
//
#include "prelude/CATS/list.cats"
#include "prelude/CATS/option.cats"
#include "prelude/CATS/array.cats"
#include "prelude/CATS/arrayptr.cats"
#include "prelude/CATS/arrayref.cats"
#include "prelude/CATS/matrix.cats"
#include "prelude/CATS/matrixptr.cats"
//
#endif /* _ATS_CCOMP_PRELUDE_NONE */
/*
** for user-supplied prelude
*/
#ifdef _ATS_CCOMP_PRELUDE_USER
//
#include _ATS_CCOMP_PRELUDE_USER
//
#endif /* _ATS_CCOMP_PRELUDE_USER */

/*
staload-prologues(beg)
*/
/*
/vagrant/pair.sats: 1(line=1, offs=1) -- 21(line=1, offs=21)
*/
/*
/vagrant/token.sats: 1(line=1, offs=1) -- 20(line=1, offs=20)
*/
/*
/vagrant/token.sats: 22(line=2, offs=1) -- 45(line=2, offs=24)
*/
/*
/vagrant/token.sats: 1(line=1, offs=1) -- 20(line=1, offs=20)
*/
/*
/vagrant/token.sats: 22(line=2, offs=1) -- 45(line=2, offs=24)
*/
/*
/vagrant/token.dats: 1(line=1, offs=1) -- 31(line=1, offs=31)
*/
/*
/ats2/libc/SATS/stdio.sats: 1380(line=35, offs=1) -- 1418(line=37, offs=3)
*/

#include "libc/CATS/stdio.cats"
/*
/ats2/libc/SATS/stdio.sats: 1791(line=56, offs=1) -- 1833(line=58, offs=27)
*/
/*
/ats2/libc/sys/SATS/types.sats: 1390(line=36, offs=1) -- 1432(line=38, offs=3)
*/

#include "libc/sys/CATS/types.cats"
/*
/vagrant/token.dats: 33(line=2, offs=1) -- 53(line=2, offs=21)
*/
/*
/vagrant/token.sats: 1(line=1, offs=1) -- 20(line=1, offs=20)
*/
/*
/vagrant/token.sats: 22(line=2, offs=1) -- 45(line=2, offs=24)
*/
/*
/vagrant/token.dats: 55(line=3, offs=1) -- 78(line=3, offs=24)
*/
/*
staload-prologues(end)
*/
/*
typedefs-for-tyrecs-and-tysums(beg)
*/
typedef
struct {
#if(0)
int contag ;
#endif
atstype_boxed atslab__0; 
atstype_boxed atslab__1; 
} postiats_tysum_0 ;
/*
typedefs-for-tyrecs-and-tysums(end)
*/
/*
dynconlst-declaration(beg)
*/
/*
dynconlst-declaration(end)
*/
/*
dyncstlst-declaration(beg)
*/
ATSdyncst_mac(atspre_fprint_string)
ATSdyncst_extfun(_057_vagrant_057_token_056_sats__fprint_token, (atstkind_type(atstype_ptrk), atstype_boxed), atsvoid_t0ype) ;
/*
dyncstlst-declaration(end)
*/
/*
dynvalist-implementation(beg)
*/
/*
dynvalist-implementation(end)
*/
/*
exnconlst-declaration(beg)
*/
#ifndef _ATS_CCOMP_EXCEPTION_NONE
extern void the_atsexncon_initize (atstype_exncon *d2c, char *exnmsg) ;
#endif // end of [_ATS_CCOMP_EXCEPTION_NONE]
/*
exnconlst-declaration(end)
*/
/*
assumelst-declaration(beg)
*/
/*
assumelst-declaration(end)
*/
/*
extypelst-declaration(beg)
*/
/*
extypelst-declaration(end)
*/
#if(0)
ATSglobaldec()
atsvoid_t0ype
_057_vagrant_057_pair_056_sats__fprint_pair_token(atstkind_type(atstype_ptrk), atstype_boxed) ;
#endif // end of [QUALIFIED]

/*
/vagrant/pair.dats: 127(line=6, offs=29) -- 315(line=13, offs=2)
*/
/*
local: 
global: fprint_pair_token$0$0(level=0)
local: 
global: 
*/
ATSglobaldec()
atsvoid_t0ype
_057_vagrant_057_pair_056_sats__fprint_pair_token(atstkind_type(atstype_ptrk) arg0, atstype_boxed arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec_void(tmpret0, atsvoid_t0ype) ;
ATStmpdec_void(tmp1, atsvoid_t0ype) ;
ATStmpdec(tmp2, atstype_boxed) ;
ATStmpdec(tmp3, atstype_boxed) ;
ATStmpdec_void(tmp4, atsvoid_t0ype) ;
ATStmpdec_void(tmp5, atsvoid_t0ype) ;
ATStmpdec_void(tmp6, atsvoid_t0ype) ;
ATStmpdec_void(tmp7, atsvoid_t0ype) ;
/* tmpvardeclst(end) */
/* funbodyinstrlst(beg) */
/*
emit_instr: loc0 = /vagrant/pair.dats: 109(line=6, offs=11) -- 315(line=13, offs=2)
*/
ATSINSlab(__patsflab_fprint_pair_token):
/*
emit_instr: loc0 = /vagrant/pair.dats: 138(line=6, offs=40) -- 315(line=13, offs=2)
*/
/*
letpush(beg)
*/
/*
emit_instr: loc0 = /vagrant/pair.dats: 159(line=7, offs=10) -- 181(line=7, offs=32)
*/
ATSINSmove_void(tmp1, atspre_fprint_string(arg0, ATSPMVstring("Pair ("))) ;

/*
emit_instr: loc0 = /vagrant/pair.dats: 188(line=8, offs=6) -- 199(line=8, offs=17)
*/

/*
emit_instr: loc0 = /vagrant/pair.dats: 194(line=8, offs=12) -- 195(line=8, offs=13)
*/
ATSINSmove(tmp2, ATSSELcon(arg1, postiats_tysum_0, atslab__0)) ;
/*
emit_instr: loc0 = /vagrant/pair.dats: 197(line=8, offs=15) -- 198(line=8, offs=16)
*/
ATSINSmove(tmp3, ATSSELcon(arg1, postiats_tysum_0, atslab__1)) ;
/*
emit_instr: loc0 = /vagrant/pair.dats: 214(line=9, offs=10) -- 229(line=9, offs=25)
*/
ATSINSmove_void(tmp4, _057_vagrant_057_token_056_sats__fprint_token(arg0, tmp2)) ;

/*
emit_instr: loc0 = /vagrant/pair.dats: 240(line=10, offs=10) -- 258(line=10, offs=28)
*/
ATSINSmove_void(tmp5, atspre_fprint_string(arg0, ATSPMVstring(", "))) ;

/*
emit_instr: loc0 = /vagrant/pair.dats: 269(line=11, offs=10) -- 284(line=11, offs=25)
*/
ATSINSmove_void(tmp6, _057_vagrant_057_token_056_sats__fprint_token(arg0, tmp3)) ;

/*
emit_instr: loc0 = /vagrant/pair.dats: 295(line=12, offs=10) -- 312(line=12, offs=27)
*/
ATSINSmove_void(tmp7, atspre_fprint_string(arg0, ATSPMVstring(")"))) ;

/*
letpush(end)
*/

/*
emit_instr: loc0 = /vagrant/pair.dats: 138(line=6, offs=40) -- 140(line=6, offs=42)
*/
ATSINSmove_void(tmpret0, ATSempty()) ;
/*
emit_instr: loc0 = /vagrant/pair.dats: 138(line=6, offs=40) -- 315(line=13, offs=2)
*/
/*
INSletpop()
*/
/* funbodyinstrlst(end) */
ATSreturn_void(tmpret0) ;
} /* end of [_057_vagrant_057_pair_056_sats__fprint_pair_token] */

#if(0)
/*
** for initialization(dynloading)
*/
atsvoid_t0ype
_057_vagrant_057_pair_056_dats__dynload()
{
ATSdynload0(
_057_vagrant_057_pair_056_dats__dynloadflag
) ;
ATSif(
ATSCKiseqz(
_057_vagrant_057_pair_056_dats__dynloadflag
)
) ATSthen() {
ATSdynloadset(_057_vagrant_057_pair_056_dats__dynloadflag) ;
/*
dynexnlst-initize(beg)
*/
/*
dynexnlst-initize(end)
*/
} /* ATSendif */
ATSreturn_void() ;
} /* end of [*_dynload] */
#endif // end of [#if(0)]
