/*
**
** The C code is generated by ATS/Postiats
** The compilation time is: 2014-8-6: 19h: 5m
**
*/

/*
** include runtime header files
*/
#ifndef _ATS_CCOMP_HEADER_NONE
#include "pats_ccomp_config.h"
#include "pats_ccomp_basics.h"
#include "pats_ccomp_typedefs.h"
#include "pats_ccomp_instrset.h"
#include "pats_ccomp_memalloc.h"
#ifndef _ATS_CCOMP_EXCEPTION_NONE
#include "pats_ccomp_memalloca.h"
#include "pats_ccomp_exception.h"
#endif // end of [_ATS_CCOMP_EXCEPTION_NONE]
#endif /* _ATS_CCOMP_HEADER_NONE */


/*
** include prelude cats files
*/
#ifndef _ATS_CCOMP_PRELUDE_NONE
//
#include "prelude/CATS/basics.cats"
#include "prelude/CATS/integer.cats"
#include "prelude/CATS/pointer.cats"
#include "prelude/CATS/bool.cats"
#include "prelude/CATS/char.cats"
#include "prelude/CATS/integer_ptr.cats"
#include "prelude/CATS/integer_fixed.cats"
#include "prelude/CATS/float.cats"
#include "prelude/CATS/memory.cats"
#include "prelude/CATS/string.cats"
#include "prelude/CATS/strptr.cats"
//
#include "prelude/CATS/filebas.cats"
//
#include "prelude/CATS/list.cats"
#include "prelude/CATS/option.cats"
#include "prelude/CATS/array.cats"
#include "prelude/CATS/arrayptr.cats"
#include "prelude/CATS/arrayref.cats"
#include "prelude/CATS/matrix.cats"
#include "prelude/CATS/matrixptr.cats"
//
#endif /* _ATS_CCOMP_PRELUDE_NONE */
/*
** for user-supplied prelude
*/
#ifdef _ATS_CCOMP_PRELUDE_USER
//
#include _ATS_CCOMP_PRELUDE_USER
//
#endif /* _ATS_CCOMP_PRELUDE_USER */

/*
staload-prologues(beg)
*/
/*
/vagrant/parcc.sats: 39(line=3, offs=1) -- 58(line=3, offs=20)
*/
/*
/vagrant/pair.sats: 1(line=1, offs=1) -- 21(line=1, offs=21)
*/
/*
/vagrant/token.sats: 1(line=1, offs=1) -- 20(line=1, offs=20)
*/
/*
/vagrant/token.sats: 22(line=2, offs=1) -- 45(line=2, offs=24)
*/
/*
/vagrant/parcc.sats: 59(line=4, offs=1) -- 79(line=4, offs=21)
*/
/*
/vagrant/token.sats: 1(line=1, offs=1) -- 20(line=1, offs=20)
*/
/*
/vagrant/token.sats: 22(line=2, offs=1) -- 45(line=2, offs=24)
*/
/*
/vagrant/parcc.sats: 80(line=5, offs=1) -- 100(line=5, offs=21)
*/
/*
/vagrant/parcc.sats: 101(line=6, offs=1) -- 124(line=6, offs=24)
*/
/*
/vagrant/parcc.sats: 125(line=7, offs=1) -- 144(line=7, offs=20)
*/
/*
/vagrant/parcc.sats: 145(line=8, offs=1) -- 171(line=8, offs=27)
*/
/*
/vagrant/stream.sats: 1(line=1, offs=1) -- 21(line=1, offs=21)
*/
/*
/vagrant/pair.sats: 1(line=1, offs=1) -- 21(line=1, offs=21)
*/
/*
/vagrant/token.sats: 1(line=1, offs=1) -- 20(line=1, offs=20)
*/
/*
/vagrant/token.sats: 22(line=2, offs=1) -- 45(line=2, offs=24)
*/
/*
/vagrant/token.sats: 1(line=1, offs=1) -- 20(line=1, offs=20)
*/
/*
/vagrant/token.sats: 22(line=2, offs=1) -- 45(line=2, offs=24)
*/
/*
/vagrant/stream.sats: 1(line=1, offs=1) -- 21(line=1, offs=21)
*/
/*
/vagrant/stream.dats: 30(line=3, offs=1) -- 51(line=3, offs=22)
*/
/*
/vagrant/stream.sats: 1(line=1, offs=1) -- 21(line=1, offs=21)
*/
/*
/vagrant/stream.dats: 53(line=4, offs=1) -- 73(line=4, offs=21)
*/
/*
/vagrant/location.dats: 30(line=3, offs=1) -- 53(line=3, offs=24)
*/
/*
staload-prologues(end)
*/
/*
typedefs-for-tyrecs-and-tysums(beg)
*/
typedef
struct {
#if(1)
int contag ;
#endif
atstyvar_type(o) atslab__0; 
atstyvar_type(i) atslab__1; 
} postiats_tysum_0 ;
typedef
struct {
#if(1)
int contag ;
#endif
atstyvar_type(o) atslab__0; 
atstyvar_type(i) atslab__1; 
} postiats_tysum_1 ;
typedef
struct {
#if(0)
int contag ;
#endif
atstyvar_type(o1) atslab__0; 
atstyvar_type(o2) atslab__1; 
} postiats_tysum_2 ;
typedef
struct {
#if(1)
int contag ;
#endif
atstyvar_type(i) atslab__0; 
} postiats_tysum_3 ;
typedef
struct {
#if(1)
int contag ;
#endif
atstyvar_type(o) atslab__0; 
atstyvar_type(i) atslab__1; 
} postiats_tysum_4 ;
typedef
struct {
#if(1)
int contag ;
#endif
atstyvar_type(o) atslab__0; 
atstyvar_type(i) atslab__1; 
} postiats_tysum_5 ;
typedef
struct {
#if(0)
int contag ;
#endif
atstyvar_type(o) atslab__0; 
} postiats_tysum_6 ;
typedef
struct {
#if(1)
int contag ;
#endif
atstype_boxed atslab__0; 
atstyvar_type(i) atslab__1; 
} postiats_tysum_7 ;
typedef
struct {
#if(1)
int contag ;
#endif
atstyvar_type(i) atslab__0; 
} postiats_tysum_8 ;
typedef
struct {
#if(0)
int contag ;
#endif
atstyvar_type(o) atslab__0; 
atstype_boxed atslab__1; 
} postiats_tysum_9 ;
typedef
struct {
#if(0)
int contag ;
#endif
atstype_boxed atslab__0; 
} postiats_tysum_10 ;
typedef
struct {
#if(1)
int contag ;
#endif
atstyvar_type(o1) atslab__0; 
atstyvar_type(i) atslab__1; 
} postiats_tysum_11 ;
typedef
struct {
#if(1)
int contag ;
#endif
atstyvar_type(i) atslab__0; 
} postiats_tysum_12 ;
typedef
struct {
#if(1)
int contag ;
#endif
atstkind_type(atstype_ptrk) atslab__0; 
} postiats_tysum_13 ;
typedef
struct {
#if(0)
int contag ;
#endif
atstype_boxed atslab__0; 
atstkind_type(atstype_ptrk) atslab__1; 
} postiats_tysum_14 ;
typedef
struct {
#if(0)
int contag ;
#endif
atstkind_t0ype(atstype_char) atslab__0; 
atstype_boxed atslab__1; 
} postiats_tysum_15 ;
typedef
struct {
#if(1)
int contag ;
#endif
atstkind_t0ype(atstype_char) atslab__0; 
atstype_boxed atslab__1; 
} postiats_tysum_16 ;
typedef
struct {
#if(1)
int contag ;
#endif
atstype_boxed atslab__0; 
atstkind_type(atstype_ptrk) atslab__1; 
} postiats_tysum_17 ;
/*
typedefs-for-tyrecs-and-tysums(end)
*/
/*
dynconlst-declaration(beg)
*/
/*
dynconlst-declaration(end)
*/
/*
dyncstlst-declaration(beg)
*/
ATSdyncst_mac(atspre_eq_char0_char0)
/*
dyncstlst-declaration(end)
*/
/*
dynvalist-implementation(beg)
*/
/*
dynvalist-implementation(end)
*/
/*
exnconlst-declaration(beg)
*/
#ifndef _ATS_CCOMP_EXCEPTION_NONE
extern void the_atsexncon_initize (atstype_exncon *d2c, char *exnmsg) ;
#endif // end of [_ATS_CCOMP_EXCEPTION_NONE]
/*
exnconlst-declaration(end)
*/
/*
assumelst-declaration(beg)
*/
/*
assumelst-declaration(end)
*/
/*
extypelst-declaration(beg)
*/
/*
extypelst-declaration(end)
*/
#if(0)
#if(0)
ATSglobaldec()
atstype_cloptr
_057_vagrant_057_parcc_056_sats__succeed__0(atstyvar_type(o)) ;
#endif // end of [QUALIFIED]
#endif // end of [TEMPLATE]

#if(0)
ATSstaticdec()
atstype_boxed
__patsfun_1__1(atstyvar_type(o), atstyvar_type(i)) ;
#endif // end of [TEMPLATE]

#if(0)
#if(0)
ATSglobaldec()
atstype_cloptr
_057_vagrant_057_parcc_056_sats__alt__2(atstype_cloptr, atstype_cloptr) ;
#endif // end of [QUALIFIED]
#endif // end of [TEMPLATE]

#if(0)
ATSstaticdec()
atstype_boxed
__patsfun_3__3(atstype_funptr, atstype_funptr, atstyvar_type(i)) ;
#endif // end of [TEMPLATE]

#if(0)
#if(0)
ATSglobaldec()
atstype_cloptr
_057_vagrant_057_parcc_056_sats__seq__4(atstype_cloptr, atstype_cloptr) ;
#endif // end of [QUALIFIED]
#endif // end of [TEMPLATE]

#if(0)
ATSstaticdec()
atstype_cloptr
__patsfun_5__5(atstype_funptr, atstyvar_type(o1)) ;
#endif // end of [TEMPLATE]

#if(0)
ATSstaticdec()
atstype_cloptr
__patsfun_6__6(atstyvar_type(o1), atstyvar_type(o2)) ;
#endif // end of [TEMPLATE]

#if(0)
#if(0)
ATSglobaldec()
atstype_cloptr
_057_vagrant_057_parcc_056_sats__sat__7(atstype_cloptr, atstype_cloptr) ;
#endif // end of [QUALIFIED]
#endif // end of [TEMPLATE]

#if(0)
ATSstaticdec()
atstype_boxed
__patsfun_8__8(atstype_funptr, atstype_funptr, atstyvar_type(i)) ;
#endif // end of [TEMPLATE]

#if(0)
#if(0)
ATSglobaldec()
atstype_cloptr
_057_vagrant_057_parcc_056_sats__opt__9(atstype_cloptr) ;
#endif // end of [QUALIFIED]
#endif // end of [TEMPLATE]

#if(0)
ATSstaticdec()
atstype_boxed
__patsfun_10__10(atstype_funptr, atstyvar_type(i)) ;
#endif // end of [TEMPLATE]

#if(0)
#if(0)
ATSglobaldec()
atstype_cloptr
_057_vagrant_057_parcc_056_sats__rpt1__11(atstype_cloptr) ;
#endif // end of [QUALIFIED]
#endif // end of [TEMPLATE]

#if(0)
ATSstaticdec()
atstype_cloptr
__patsfun_12__12(atstype_funptr, atstyvar_type(o)) ;
#endif // end of [TEMPLATE]

#if(0)
ATSstaticdec()
atstype_cloptr
__patsfun_13__13(atstyvar_type(o), atstype_boxed) ;
#endif // end of [TEMPLATE]

#if(0)
#if(0)
ATSglobaldec()
atstype_cloptr
_057_vagrant_057_parcc_056_sats__rpt0__14(atstype_cloptr) ;
#endif // end of [QUALIFIED]
#endif // end of [TEMPLATE]

#if(0)
ATSstaticdec()
atstype_cloptr
__patsfun_15__15(atstype_boxed) ;
#endif // end of [TEMPLATE]

#if(0)
#if(0)
ATSglobaldec()
atstype_boxed
_057_vagrant_057_parcc_056_sats__apply__16(atstype_cloptr, atstyvar_type(i)) ;
#endif // end of [QUALIFIED]
#endif // end of [TEMPLATE]

#if(0)
#if(0)
ATSglobaldec()
atstype_cloptr
_057_vagrant_057_parcc_056_sats__bind__17(atstype_cloptr, atstype_cloptr) ;
#endif // end of [QUALIFIED]
#endif // end of [TEMPLATE]

#if(0)
ATSstaticdec()
atstype_boxed
__patsfun_18__18(atstype_funptr, atstype_funptr, atstyvar_type(i)) ;
#endif // end of [TEMPLATE]

#if(0)
ATSglobaldec()
atstype_cloptr
_057_vagrant_057_parcc_056_sats__lit_char(atstkind_t0ype(atstype_char)) ;
#endif // end of [QUALIFIED]

ATSstaticdec()
atstype_boxed
__patsfun_20(atstkind_t0ype(atstype_char), atstkind_type(atstype_ptrk)) ;

ATSstaticdec()
atstype_boxed
__patsfun_21(atstype_boxed, atstkind_type(atstype_ptrk)) ;

typedef struct
{
atstype_funptr cfun ;
atstkind_t0ype(atstype_char) env0 ;
} __patsfun_20__closure_t0ype ;
ATSstaticdec()
atstype_boxed
__patsfun_20__cfun
(
__patsfun_20__closure_t0ype *p_cenv, atstkind_type(atstype_ptrk) arg0
)
{
ATSFCreturn(__patsfun_20(p_cenv->env0, arg0)) ;
} /* end of [cfun] */
ATSstaticdec()
atstype_cloptr
__patsfun_20__closureinit
(
__patsfun_20__closure_t0ype *p_cenv, atstkind_t0ype(atstype_char) env0
)
{
p_cenv->env0 = env0 ;
p_cenv->cfun = __patsfun_20__cfun ;
return p_cenv ;
} /* end of [closureinit] */
ATSstaticdec()
atstype_cloptr
__patsfun_20__closurerize
(
atstkind_t0ype(atstype_char) env0
)
{
return __patsfun_20__closureinit(ATS_MALLOC(sizeof(__patsfun_20__closure_t0ype)), env0) ;
} /* end of [closurerize] */

typedef struct
{
atstype_funptr cfun ;
atstype_boxed env0 ;
atstkind_type(atstype_ptrk) env1 ;
} __patsfun_21__closure_t0ype ;
ATSstaticdec()
atstype_boxed
__patsfun_21__cfun
(
__patsfun_21__closure_t0ype *p_cenv
)
{
ATSFCreturn(__patsfun_21(p_cenv->env0, p_cenv->env1)) ;
} /* end of [cfun] */
ATSstaticdec()
atstype_cloptr
__patsfun_21__closureinit
(
__patsfun_21__closure_t0ype *p_cenv, atstype_boxed env0, atstkind_type(atstype_ptrk) env1
)
{
p_cenv->env0 = env0 ;
p_cenv->env1 = env1 ;
p_cenv->cfun = __patsfun_21__cfun ;
return p_cenv ;
} /* end of [closureinit] */
ATSstaticdec()
atstype_cloptr
__patsfun_21__closurerize
(
atstype_boxed env0, atstkind_type(atstype_ptrk) env1
)
{
return __patsfun_21__closureinit(ATS_MALLOC(sizeof(__patsfun_21__closure_t0ype)), env0, env1) ;
} /* end of [closurerize] */

#if(0)
/*
/vagrant/parcc.dats: 288(line=17, offs=27) -- 334(line=18, offs=37)
*/
/*
local: 
global: succeed$0$0(level=0)
local: 
global: 
*/
ATSglobaldec()
/*
imparg = i(7660), o(7661)
tmparg = S2Evar(i(7660)); S2Evar(o(7661))
tmpsub = None()
*/
atstype_cloptr
_057_vagrant_057_parcc_056_sats__succeed__0(atstyvar_type(o) arg0)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret0, atstype_funptr) ;
/* tmpvardeclst(end) */
/* funbodyinstrlst(beg) */
/*
emit_instr: loc0 = /vagrant/parcc.dats: 280(line=17, offs=19) -- 334(line=18, offs=37)
*/
ATSINSlab(__patsflab_succeed):
/*
emit_instr: loc0 = /vagrant/parcc.dats: 299(line=18, offs=2) -- 334(line=18, offs=37)
*/
ATSINSmove(tmpret0, ATSPMVcfunlab(-1, __patsfun_1__1, (arg0))) ;
/* funbodyinstrlst(end) */
ATSreturn(tmpret0) ;
} /* end of [_057_vagrant_057_parcc_056_sats__succeed__0] */
#endif // end of [TEMPLATE]

#if(0)
/*
/vagrant/parcc.dats: 299(line=18, offs=2) -- 334(line=18, offs=37)
*/
/*
local: 
global: __patsfun_1$0(level=1)
local: ret$3489(1)(HSEtyvar(o(7661)))
global: ret$3489(1)(HSEtyvar(o(7661)))
*/
ATSstaticdec()
atstype_boxed
__patsfun_1__1(atstyvar_type(o) env0, atstyvar_type(i) arg0)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret1, atstype_boxed) ;
/* tmpvardeclst(end) */
/* funbodyinstrlst(beg) */
/*
emit_instr: loc0 = /vagrant/parcc.dats: 299(line=18, offs=2) -- 334(line=18, offs=37)
*/
ATSINSlab(__patsflab___patsfun_1):
/*
emit_instr: loc0 = /vagrant/parcc.dats: 314(line=18, offs=17) -- 334(line=18, offs=37)
*/

ATSINSmove_con1(tmpret1, postiats_tysum_0) ;
#if(1)
ATSINSstore_con_tag(tmpret1, 0) ;
#endif
ATSINSstore_con_ofs(tmpret1, postiats_tysum_0, atslab__0, env0) ;
ATSINSstore_con_ofs(tmpret1, postiats_tysum_0, atslab__1, arg0) ;

/* funbodyinstrlst(end) */
ATSreturn(tmpret1) ;
} /* end of [__patsfun_1__1] */
#endif // end of [TEMPLATE]

#if(0)
/*
/vagrant/parcc.dats: 383(line=25, offs=23) -- 525(line=29, offs=34)
*/
/*
local: 
global: alt$2$0(level=0)
local: 
global: 
*/
ATSglobaldec()
/*
imparg = i(7662), o(7663)
tmparg = S2Evar(i(7662)); S2Evar(o(7663))
tmpsub = None()
*/
atstype_cloptr
_057_vagrant_057_parcc_056_sats__alt__2(atstype_cloptr arg0, atstype_cloptr arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret2, atstype_funptr) ;
/* tmpvardeclst(end) */
/* funbodyinstrlst(beg) */
/*
emit_instr: loc0 = /vagrant/parcc.dats: 379(line=25, offs=19) -- 525(line=29, offs=34)
*/
ATSINSlab(__patsflab_alt):
/*
emit_instr: loc0 = /vagrant/parcc.dats: 395(line=26, offs=2) -- 525(line=29, offs=34)
*/
ATSINSmove(tmpret2, ATSPMVcfunlab(-1, __patsfun_3__3, (arg0, arg1))) ;
/* funbodyinstrlst(end) */
ATSreturn(tmpret2) ;
} /* end of [_057_vagrant_057_parcc_056_sats__alt__2] */
#endif // end of [TEMPLATE]

#if(0)
/*
/vagrant/parcc.dats: 395(line=26, offs=2) -- 525(line=29, offs=34)
*/
/*
local: 
global: __patsfun_3$0(level=1)
local: a$3491(1)(HSEfun(HSEtyvar(i(7662)); HSEtybox())), b$3492(1)(HSEfun(HSEtyvar(i(7662)); HSEtybox()))
global: a$3491(1)(HSEfun(HSEtyvar(i(7662)); HSEtybox())), b$3492(1)(HSEfun(HSEtyvar(i(7662)); HSEtybox()))
*/
ATSstaticdec()
atstype_boxed
__patsfun_3__3(atstype_funptr env0, atstype_funptr env1, atstyvar_type(i) arg0)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret3, atstype_boxed) ;
ATStmpdec(tmp4, atstype_boxed) ;
ATStmpdec(tmp5, atstyvar_type(o)) ;
ATStmpdec(tmp6, atstyvar_type(i)) ;
/* tmpvardeclst(end) */
/* funbodyinstrlst(beg) */
/*
emit_instr: loc0 = /vagrant/parcc.dats: 395(line=26, offs=2) -- 525(line=29, offs=34)
*/
ATSINSlab(__patsflab___patsfun_3):
/*
emit_instr: loc0 = /vagrant/parcc.dats: 420(line=27, offs=9) -- 436(line=27, offs=25)
*/
ATSINSmove(tmp4, PMVtmpltcst(apply<S2Evar(i(7662))><S2Evar(o(7663))>)(env0, arg0)) ;

/*
emit_instr: loc0 = /vagrant/parcc.dats: 414(line=27, offs=3) -- 525(line=29, offs=34)
*/
ATScaseofbeg()
/*
** ibranchlst-beg
*/
ATSbranchbeg() ;
/*
emit_instr: loc0 = /vagrant/parcc.dats: 446(line=28, offs=5) -- 466(line=28, offs=25)
*/
__atstmplab0:
/*
emit_instr: loc0 = /vagrant/parcc.dats: 420(line=27, offs=9) -- 436(line=27, offs=25)
*/
ATSifnot(ATSPATCKcon1(tmp4, 0)) { ATSgoto(__atstmplab3) ; }
/*
emit_instr: loc0 = /vagrant/parcc.dats: 466(line=28, offs=25) -- 466(line=28, offs=25)
*/
__atstmplab1:
/*
emit_instr: loc0 = /vagrant/parcc.dats: 455(line=28, offs=14) -- 458(line=28, offs=17)
*/
ATSINSmove(tmp5, ATSSELcon(tmp4, postiats_tysum_1, atslab__0)) ;
/*
emit_instr: loc0 = /vagrant/parcc.dats: 460(line=28, offs=19) -- 465(line=28, offs=24)
*/
ATSINSmove(tmp6, ATSSELcon(tmp4, postiats_tysum_1, atslab__1)) ;
/*
emit_instr: loc0 = : 0(line=0, offs=0) -- 0(line=0, offs=0)
*/
/*
ibranch-mbody:
*/
/*
emit_instr: loc0 = /vagrant/parcc.dats: 470(line=28, offs=29) -- 490(line=28, offs=49)
*/

ATSINSmove_con1(tmpret3, postiats_tysum_1) ;
#if(1)
ATSINSstore_con_tag(tmpret3, 0) ;
#endif
ATSINSstore_con_ofs(tmpret3, postiats_tysum_1, atslab__0, tmp5) ;
ATSINSstore_con_ofs(tmpret3, postiats_tysum_1, atslab__1, tmp6) ;

ATSbranchend() ;

ATSbranchbeg() ;
/*
emit_instr: loc0 = /vagrant/parcc.dats: 496(line=29, offs=5) -- 505(line=29, offs=14)
*/
__atstmplab2:
/*
emit_instr: loc0 = /vagrant/parcc.dats: 420(line=27, offs=9) -- 436(line=27, offs=25)
*/
#if(0)
ATSifnot(ATSPATCKcon1(tmp4, 1)) { ATSINSdeadcode_fail() ; }
#endif
/*
emit_instr: loc0 = /vagrant/parcc.dats: 505(line=29, offs=14) -- 505(line=29, offs=14)
*/
__atstmplab3:
/*
emit_instr: loc0 = : 0(line=0, offs=0) -- 0(line=0, offs=0)
*/
/*
ibranch-mbody:
*/
/*
emit_instr: loc0 = /vagrant/parcc.dats: 509(line=29, offs=18) -- 525(line=29, offs=34)
*/
ATSINSmove(tmpret3, PMVtmpltcst(apply<S2Evar(i(7662))><S2Evar(o(7663))>)(env1, arg0)) ;

ATSbranchend() ;

/*
** ibranchlst-end
*/
ATScaseofend()

/* funbodyinstrlst(end) */
ATSreturn(tmpret3) ;
} /* end of [__patsfun_3__3] */
#endif // end of [TEMPLATE]

#if(0)
/*
/vagrant/parcc.dats: 559(line=32, offs=27) -- 643(line=35, offs=47)
*/
/*
local: 
global: seq$4$0(level=0)
local: 
global: 
*/
ATSglobaldec()
/*
imparg = i(7668), o1(7669), o2(7670)
tmparg = S2Evar(i(7668)); S2Evar(o1(7669)), S2Evar(o2(7670))
tmpsub = None()
*/
atstype_cloptr
_057_vagrant_057_parcc_056_sats__seq__4(atstype_cloptr arg0, atstype_cloptr arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret7, atstype_cloptr) ;
/* tmpvardeclst(end) */
/* funbodyinstrlst(beg) */
/*
emit_instr: loc0 = /vagrant/parcc.dats: 555(line=32, offs=23) -- 643(line=35, offs=47)
*/
ATSINSlab(__patsflab_seq):
/*
emit_instr: loc0 = /vagrant/parcc.dats: 571(line=33, offs=2) -- 643(line=35, offs=47)
*/
ATSINSmove(tmpret7, PMVtmpltcst(bind<S2Evar(i(7668))><S2Evar(o1(7669)), S2Eapp(S2Ecst(pair); S2Evar(o1(7669)), S2Evar(o2(7670)))>)(arg0, ATSPMVcfunlab(-1, __patsfun_5__5, (arg1)))) ;

/* funbodyinstrlst(end) */
ATSreturn(tmpret7) ;
} /* end of [_057_vagrant_057_parcc_056_sats__seq__4] */
#endif // end of [TEMPLATE]

#if(0)
/*
/vagrant/parcc.dats: 584(line=34, offs=3) -- 642(line=35, offs=46)
*/
/*
local: 
global: __patsfun_5$0(level=1)
local: b$3497(1)(HSEfun(HSEtyvar(i(7668)); HSEtybox()))
global: b$3497(1)(HSEfun(HSEtyvar(i(7668)); HSEtybox()))
*/
ATSstaticdec()
atstype_cloptr
__patsfun_5__5(atstype_funptr env0, atstyvar_type(o1) arg0)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret8, atstype_cloptr) ;
/* tmpvardeclst(end) */
/* funbodyinstrlst(beg) */
/*
emit_instr: loc0 = /vagrant/parcc.dats: 584(line=34, offs=3) -- 642(line=35, offs=46)
*/
ATSINSlab(__patsflab___patsfun_5):
/*
emit_instr: loc0 = /vagrant/parcc.dats: 600(line=35, offs=4) -- 642(line=35, offs=46)
*/
ATSINSmove(tmpret8, PMVtmpltcst(bind<S2Evar(i(7668))><S2Evar(o2(7670)), S2Eapp(S2Ecst(pair); S2Evar(o1(7669)), S2Evar(o2(7670)))>)(env0, ATSPMVcfunlab(-1, __patsfun_6__6, (arg0)))) ;

/* funbodyinstrlst(end) */
ATSreturn(tmpret8) ;
} /* end of [__patsfun_5__5] */
#endif // end of [TEMPLATE]

#if(0)
/*
/vagrant/parcc.dats: 609(line=35, offs=13) -- 641(line=35, offs=45)
*/
/*
local: 
global: __patsfun_6$0(level=2)
local: x$3498(2)(HSEtyvar(o1(7669)))
global: x$3498(2)(HSEtyvar(o1(7669)))
*/
ATSstaticdec()
atstype_cloptr
__patsfun_6__6(atstyvar_type(o1) env0, atstyvar_type(o2) arg0)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret9, atstype_cloptr) ;
ATStmpdec(tmp10, atstype_boxed) ;
/* tmpvardeclst(end) */
/* funbodyinstrlst(beg) */
/*
emit_instr: loc0 = /vagrant/parcc.dats: 609(line=35, offs=13) -- 641(line=35, offs=45)
*/
ATSINSlab(__patsflab___patsfun_6):
/*
emit_instr: loc0 = /vagrant/parcc.dats: 629(line=35, offs=33) -- 640(line=35, offs=44)
*/

ATSINSmove_con1(tmp10, postiats_tysum_2) ;
#if(0)
ATSINSstore_con_tag(tmp10, 0) ;
#endif
ATSINSstore_con_ofs(tmp10, postiats_tysum_2, atslab__0, env0) ;
ATSINSstore_con_ofs(tmp10, postiats_tysum_2, atslab__1, arg0) ;

/*
emit_instr: loc0 = /vagrant/parcc.dats: 620(line=35, offs=24) -- 640(line=35, offs=44)
*/
ATSINSmove(tmpret9, PMVtmpltcst(succeed<S2Evar(i(7668))><S2Eapp(S2Ecst(pair); S2Evar(o1(7669)), S2Evar(o2(7670)))>)(tmp10)) ;

/* funbodyinstrlst(end) */
ATSreturn(tmpret9) ;
} /* end of [__patsfun_6__6] */
#endif // end of [TEMPLATE]

#if(0)
/*
/vagrant/parcc.dats: 669(line=37, offs=23) -- 859(line=44, offs=24)
*/
/*
local: 
global: sat$7$0(level=0)
local: 
global: 
*/
ATSglobaldec()
/*
imparg = i(7671), o(7672)
tmparg = S2Evar(i(7671)); S2Evar(o(7672))
tmpsub = None()
*/
atstype_cloptr
_057_vagrant_057_parcc_056_sats__sat__7(atstype_cloptr arg0, atstype_cloptr arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret11, atstype_funptr) ;
/* tmpvardeclst(end) */
/* funbodyinstrlst(beg) */
/*
emit_instr: loc0 = /vagrant/parcc.dats: 665(line=37, offs=19) -- 859(line=44, offs=24)
*/
ATSINSlab(__patsflab_sat):
/*
emit_instr: loc0 = /vagrant/parcc.dats: 681(line=38, offs=2) -- 859(line=44, offs=24)
*/
ATSINSmove(tmpret11, ATSPMVcfunlab(-1, __patsfun_8__8, (arg0, arg1))) ;
/* funbodyinstrlst(end) */
ATSreturn(tmpret11) ;
} /* end of [_057_vagrant_057_parcc_056_sats__sat__7] */
#endif // end of [TEMPLATE]

#if(0)
/*
/vagrant/parcc.dats: 681(line=38, offs=2) -- 859(line=44, offs=24)
*/
/*
local: 
global: __patsfun_8$0(level=1)
local: p$3500(1)(HSEfun(HSEtyvar(i(7671)); HSEtybox())), f$3501(1)(HSEfun(HSEtyvar(o(7672)); HSEapp(HSEcst(atstkind_t0ype); HSEs2exp(S2Eextkind(atstype_bool)))))
global: p$3500(1)(HSEfun(HSEtyvar(i(7671)); HSEtybox())), f$3501(1)(HSEfun(HSEtyvar(o(7672)); HSEapp(HSEcst(atstkind_t0ype); HSEs2exp(S2Eextkind(atstype_bool)))))
*/
ATSstaticdec()
atstype_boxed
__patsfun_8__8(atstype_funptr env0, atstype_funptr env1, atstyvar_type(i) arg0)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret12, atstype_boxed) ;
ATStmpdec(tmp13, atstype_boxed) ;
ATStmpdec(tmp14, atstyvar_type(o)) ;
ATStmpdec(tmp15, atstyvar_type(i)) ;
ATStmpdec(tmp16, atstkind_t0ype(atstype_bool)) ;
/* tmpvardeclst(end) */
/* funbodyinstrlst(beg) */
/*
emit_instr: loc0 = /vagrant/parcc.dats: 681(line=38, offs=2) -- 859(line=44, offs=24)
*/
ATSINSlab(__patsflab___patsfun_8):
/*
emit_instr: loc0 = /vagrant/parcc.dats: 706(line=39, offs=9) -- 722(line=39, offs=25)
*/
ATSINSmove(tmp13, PMVtmpltcst(apply<S2Evar(i(7671))><S2Evar(o(7672))>)(env0, arg0)) ;

/*
emit_instr: loc0 = /vagrant/parcc.dats: 700(line=39, offs=3) -- 859(line=44, offs=24)
*/
ATScaseofbeg()
/*
** ibranchlst-beg
*/
ATSbranchbeg() ;
/*
emit_instr: loc0 = /vagrant/parcc.dats: 732(line=40, offs=5) -- 741(line=40, offs=14)
*/
__atstmplab4:
/*
emit_instr: loc0 = /vagrant/parcc.dats: 706(line=39, offs=9) -- 722(line=39, offs=25)
*/
ATSifnot(ATSPATCKcon1(tmp13, 1)) { ATSgoto(__atstmplab7) ; }
/*
emit_instr: loc0 = /vagrant/parcc.dats: 741(line=40, offs=14) -- 741(line=40, offs=14)
*/
__atstmplab5:
/*
emit_instr: loc0 = : 0(line=0, offs=0) -- 0(line=0, offs=0)
*/
/*
ibranch-mbody:
*/
/*
emit_instr: loc0 = /vagrant/parcc.dats: 745(line=40, offs=18) -- 759(line=40, offs=32)
*/

ATSINSmove_con1(tmpret12, postiats_tysum_3) ;
#if(1)
ATSINSstore_con_tag(tmpret12, 1) ;
#endif
ATSINSstore_con_ofs(tmpret12, postiats_tysum_3, atslab__0, arg0) ;

ATSbranchend() ;

ATSbranchbeg() ;
/*
emit_instr: loc0 = /vagrant/parcc.dats: 767(line=41, offs=5) -- 786(line=41, offs=24)
*/
__atstmplab6:
/*
emit_instr: loc0 = /vagrant/parcc.dats: 706(line=39, offs=9) -- 722(line=39, offs=25)
*/
#if(0)
ATSifnot(ATSPATCKcon1(tmp13, 0)) { ATSINSdeadcode_fail() ; }
#endif
/*
emit_instr: loc0 = /vagrant/parcc.dats: 786(line=41, offs=24) -- 786(line=41, offs=24)
*/
__atstmplab7:
/*
emit_instr: loc0 = /vagrant/parcc.dats: 776(line=41, offs=14) -- 779(line=41, offs=17)
*/
ATSINSmove(tmp14, ATSSELcon(tmp13, postiats_tysum_4, atslab__0)) ;
/*
emit_instr: loc0 = /vagrant/parcc.dats: 781(line=41, offs=19) -- 785(line=41, offs=23)
*/
ATSINSmove(tmp15, ATSSELcon(tmp13, postiats_tysum_4, atslab__1)) ;
/*
emit_instr: loc0 = : 0(line=0, offs=0) -- 0(line=0, offs=0)
*/
/*
ibranch-mbody:
*/
/*
emit_instr: loc0 = /vagrant/parcc.dats: 797(line=42, offs=7) -- 803(line=42, offs=13)
*/
ATSINSmove(tmp16, ATSfunclo_clo(env1, (atstype_cloptr, atstyvar_type(o)), atstkind_t0ype(atstype_bool))(env1, tmp14)) ;

/*
emit_instr: loc0 = /vagrant/parcc.dats: 794(line=42, offs=4) -- 859(line=44, offs=24)
*/
ATSif(
tmp16
) ATSthen() {
/*
emit_instr: loc0 = /vagrant/parcc.dats: 814(line=43, offs=9) -- 833(line=43, offs=28)
*/

ATSINSmove_con1(tmpret12, postiats_tysum_4) ;
#if(1)
ATSINSstore_con_tag(tmpret12, 0) ;
#endif
ATSINSstore_con_ofs(tmpret12, postiats_tysum_4, atslab__0, tmp14) ;
ATSINSstore_con_ofs(tmpret12, postiats_tysum_4, atslab__1, tmp15) ;

} ATSelse() {
/*
emit_instr: loc0 = /vagrant/parcc.dats: 844(line=44, offs=9) -- 858(line=44, offs=23)
*/

ATSINSmove_con1(tmpret12, postiats_tysum_3) ;
#if(1)
ATSINSstore_con_tag(tmpret12, 1) ;
#endif
ATSINSstore_con_ofs(tmpret12, postiats_tysum_3, atslab__0, arg0) ;

} /* ATSendif */
ATSbranchend() ;

/*
** ibranchlst-end
*/
ATScaseofend()

/* funbodyinstrlst(end) */
ATSreturn(tmpret12) ;
} /* end of [__patsfun_8__8] */
#endif // end of [TEMPLATE]

#if(0)
/*
/vagrant/parcc.dats: 885(line=46, offs=23) -- 1045(line=50, offs=51)
*/
/*
local: 
global: opt$9$0(level=0)
local: 
global: 
*/
ATSglobaldec()
/*
imparg = i(7677), o(7678)
tmparg = S2Evar(i(7677)); S2Evar(o(7678))
tmpsub = None()
*/
atstype_cloptr
_057_vagrant_057_parcc_056_sats__opt__9(atstype_cloptr arg0)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret17, atstype_funptr) ;
/* tmpvardeclst(end) */
/* funbodyinstrlst(beg) */
/*
emit_instr: loc0 = /vagrant/parcc.dats: 881(line=46, offs=19) -- 1045(line=50, offs=51)
*/
ATSINSlab(__patsflab_opt):
/*
emit_instr: loc0 = /vagrant/parcc.dats: 893(line=47, offs=2) -- 1045(line=50, offs=51)
*/
ATSINSmove(tmpret17, ATSPMVcfunlab(-1, __patsfun_10__10, (arg0))) ;
/* funbodyinstrlst(end) */
ATSreturn(tmpret17) ;
} /* end of [_057_vagrant_057_parcc_056_sats__opt__9] */
#endif // end of [TEMPLATE]

#if(0)
/*
/vagrant/parcc.dats: 893(line=47, offs=2) -- 1045(line=50, offs=51)
*/
/*
local: 
global: __patsfun_10$0(level=1)
local: p$3505(1)(HSEfun(HSEtyvar(i(7677)); HSEtybox()))
global: p$3505(1)(HSEfun(HSEtyvar(i(7677)); HSEtybox()))
*/
ATSstaticdec()
atstype_boxed
__patsfun_10__10(atstype_funptr env0, atstyvar_type(i) arg0)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret18, atstype_boxed) ;
ATStmpdec(tmp19, atstype_boxed) ;
ATStmpdec(tmp20, atstyvar_type(o)) ;
ATStmpdec(tmp21, atstyvar_type(i)) ;
ATStmpdec(tmp22, atstyvar_type(i)) ;
ATStmpdec(tmp23, atstype_boxed) ;
ATStmpdec(tmp24, atstype_boxed) ;
/* tmpvardeclst(end) */
/* funbodyinstrlst(beg) */
/*
emit_instr: loc0 = /vagrant/parcc.dats: 893(line=47, offs=2) -- 1045(line=50, offs=51)
*/
ATSINSlab(__patsflab___patsfun_10):
/*
emit_instr: loc0 = /vagrant/parcc.dats: 918(line=48, offs=9) -- 934(line=48, offs=25)
*/
ATSINSmove(tmp19, PMVtmpltcst(apply<S2Evar(i(7677))><S2Evar(o(7678))>)(env0, arg0)) ;

/*
emit_instr: loc0 = /vagrant/parcc.dats: 912(line=48, offs=3) -- 1045(line=50, offs=51)
*/
ATScaseofbeg()
/*
** ibranchlst-beg
*/
ATSbranchbeg() ;
/*
emit_instr: loc0 = /vagrant/parcc.dats: 944(line=49, offs=5) -- 963(line=49, offs=24)
*/
__atstmplab8:
/*
emit_instr: loc0 = /vagrant/parcc.dats: 918(line=48, offs=9) -- 934(line=48, offs=25)
*/
ATSifnot(ATSPATCKcon1(tmp19, 0)) { ATSgoto(__atstmplab11) ; }
/*
emit_instr: loc0 = /vagrant/parcc.dats: 963(line=49, offs=24) -- 963(line=49, offs=24)
*/
__atstmplab9:
/*
emit_instr: loc0 = /vagrant/parcc.dats: 953(line=49, offs=14) -- 956(line=49, offs=17)
*/
ATSINSmove(tmp20, ATSSELcon(tmp19, postiats_tysum_5, atslab__0)) ;
/*
emit_instr: loc0 = /vagrant/parcc.dats: 958(line=49, offs=19) -- 962(line=49, offs=23)
*/
ATSINSmove(tmp21, ATSSELcon(tmp19, postiats_tysum_5, atslab__1)) ;
/*
emit_instr: loc0 = : 0(line=0, offs=0) -- 0(line=0, offs=0)
*/
/*
ibranch-mbody:
*/
/*
emit_instr: loc0 = /vagrant/parcc.dats: 976(line=49, offs=37) -- 985(line=49, offs=46)
*/

ATSINSmove_con1(tmp23, postiats_tysum_6) ;
#if(0)
ATSINSstore_con_tag(tmp23, 1) ;
#endif
ATSINSstore_con_ofs(tmp23, postiats_tysum_6, atslab__0, tmp20) ;

/*
emit_instr: loc0 = /vagrant/parcc.dats: 967(line=49, offs=28) -- 993(line=49, offs=54)
*/

ATSINSmove_con1(tmpret18, postiats_tysum_7) ;
#if(1)
ATSINSstore_con_tag(tmpret18, 0) ;
#endif
ATSINSstore_con_ofs(tmpret18, postiats_tysum_7, atslab__0, tmp23) ;
ATSINSstore_con_ofs(tmpret18, postiats_tysum_7, atslab__1, tmp21) ;

ATSbranchend() ;

ATSbranchbeg() ;
/*
emit_instr: loc0 = /vagrant/parcc.dats: 999(line=50, offs=5) -- 1013(line=50, offs=19)
*/
__atstmplab10:
/*
emit_instr: loc0 = /vagrant/parcc.dats: 918(line=48, offs=9) -- 934(line=48, offs=25)
*/
#if(0)
ATSifnot(ATSPATCKcon1(tmp19, 1)) { ATSINSdeadcode_fail() ; }
#endif
/*
emit_instr: loc0 = /vagrant/parcc.dats: 1013(line=50, offs=19) -- 1013(line=50, offs=19)
*/
__atstmplab11:
/*
emit_instr: loc0 = /vagrant/parcc.dats: 1008(line=50, offs=14) -- 1013(line=50, offs=19)
*/
ATSINSmove(tmp22, ATSSELcon(tmp19, postiats_tysum_8, atslab__0)) ;
/*
emit_instr: loc0 = : 0(line=0, offs=0) -- 0(line=0, offs=0)
*/
/*
ibranch-mbody:
*/
/*
emit_instr: loc0 = /vagrant/parcc.dats: 1027(line=50, offs=33) -- 1037(line=50, offs=43)
*/

ATSINSmove_con0(tmp24, 0) ;

/*
emit_instr: loc0 = /vagrant/parcc.dats: 1018(line=50, offs=24) -- 1045(line=50, offs=51)
*/

ATSINSmove_con1(tmpret18, postiats_tysum_7) ;
#if(1)
ATSINSstore_con_tag(tmpret18, 0) ;
#endif
ATSINSstore_con_ofs(tmpret18, postiats_tysum_7, atslab__0, tmp24) ;
ATSINSstore_con_ofs(tmpret18, postiats_tysum_7, atslab__1, tmp22) ;

ATSbranchend() ;

/*
** ibranchlst-end
*/
ATScaseofend()

/* funbodyinstrlst(end) */
ATSreturn(tmpret18) ;
} /* end of [__patsfun_10__10] */
#endif // end of [TEMPLATE]

#if(0)
/*
/vagrant/parcc.dats: 1072(line=52, offs=24) -- 1152(line=55, offs=47)
*/
/*
local: 
global: rpt1$11$0(level=0)
local: 
global: 
*/
ATSglobaldec()
/*
imparg = i(7683), o(7684)
tmparg = S2Evar(i(7683)); S2Evar(o(7684))
tmpsub = None()
*/
atstype_cloptr
_057_vagrant_057_parcc_056_sats__rpt1__11(atstype_cloptr arg0)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret25, atstype_cloptr) ;
/* tmpvardeclst(end) */
/* funbodyinstrlst(beg) */
/*
emit_instr: loc0 = /vagrant/parcc.dats: 1067(line=52, offs=19) -- 1152(line=55, offs=47)
*/
ATSINSlab(__patsflab_rpt1):
/*
emit_instr: loc0 = /vagrant/parcc.dats: 1081(line=53, offs=2) -- 1152(line=55, offs=47)
*/
ATSINSmove(tmpret25, PMVtmpltcst(bind<S2Evar(i(7683))><S2Evar(o(7684)), S2Eapp(S2Ecst(list); S2Evar(o(7684)))>)(arg0, ATSPMVcfunlab(-1, __patsfun_12__12, (arg0)))) ;

/* funbodyinstrlst(end) */
ATSreturn(tmpret25) ;
} /* end of [_057_vagrant_057_parcc_056_sats__rpt1__11] */
#endif // end of [TEMPLATE]

#if(0)
/*
/vagrant/parcc.dats: 1094(line=54, offs=3) -- 1151(line=55, offs=46)
*/
/*
local: 
global: __patsfun_12$0(level=1)
local: p$3510(1)(HSEfun(HSEtyvar(i(7683)); HSEtybox()))
global: p$3510(1)(HSEfun(HSEtyvar(i(7683)); HSEtybox()))
*/
ATSstaticdec()
atstype_cloptr
__patsfun_12__12(atstype_funptr env0, atstyvar_type(o) arg0)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret26, atstype_cloptr) ;
ATStmpdec(tmp27, atstype_cloptr) ;
/* tmpvardeclst(end) */
/* funbodyinstrlst(beg) */
/*
emit_instr: loc0 = /vagrant/parcc.dats: 1094(line=54, offs=3) -- 1151(line=55, offs=46)
*/
ATSINSlab(__patsflab___patsfun_12):
/*
emit_instr: loc0 = /vagrant/parcc.dats: 1115(line=55, offs=10) -- 1121(line=55, offs=16)
*/
ATSINSmove(tmp27, PMVtmpltcst(rpt0<S2Evar(i(7683))><S2Evar(o(7684))>)(env0)) ;

/*
emit_instr: loc0 = /vagrant/parcc.dats: 1109(line=55, offs=4) -- 1151(line=55, offs=46)
*/
ATSINSmove(tmpret26, PMVtmpltcst(bind<S2Evar(i(7683))><S2Eapp(S2Ecst(list); S2EVar(4186->S2Evar(o(7684)))), S2Eapp(S2Ecst(list); S2Evar(o(7684)))>)(tmp27, ATSPMVcfunlab(-1, __patsfun_13__13, (arg0)))) ;

/* funbodyinstrlst(end) */
ATSreturn(tmpret26) ;
} /* end of [__patsfun_12__12] */
#endif // end of [TEMPLATE]

#if(0)
/*
/vagrant/parcc.dats: 1123(line=55, offs=18) -- 1150(line=55, offs=45)
*/
/*
local: 
global: __patsfun_13$0(level=2)
local: x$3511(2)(HSEtyvar(o(7684)))
global: x$3511(2)(HSEtyvar(o(7684)))
*/
ATSstaticdec()
atstype_cloptr
__patsfun_13__13(atstyvar_type(o) env0, atstype_boxed arg0)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret28, atstype_cloptr) ;
ATStmpdec(tmp29, atstype_boxed) ;
/* tmpvardeclst(end) */
/* funbodyinstrlst(beg) */
/*
emit_instr: loc0 = /vagrant/parcc.dats: 1123(line=55, offs=18) -- 1150(line=55, offs=45)
*/
ATSINSlab(__patsflab___patsfun_13):
/*
emit_instr: loc0 = /vagrant/parcc.dats: 1143(line=55, offs=38) -- 1149(line=55, offs=44)
*/

ATSINSmove_con1(tmp29, postiats_tysum_9) ;
#if(0)
ATSINSstore_con_tag(tmp29, 0) ;
#endif
ATSINSstore_con_ofs(tmp29, postiats_tysum_9, atslab__0, env0) ;
ATSINSstore_con_ofs(tmp29, postiats_tysum_9, atslab__1, arg0) ;

/*
emit_instr: loc0 = /vagrant/parcc.dats: 1134(line=55, offs=29) -- 1149(line=55, offs=44)
*/
ATSINSmove(tmpret28, PMVtmpltcst(succeed<S2Evar(i(7683))><S2Eapp(S2Ecst(list); S2Evar(o(7684)))>)(tmp29)) ;

/* funbodyinstrlst(end) */
ATSreturn(tmpret28) ;
} /* end of [__patsfun_13__13] */
#endif // end of [TEMPLATE]

#if(0)
/*
/vagrant/parcc.dats: 1179(line=57, offs=24) -- 1303(line=62, offs=3)
*/
/*
local: 
global: rpt0$14$0(level=0)
local: 
global: 
*/
ATSglobaldec()
/*
imparg = i(7685), o(7686)
tmparg = S2Evar(i(7685)); S2Evar(o(7686))
tmpsub = None()
*/
atstype_cloptr
_057_vagrant_057_parcc_056_sats__rpt0__14(atstype_cloptr arg0)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret30, atstype_cloptr) ;
ATStmpdec(tmp31, atstype_cloptr) ;
ATStmpdec(tmp32, atstype_cloptr) ;
/* tmpvardeclst(end) */
/* funbodyinstrlst(beg) */
/*
emit_instr: loc0 = /vagrant/parcc.dats: 1174(line=57, offs=19) -- 1303(line=62, offs=3)
*/
ATSINSlab(__patsflab_rpt0):
/*
emit_instr: loc0 = /vagrant/parcc.dats: 1199(line=58, offs=13) -- 1205(line=58, offs=19)
*/
ATSINSmove(tmp32, PMVtmpltcst(rpt1<S2Evar(i(7685))><S2Evar(o(7686))>)(arg0)) ;

/*
emit_instr: loc0 = /vagrant/parcc.dats: 1194(line=58, offs=8) -- 1205(line=58, offs=19)
*/
ATSINSmove(tmp31, PMVtmpltcst(opt<S2Evar(i(7685))><S2Eapp(S2Ecst(list); S2EVar(4196->S2Evar(o(7686))))>)(tmp32)) ;

/*
emit_instr: loc0 = /vagrant/parcc.dats: 1188(line=58, offs=2) -- 1303(line=62, offs=3)
*/
ATSINSmove(tmpret30, PMVtmpltcst(bind<S2Evar(i(7685))><S2Eapp(S2Ecst(maybe); S2EVar(4194->S2Eapp(S2Ecst(list); S2EVar(4196->S2Evar(o(7686)))))), S2Eapp(S2Ecst(list); S2Evar(o(7686)))>)(tmp31, ATSPMVcfunlab(-1, __patsfun_15__15, ()))) ;

/* funbodyinstrlst(end) */
ATSreturn(tmpret30) ;
} /* end of [_057_vagrant_057_parcc_056_sats__rpt0__14] */
#endif // end of [TEMPLATE]

#if(0)
/*
/vagrant/parcc.dats: 1208(line=58, offs=22) -- 1299(line=61, offs=35)
*/
/*
local: 
global: __patsfun_15$0(level=1)
local: 
global: 
*/
ATSstaticdec()
atstype_cloptr
__patsfun_15__15(atstype_boxed arg0)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret33, atstype_cloptr) ;
ATStmpdec(tmp34, atstype_boxed) ;
ATStmpdec(tmp35, atstype_boxed) ;
/* tmpvardeclst(end) */
/* funbodyinstrlst(beg) */
/*
emit_instr: loc0 = /vagrant/parcc.dats: 1208(line=58, offs=22) -- 1299(line=61, offs=35)
*/
ATSINSlab(__patsflab___patsfun_15):
/*
emit_instr: loc0 = /vagrant/parcc.dats: 1223(line=59, offs=3) -- 1299(line=61, offs=35)
*/
ATScaseofbeg()
/*
** ibranchlst-beg
*/
ATSbranchbeg() ;
/*
emit_instr: loc0 = /vagrant/parcc.dats: 1240(line=60, offs=5) -- 1247(line=60, offs=12)
*/
__atstmplab12:
/*
emit_instr: loc0 = /vagrant/parcc.dats: 1213(line=58, offs=27) -- 1214(line=58, offs=28)
*/
if (ATSCKptrisnull(arg0)) { ATSgoto(__atstmplab15) ; }
/*
emit_instr: loc0 = /vagrant/parcc.dats: 1247(line=60, offs=12) -- 1247(line=60, offs=12)
*/
__atstmplab13:
/*
emit_instr: loc0 = /vagrant/parcc.dats: 1246(line=60, offs=11) -- 1247(line=60, offs=12)
*/
ATSINSmove(tmp34, ATSSELcon(arg0, postiats_tysum_10, atslab__0)) ;
/*
emit_instr: loc0 = : 0(line=0, offs=0) -- 0(line=0, offs=0)
*/
/*
ibranch-mbody:
*/
/*
emit_instr: loc0 = /vagrant/parcc.dats: 1252(line=60, offs=17) -- 1262(line=60, offs=27)
*/
ATSINSmove(tmpret33, PMVtmpltcst(succeed<S2Evar(i(7685))><S2Eapp(S2Ecst(list); S2Evar(o(7686)))>)(tmp34)) ;

ATSbranchend() ;

ATSbranchbeg() ;
/*
emit_instr: loc0 = /vagrant/parcc.dats: 1269(line=61, offs=5) -- 1279(line=61, offs=15)
*/
__atstmplab14:
/*
emit_instr: loc0 = /vagrant/parcc.dats: 1213(line=58, offs=27) -- 1214(line=58, offs=28)
*/
#if(0)
if (ATSCKptriscons(arg0)) { ATSINSdeadcode_fail() ; }
#endif
/*
emit_instr: loc0 = /vagrant/parcc.dats: 1279(line=61, offs=15) -- 1279(line=61, offs=15)
*/
__atstmplab15:
/*
emit_instr: loc0 = : 0(line=0, offs=0) -- 0(line=0, offs=0)
*/
/*
ibranch-mbody:
*/
/*
emit_instr: loc0 = /vagrant/parcc.dats: 1292(line=61, offs=28) -- 1298(line=61, offs=34)
*/

ATSINSmove_con0(tmp35, 0) ;

/*
emit_instr: loc0 = /vagrant/parcc.dats: 1283(line=61, offs=19) -- 1298(line=61, offs=34)
*/
ATSINSmove(tmpret33, PMVtmpltcst(succeed<S2Evar(i(7685))><S2Eapp(S2Ecst(list); S2Evar(o(7686)))>)(tmp35)) ;

ATSbranchend() ;

/*
** ibranchlst-end
*/
ATScaseofend()

/* funbodyinstrlst(end) */
ATSreturn(tmpret33) ;
} /* end of [__patsfun_15__15] */
#endif // end of [TEMPLATE]

#if(0)
/*
/vagrant/parcc.dats: 1331(line=64, offs=25) -- 1344(line=64, offs=38)
*/
/*
local: 
global: apply$16$0(level=0)
local: 
global: 
*/
ATSglobaldec()
/*
imparg = i(7689), o(7690)
tmparg = S2Evar(i(7689)); S2Evar(o(7690))
tmpsub = None()
*/
atstype_boxed
_057_vagrant_057_parcc_056_sats__apply__16(atstype_cloptr arg0, atstyvar_type(i) arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret36, atstype_boxed) ;
/* tmpvardeclst(end) */
/* funbodyinstrlst(beg) */
/*
emit_instr: loc0 = /vagrant/parcc.dats: 1325(line=64, offs=19) -- 1345(line=64, offs=39)
*/
ATSINSlab(__patsflab_apply):
/*
emit_instr: loc0 = /vagrant/parcc.dats: 1340(line=64, offs=34) -- 1344(line=64, offs=38)
*/
ATSINSmove(tmpret36, ATSfunclo_clo(arg0, (atstype_cloptr, atstyvar_type(i)), atstype_boxed)(arg0, arg1)) ;

/* funbodyinstrlst(end) */
ATSreturn(tmpret36) ;
} /* end of [_057_vagrant_057_parcc_056_sats__apply__16] */
#endif // end of [TEMPLATE]

#if(0)
/*
/vagrant/parcc.dats: 1376(line=66, offs=28) -- 1527(line=70, offs=40)
*/
/*
local: 
global: bind$17$0(level=0)
local: 
global: 
*/
ATSglobaldec()
/*
imparg = i(7691), o1(7692), o2(7693)
tmparg = S2Evar(i(7691)); S2Evar(o1(7692)), S2Evar(o2(7693))
tmpsub = None()
*/
atstype_cloptr
_057_vagrant_057_parcc_056_sats__bind__17(atstype_cloptr arg0, atstype_cloptr arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret37, atstype_funptr) ;
/* tmpvardeclst(end) */
/* funbodyinstrlst(beg) */
/*
emit_instr: loc0 = /vagrant/parcc.dats: 1371(line=66, offs=23) -- 1527(line=70, offs=40)
*/
ATSINSlab(__patsflab_bind):
/*
emit_instr: loc0 = /vagrant/parcc.dats: 1388(line=67, offs=2) -- 1527(line=70, offs=40)
*/
ATSINSmove(tmpret37, ATSPMVcfunlab(-1, __patsfun_18__18, (arg0, arg1))) ;
/* funbodyinstrlst(end) */
ATSreturn(tmpret37) ;
} /* end of [_057_vagrant_057_parcc_056_sats__bind__17] */
#endif // end of [TEMPLATE]

#if(0)
/*
/vagrant/parcc.dats: 1388(line=67, offs=2) -- 1527(line=70, offs=40)
*/
/*
local: 
global: __patsfun_18$0(level=1)
local: p$3518(1)(HSEfun(HSEtyvar(i(7691)); HSEtybox())), f$3519(1)(HSEfun(HSEtyvar(o1(7692)); HSEtybox()))
global: p$3518(1)(HSEfun(HSEtyvar(i(7691)); HSEtybox())), f$3519(1)(HSEfun(HSEtyvar(o1(7692)); HSEtybox()))
*/
ATSstaticdec()
atstype_boxed
__patsfun_18__18(atstype_funptr env0, atstype_funptr env1, atstyvar_type(i) arg0)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret38, atstype_boxed) ;
ATStmpdec(tmp39, atstype_boxed) ;
ATStmpdec(tmp40, atstyvar_type(o1)) ;
ATStmpdec(tmp41, atstyvar_type(i)) ;
ATStmpdec(tmp42, atstyvar_type(i)) ;
ATStmpdec(tmp43, atstype_cloptr) ;
/* tmpvardeclst(end) */
/* funbodyinstrlst(beg) */
/*
emit_instr: loc0 = /vagrant/parcc.dats: 1388(line=67, offs=2) -- 1527(line=70, offs=40)
*/
ATSINSlab(__patsflab___patsfun_18):
/*
emit_instr: loc0 = /vagrant/parcc.dats: 1413(line=68, offs=9) -- 1429(line=68, offs=25)
*/
ATSINSmove(tmp39, PMVtmpltcst(apply<S2Evar(i(7691))><S2Evar(o1(7692))>)(env0, arg0)) ;

/*
emit_instr: loc0 = /vagrant/parcc.dats: 1407(line=68, offs=3) -- 1527(line=70, offs=40)
*/
ATScaseofbeg()
/*
** ibranchlst-beg
*/
ATSbranchbeg() ;
/*
emit_instr: loc0 = /vagrant/parcc.dats: 1440(line=69, offs=6) -- 1460(line=69, offs=26)
*/
__atstmplab16:
/*
emit_instr: loc0 = /vagrant/parcc.dats: 1413(line=68, offs=9) -- 1429(line=68, offs=25)
*/
ATSifnot(ATSPATCKcon1(tmp39, 0)) { ATSgoto(__atstmplab19) ; }
/*
emit_instr: loc0 = /vagrant/parcc.dats: 1460(line=69, offs=26) -- 1460(line=69, offs=26)
*/
__atstmplab17:
/*
emit_instr: loc0 = /vagrant/parcc.dats: 1449(line=69, offs=15) -- 1452(line=69, offs=18)
*/
ATSINSmove(tmp40, ATSSELcon(tmp39, postiats_tysum_11, atslab__0)) ;
/*
emit_instr: loc0 = /vagrant/parcc.dats: 1454(line=69, offs=20) -- 1459(line=69, offs=25)
*/
ATSINSmove(tmp41, ATSSELcon(tmp39, postiats_tysum_11, atslab__1)) ;
/*
emit_instr: loc0 = : 0(line=0, offs=0) -- 0(line=0, offs=0)
*/
/*
ibranch-mbody:
*/
/*
emit_instr: loc0 = /vagrant/parcc.dats: 1471(line=69, offs=37) -- 1477(line=69, offs=43)
*/
ATSINSmove(tmp43, ATSfunclo_clo(env1, (atstype_cloptr, atstyvar_type(o1)), atstype_cloptr)(env1, tmp40)) ;

/*
emit_instr: loc0 = /vagrant/parcc.dats: 1464(line=69, offs=30) -- 1486(line=69, offs=52)
*/
ATSINSmove(tmpret38, PMVtmpltcst(apply<S2Evar(i(7691))><S2Evar(o2(7693))>)(tmp43, tmp41)) ;

ATSbranchend() ;

ATSbranchbeg() ;
/*
emit_instr: loc0 = /vagrant/parcc.dats: 1493(line=70, offs=6) -- 1507(line=70, offs=20)
*/
__atstmplab18:
/*
emit_instr: loc0 = /vagrant/parcc.dats: 1413(line=68, offs=9) -- 1429(line=68, offs=25)
*/
#if(0)
ATSifnot(ATSPATCKcon1(tmp39, 1)) { ATSINSdeadcode_fail() ; }
#endif
/*
emit_instr: loc0 = /vagrant/parcc.dats: 1507(line=70, offs=20) -- 1507(line=70, offs=20)
*/
__atstmplab19:
/*
emit_instr: loc0 = /vagrant/parcc.dats: 1502(line=70, offs=15) -- 1507(line=70, offs=20)
*/
ATSINSmove(tmp42, ATSSELcon(tmp39, postiats_tysum_12, atslab__0)) ;
/*
emit_instr: loc0 = : 0(line=0, offs=0) -- 0(line=0, offs=0)
*/
/*
ibranch-mbody:
*/
/*
emit_instr: loc0 = /vagrant/parcc.dats: 1512(line=70, offs=25) -- 1526(line=70, offs=39)
*/

ATSINSmove_con1(tmpret38, postiats_tysum_12) ;
#if(1)
ATSINSstore_con_tag(tmpret38, 1) ;
#endif
ATSINSstore_con_ofs(tmpret38, postiats_tysum_12, atslab__0, tmp42) ;

ATSbranchend() ;

/*
** ibranchlst-end
*/
ATScaseofend()

/* funbodyinstrlst(end) */
ATSreturn(tmpret38) ;
} /* end of [__patsfun_18__18] */
#endif // end of [TEMPLATE]

/*
/vagrant/parcc.dats: 1552(line=73, offs=20) -- 1801(line=83, offs=6)
*/
/*
local: 
global: lit_char$19$0(level=0)
local: 
global: 
*/
ATSglobaldec()
atstype_cloptr
_057_vagrant_057_parcc_056_sats__lit_char(atstkind_t0ype(atstype_char) arg0)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret44, atstype_funptr) ;
/* tmpvardeclst(end) */
/* funbodyinstrlst(beg) */
/*
emit_instr: loc0 = /vagrant/parcc.dats: 1543(line=73, offs=11) -- 1801(line=83, offs=6)
*/
ATSINSlab(__patsflab_lit_char):
/*
emit_instr: loc0 = /vagrant/parcc.dats: 1565(line=74, offs=2) -- 1801(line=83, offs=6)
*/
ATSINSmove(tmpret44, ATSPMVcfunlab(-1, __patsfun_20, (arg0))) ;
/* funbodyinstrlst(end) */
ATSreturn(tmpret44) ;
} /* end of [_057_vagrant_057_parcc_056_sats__lit_char] */

/*
/vagrant/parcc.dats: 1565(line=74, offs=2) -- 1801(line=83, offs=6)
*/
/*
local: 
global: __patsfun_20$0(level=1)
local: match$3524(1)(HSEapp(HSEcst(atstkind_t0ype); HSEs2exp(S2Eextkind(atstype_char))))
global: match$3524(1)(HSEapp(HSEcst(atstkind_t0ype); HSEs2exp(S2Eextkind(atstype_char))))
*/
ATSstaticdec()
atstype_boxed
__patsfun_20(atstkind_t0ype(atstype_char) env0, atstkind_type(atstype_ptrk) arg0)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret45, atstype_boxed) ;
ATStmpdec(tmp46, atstype_boxed) ;
ATStmpdec(tmp47, atstype_boxed) ;
ATStmpdec(tmp48, atstkind_type(atstype_ptrk)) ;
ATStmpdec(tmp49, atstkind_t0ype(atstype_char)) ;
ATStmpdec(tmp50, atstype_boxed) ;
ATStmpdec(tmp51, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp52, atstype_boxed) ;
ATStmpdec(tmp53, atstkind_type(atstype_ptrk)) ;
/* tmpvardeclst(end) */
/* funbodyinstrlst(beg) */
/*
emit_instr: loc0 = /vagrant/parcc.dats: 1565(line=74, offs=2) -- 1801(line=83, offs=6)
*/
ATSINSlab(__patsflab___patsfun_20):
/*
emit_instr: loc0 = /vagrant/parcc.dats: 1587(line=75, offs=9) -- 1590(line=75, offs=12)
*/
ATSINSmove_lazyeval(tmp46, atstype_boxed, arg0) ;
/*
emit_instr: loc0 = /vagrant/parcc.dats: 1581(line=75, offs=3) -- 1801(line=83, offs=6)
*/
ATScaseofbeg()
/*
** ibranchlst-beg
*/
ATSbranchbeg() ;
/*
emit_instr: loc0 = /vagrant/parcc.dats: 1599(line=76, offs=5) -- 1609(line=76, offs=15)
*/
__atstmplab20:
/*
emit_instr: loc0 = /vagrant/parcc.dats: 1587(line=75, offs=9) -- 1590(line=75, offs=12)
*/
if (ATSCKptriscons(tmp46)) { ATSgoto(__atstmplab23) ; }
/*
emit_instr: loc0 = /vagrant/parcc.dats: 1609(line=76, offs=15) -- 1609(line=76, offs=15)
*/
__atstmplab21:
/*
emit_instr: loc0 = : 0(line=0, offs=0) -- 0(line=0, offs=0)
*/
/*
ibranch-mbody:
*/
/*
emit_instr: loc0 = /vagrant/parcc.dats: 1613(line=76, offs=19) -- 1624(line=76, offs=30)
*/

ATSINSmove_con1(tmpret45, postiats_tysum_13) ;
#if(1)
ATSINSstore_con_tag(tmpret45, 1) ;
#endif
ATSINSstore_con_ofs(tmpret45, postiats_tysum_13, atslab__0, arg0) ;

ATSbranchend() ;

ATSbranchbeg() ;
/*
emit_instr: loc0 = /vagrant/parcc.dats: 1631(line=77, offs=5) -- 1649(line=77, offs=23)
*/
__atstmplab22:
/*
emit_instr: loc0 = /vagrant/parcc.dats: 1587(line=75, offs=9) -- 1590(line=75, offs=12)
*/
#if(0)
if (ATSCKptrisnull(tmp46)) { ATSINSdeadcode_fail() ; }
#endif
/*
emit_instr: loc0 = /vagrant/parcc.dats: 1649(line=77, offs=23) -- 1649(line=77, offs=23)
*/
__atstmplab23:
/*
emit_instr: loc0 = /vagrant/parcc.dats: 1641(line=77, offs=15) -- 1642(line=77, offs=16)
*/
ATSINSmove(tmp47, ATSSELcon(tmp46, postiats_tysum_14, atslab__0)) ;
/*
emit_instr: loc0 = /vagrant/parcc.dats: 1644(line=77, offs=18) -- 1648(line=77, offs=22)
*/
ATSINSmove(tmp48, ATSSELcon(tmp46, postiats_tysum_14, atslab__1)) ;
/*
emit_instr: loc0 = : 0(line=0, offs=0) -- 0(line=0, offs=0)
*/
/*
ibranch-mbody:
*/
/*
emit_instr: loc0 = /vagrant/parcc.dats: 1653(line=77, offs=27) -- 1801(line=83, offs=6)
*/
/*
letpush(beg)
*/
/*
emit_instr: loc0 = /vagrant/parcc.dats: 1665(line=78, offs=8) -- 1678(line=78, offs=21)
*/

/*
emit_instr: loc0 = /vagrant/parcc.dats: 1671(line=78, offs=14) -- 1672(line=78, offs=15)
*/
ATSINSmove(tmp49, ATSSELcon(tmp47, postiats_tysum_15, atslab__0)) ;
/*
emit_instr: loc0 = /vagrant/parcc.dats: 1674(line=78, offs=17) -- 1677(line=78, offs=20)
*/
ATSINSmove(tmp50, ATSSELcon(tmp47, postiats_tysum_15, atslab__1)) ;
/*
letpush(end)
*/

/*
emit_instr: loc0 = /vagrant/parcc.dats: 1698(line=80, offs=7) -- 1707(line=80, offs=16)
*/
ATSINSmove(tmp51, atspre_eq_char0_char0(tmp49, env0)) ;

/*
emit_instr: loc0 = /vagrant/parcc.dats: 1695(line=80, offs=4) -- 1794(line=82, offs=46)
*/
ATSif(
tmp51
) ATSthen() {
/*
emit_instr: loc0 = /vagrant/parcc.dats: 1726(line=81, offs=18) -- 1740(line=81, offs=32)
*/

ATSINSmove_con1(tmp52, postiats_tysum_16) ;
#if(1)
ATSINSstore_con_tag(tmp52, 4) ;
#endif
ATSINSstore_con_ofs(tmp52, postiats_tysum_16, atslab__0, tmp49) ;
ATSINSstore_con_ofs(tmp52, postiats_tysum_16, atslab__1, tmp50) ;

/*
emit_instr: loc0 = /vagrant/parcc.dats: 1717(line=81, offs=9) -- 1747(line=81, offs=39)
*/

ATSINSmove_con1(tmpret45, postiats_tysum_17) ;
#if(1)
ATSINSstore_con_tag(tmpret45, 0) ;
#endif
ATSINSstore_con_ofs(tmpret45, postiats_tysum_17, atslab__0, tmp52) ;
ATSINSstore_con_ofs(tmpret45, postiats_tysum_17, atslab__1, tmp48) ;

} ATSelse() {
/*
emit_instr: loc0 = /vagrant/parcc.dats: 1766(line=82, offs=18) -- 1793(line=82, offs=45)
*/
ATSINSmove_delay(tmp53, atstype_boxed, ATSPMVcfunlab(-1, __patsfun_21, (tmp47, tmp48))) ;
/*
emit_instr: loc0 = /vagrant/parcc.dats: 1757(line=82, offs=9) -- 1793(line=82, offs=45)
*/

ATSINSmove_con1(tmpret45, postiats_tysum_13) ;
#if(1)
ATSINSstore_con_tag(tmpret45, 1) ;
#endif
ATSINSstore_con_ofs(tmpret45, postiats_tysum_13, atslab__0, tmp53) ;

} /* ATSendif */
/*
emit_instr: loc0 = /vagrant/parcc.dats: 1653(line=77, offs=27) -- 1801(line=83, offs=6)
*/
/*
INSletpop()
*/
ATSbranchend() ;

/*
** ibranchlst-end
*/
ATScaseofend()

/* funbodyinstrlst(end) */
ATSreturn(tmpret45) ;
} /* end of [__patsfun_20] */

/*
/vagrant/parcc.dats: 1766(line=82, offs=18) -- 1793(line=82, offs=45)
*/
/*
local: 
global: __patsfun_21$0(level=2)
local: p$3526(2)(HSEtybox()), rest$3527(2)(HSEapp(HSEcst(atstkind_type); HSEs2exp(S2Eextkind(atstype_ptrk))))
global: p$3526(2)(HSEtybox()), rest$3527(2)(HSEapp(HSEcst(atstkind_type); HSEs2exp(S2Eextkind(atstype_ptrk))))
*/
ATSstaticdec()
atstype_boxed
__patsfun_21(atstype_boxed env0, atstkind_type(atstype_ptrk) env1)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret54, atstype_boxed) ;
/* tmpvardeclst(end) */
/* funbodyinstrlst(beg) */
/*
emit_instr: loc0 = /vagrant/parcc.dats: 1766(line=82, offs=18) -- 1793(line=82, offs=45)
*/
ATSINSlab(__patsflab___patsfun_21):
/*
emit_instr: loc0 = /vagrant/parcc.dats: 1774(line=82, offs=26) -- 1792(line=82, offs=44)
*/

ATSINSmove_con1(tmpret54, postiats_tysum_14) ;
#if(0)
ATSINSstore_con_tag(tmpret54, 0) ;
#endif
ATSINSstore_con_ofs(tmpret54, postiats_tysum_14, atslab__0, env0) ;
ATSINSstore_con_ofs(tmpret54, postiats_tysum_14, atslab__1, env1) ;

/* funbodyinstrlst(end) */
ATSreturn(tmpret54) ;
} /* end of [__patsfun_21] */

#if(0)
/*
** for initialization(dynloading)
*/
atsvoid_t0ype
_057_vagrant_057_parcc_056_dats__dynload()
{
ATSdynload0(
_057_vagrant_057_parcc_056_dats__dynloadflag
) ;
ATSif(
ATSCKiseqz(
_057_vagrant_057_parcc_056_dats__dynloadflag
)
) ATSthen() {
ATSdynloadset(_057_vagrant_057_parcc_056_dats__dynloadflag) ;
/*
dynexnlst-initize(beg)
*/
/*
dynexnlst-initize(end)
*/
} /* ATSendif */
ATSreturn_void() ;
} /* end of [*_dynload] */
#endif // end of [#if(0)]
