/*
**
** The C code is generated by ATS/Postiats
** The compilation time is: 2014-2-11: 22h:24m
**
*/

/*
** include runtime header files
*/
#ifndef _ATS_CCOMP_HEADER_NONE
#include "pats_ccomp_config.h"
#include "pats_ccomp_basics.h"
#include "pats_ccomp_typedefs.h"
#include "pats_ccomp_instrset.h"
#include "pats_ccomp_memalloc.h"
#ifndef _ATS_EXCEPTION_NONE
#include "pats_ccomp_memalloca.h"
#include "pats_ccomp_exception.h"
#endif // end of [_ATS_EXCEPTION_NONE]
#endif /* _ATS_CCOMP_HEADER_NONE */


/*
** include prelude cats files
*/
#ifndef _ATS_CCOMP_PRELUDE_NONE
//
#include "prelude/CATS/basics.cats"
#include "prelude/CATS/integer.cats"
#include "prelude/CATS/pointer.cats"
#include "prelude/CATS/bool.cats"
#include "prelude/CATS/char.cats"
#include "prelude/CATS/integer_ptr.cats"
#include "prelude/CATS/integer_fixed.cats"
#include "prelude/CATS/float.cats"
#include "prelude/CATS/memory.cats"
#include "prelude/CATS/string.cats"
#include "prelude/CATS/strptr.cats"
//
#include "prelude/CATS/filebas.cats"
//
#include "prelude/CATS/list.cats"
#include "prelude/CATS/option.cats"
#include "prelude/CATS/array.cats"
#include "prelude/CATS/arrayptr.cats"
#include "prelude/CATS/arrayref.cats"
#include "prelude/CATS/matrix.cats"
#include "prelude/CATS/matrixptr.cats"
//
#endif /* _ATS_CCOMP_PRELUDE_NONE */

/*
staload-prologues(beg)
*/
/*
/cygdrive/c/GitHub/ats-parcc/prelude.sats: 1(line=1, offs=1) -- 23(line=1, offs=23)
*/
/*
/cygdrive/c/GitHub/ats-parcc/prelude.sats: 25(line=2, offs=1) -- 48(line=2, offs=24)
*/
/*
/cygdrive/c/GitHub/ats-parcc/prelude.sats: 50(line=3, offs=1) -- 71(line=3, offs=22)
*/
/*
/cygdrive/c/GitHub/ats-parcc/prelude.sats: 73(line=4, offs=1) -- 93(line=4, offs=21)
*/
/*
/cygdrive/c/GitHub/ats-parcc/map.sats: 1(line=1, offs=1) -- 21(line=1, offs=21)
*/
/*
/cygdrive/c/GitHub/ats-parcc/prelude.sats: 95(line=5, offs=1) -- 118(line=5, offs=24)
*/
/*
/cygdrive/c/GitHub/ats-parcc/prelude.sats: 120(line=6, offs=1) -- 141(line=6, offs=22)
*/
/*
/cygdrive/c/GitHub/ats-parcc/prelude.sats: 143(line=7, offs=1) -- 165(line=7, offs=23)
*/
/*
/cygdrive/c/GitHub/ats-parcc/prelude.sats: 167(line=8, offs=1) -- 188(line=8, offs=22)
*/
/*
/cygdrive/c/GitHub/ats-parcc/parcc.sats: 1(line=1, offs=1) -- 24(line=1, offs=24)
*/
/*
/cygdrive/c/GitHub/ats-parcc/parcc.sats: 26(line=2, offs=1) -- 47(line=2, offs=22)
*/
/*
/cygdrive/c/GitHub/ats-parcc/parcc.sats: 49(line=3, offs=1) -- 70(line=3, offs=22)
*/
/*
staload-prologues(end)
*/
/*
typedefs-for-tyrecs-and-tysums(beg)
*/
typedef
struct {
#if(1)
int contag ;
#endif
atstype_boxed atslab__0; 
stream(atstype_boxed) atslab__1; 
} postiats_tysum_0 ;
typedef
struct {
#if(1)
int contag ;
#endif
stream(atstype_boxed) atslab__0; 
} postiats_tysum_2 ;
typedef
struct {
#if(0)
int contag ;
#endif
atstype_boxed atslab__0; 
atstype_boxed atslab__1; 
} postiats_tysum_3 ;
/*
typedefs-for-tyrecs-and-tysums(end)
*/
/*
dynconlst-declaration(beg)
*/
/*
dynconlst-declaration(end)
*/
/*
dyncstlst-declaration(beg)
*/
ATSdyncst_extfun(_057_cygdrive_057_c_057_GitHub_057_ats_055_parcc_057_stream_056_sats__head, (stream(atstype_boxed)), atstype_boxed) ;
ATSdyncst_extfun(_057_cygdrive_057_c_057_GitHub_057_ats_055_parcc_057_stream_056_sats__tail, (stream(atstype_boxed)), stream(atstype_boxed)) ;
ATSdyncst_extfun(_057_cygdrive_057_c_057_GitHub_057_ats_055_parcc_057_parcc_056_sats__apply, (atstype_cloptr, stream(atstype_boxed)), atstype_boxed) ;
ATSdyncst_extfun(_057_cygdrive_057_c_057_GitHub_057_ats_055_parcc_057_parcc_056_sats__bind, (atstype_cloptr, atstype_cloptr), atstype_cloptr) ;
ATSdyncst_extfun(_057_cygdrive_057_c_057_GitHub_057_ats_055_parcc_057_parcc_056_sats__succeed, (atstype_boxed), atstype_cloptr) ;
/*
dyncstlst-declaration(end)
*/
/*
dynvalist-implementation(beg)
*/
/*
dynvalist-implementation(end)
*/
/*
exnconlst-declaration(beg)
*/
#ifndef _ATS_EXCEPTION_NONE
extern void the_atsexncon_initize (atstype_exncon *d2c, char *exnmsg) ;
#endif // end of [_ATS_EXCEPTION_NONE]
/*
exnconlst-declaration(end)
*/
/*
assumelst-declaration(beg)
*/
/*
/cygdrive/c/GitHub/ats-parcc/parcc.dats: 169(line=8, offs=1) -- 231(line=8, offs=63)
*/
ATSassume(_057_cygdrive_057_c_057_GitHub_057_ats_055_parcc_057_parcc_056_sats__parser) ;
/*
assumelst-declaration(end)
*/
/*
extypelst-declaration(beg)
*/
/*
extypelst-declaration(end)
*/
#if(0)
ATSglobaldec()
atstype_cloptr
_057_cygdrive_057_c_057_GitHub_057_ats_055_parcc_057_parcc_056_sats__succeed(atstype_boxed) ;
#endif // end of [QUALIFIED]

ATSstaticdec()
atstype_boxed
__patsfun_1(atstype_boxed, stream(atstype_boxed)) ;

#if(0)
ATSglobaldec()
atstype_cloptr
_057_cygdrive_057_c_057_GitHub_057_ats_055_parcc_057_parcc_056_sats__literal(atstkind_type(atstype_ptrk)) ;
#endif // end of [QUALIFIED]

ATSstaticdec()
atstype_boxed
__patsfun_3(atstkind_type(atstype_ptrk), stream(atstype_boxed)) ;

#if(0)
ATSglobaldec()
atstype_cloptr
_057_cygdrive_057_c_057_GitHub_057_ats_055_parcc_057_parcc_056_sats__alt(atstype_cloptr, atstype_cloptr) ;
#endif // end of [QUALIFIED]

ATSstaticdec()
atstype_boxed
__patsfun_5(atstype_funptr, atstype_funptr, stream(atstype_boxed)) ;

#if(0)
ATSglobaldec()
atstype_cloptr
_057_cygdrive_057_c_057_GitHub_057_ats_055_parcc_057_parcc_056_sats__seq(atstype_cloptr, atstype_cloptr) ;
#endif // end of [QUALIFIED]

ATSstaticdec()
atstype_cloptr
__patsfun_7(atstype_funptr, atstype_boxed) ;

ATSstaticdec()
atstype_cloptr
__patsfun_8(atstype_boxed, atstype_boxed) ;

#if(0)
ATSglobaldec()
atstype_boxed
_057_cygdrive_057_c_057_GitHub_057_ats_055_parcc_057_parcc_056_sats__apply(atstype_cloptr, stream(atstype_boxed)) ;
#endif // end of [QUALIFIED]

#if(0)
ATSglobaldec()
atstype_cloptr
_057_cygdrive_057_c_057_GitHub_057_ats_055_parcc_057_parcc_056_sats__bind(atstype_cloptr, atstype_cloptr) ;
#endif // end of [QUALIFIED]

ATSstaticdec()
atstype_boxed
__patsfun_11(atstype_funptr, atstype_funptr, stream(atstype_boxed)) ;

typedef struct
{
atstype_funptr cfun ;
atstype_boxed env0 ;
} __patsfun_1$closure_t0ype ;
ATSstaticdec()
atstype_boxed
__patsfun_1$cfun
(
__patsfun_1$closure_t0ype *p_cenv, stream(atstype_boxed) arg0
)
{
return __patsfun_1(p_cenv->env0, arg0) ;
} /* end of [cfun] */
ATSstaticdec()
atstype_cloptr
__patsfun_1$closureinit
(
__patsfun_1$closure_t0ype *p_cenv, atstype_boxed env0
)
{
p_cenv->env0 = env0 ;
p_cenv->cfun = __patsfun_1$cfun ;
return p_cenv ;
} /* end of [closureinit] */
ATSstaticdec()
atstype_cloptr
__patsfun_1$closurerize
(
atstype_boxed env0
)
{
return __patsfun_1$closureinit(ATS_MALLOC(sizeof(__patsfun_1$closure_t0ype)), env0) ;
} /* end of [closurerize] */

typedef struct
{
atstype_funptr cfun ;
atstkind_type(atstype_ptrk) env0 ;
} __patsfun_3$closure_t0ype ;
ATSstaticdec()
atstype_boxed
__patsfun_3$cfun
(
__patsfun_3$closure_t0ype *p_cenv, stream(atstype_boxed) arg0
)
{
return __patsfun_3(p_cenv->env0, arg0) ;
} /* end of [cfun] */
ATSstaticdec()
atstype_cloptr
__patsfun_3$closureinit
(
__patsfun_3$closure_t0ype *p_cenv, atstkind_type(atstype_ptrk) env0
)
{
p_cenv->env0 = env0 ;
p_cenv->cfun = __patsfun_3$cfun ;
return p_cenv ;
} /* end of [closureinit] */
ATSstaticdec()
atstype_cloptr
__patsfun_3$closurerize
(
atstkind_type(atstype_ptrk) env0
)
{
return __patsfun_3$closureinit(ATS_MALLOC(sizeof(__patsfun_3$closure_t0ype)), env0) ;
} /* end of [closurerize] */

typedef struct
{
atstype_funptr cfun ;
atstype_funptr env0 ;
atstype_funptr env1 ;
} __patsfun_5$closure_t0ype ;
ATSstaticdec()
atstype_boxed
__patsfun_5$cfun
(
__patsfun_5$closure_t0ype *p_cenv, stream(atstype_boxed) arg0
)
{
return __patsfun_5(p_cenv->env0, p_cenv->env1, arg0) ;
} /* end of [cfun] */
ATSstaticdec()
atstype_cloptr
__patsfun_5$closureinit
(
__patsfun_5$closure_t0ype *p_cenv, atstype_funptr env0, atstype_funptr env1
)
{
p_cenv->env0 = env0 ;
p_cenv->env1 = env1 ;
p_cenv->cfun = __patsfun_5$cfun ;
return p_cenv ;
} /* end of [closureinit] */
ATSstaticdec()
atstype_cloptr
__patsfun_5$closurerize
(
atstype_funptr env0, atstype_funptr env1
)
{
return __patsfun_5$closureinit(ATS_MALLOC(sizeof(__patsfun_5$closure_t0ype)), env0, env1) ;
} /* end of [closurerize] */

typedef struct
{
atstype_funptr cfun ;
atstype_funptr env0 ;
} __patsfun_7$closure_t0ype ;
ATSstaticdec()
atstype_cloptr
__patsfun_7$cfun
(
__patsfun_7$closure_t0ype *p_cenv, atstype_boxed arg0
)
{
return __patsfun_7(p_cenv->env0, arg0) ;
} /* end of [cfun] */
ATSstaticdec()
atstype_cloptr
__patsfun_7$closureinit
(
__patsfun_7$closure_t0ype *p_cenv, atstype_funptr env0
)
{
p_cenv->env0 = env0 ;
p_cenv->cfun = __patsfun_7$cfun ;
return p_cenv ;
} /* end of [closureinit] */
ATSstaticdec()
atstype_cloptr
__patsfun_7$closurerize
(
atstype_funptr env0
)
{
return __patsfun_7$closureinit(ATS_MALLOC(sizeof(__patsfun_7$closure_t0ype)), env0) ;
} /* end of [closurerize] */

typedef struct
{
atstype_funptr cfun ;
atstype_boxed env0 ;
} __patsfun_8$closure_t0ype ;
ATSstaticdec()
atstype_cloptr
__patsfun_8$cfun
(
__patsfun_8$closure_t0ype *p_cenv, atstype_boxed arg0
)
{
return __patsfun_8(p_cenv->env0, arg0) ;
} /* end of [cfun] */
ATSstaticdec()
atstype_cloptr
__patsfun_8$closureinit
(
__patsfun_8$closure_t0ype *p_cenv, atstype_boxed env0
)
{
p_cenv->env0 = env0 ;
p_cenv->cfun = __patsfun_8$cfun ;
return p_cenv ;
} /* end of [closureinit] */
ATSstaticdec()
atstype_cloptr
__patsfun_8$closurerize
(
atstype_boxed env0
)
{
return __patsfun_8$closureinit(ATS_MALLOC(sizeof(__patsfun_8$closure_t0ype)), env0) ;
} /* end of [closurerize] */

typedef struct
{
atstype_funptr cfun ;
atstype_funptr env0 ;
atstype_funptr env1 ;
} __patsfun_11$closure_t0ype ;
ATSstaticdec()
atstype_boxed
__patsfun_11$cfun
(
__patsfun_11$closure_t0ype *p_cenv, stream(atstype_boxed) arg0
)
{
return __patsfun_11(p_cenv->env0, p_cenv->env1, arg0) ;
} /* end of [cfun] */
ATSstaticdec()
atstype_cloptr
__patsfun_11$closureinit
(
__patsfun_11$closure_t0ype *p_cenv, atstype_funptr env0, atstype_funptr env1
)
{
p_cenv->env0 = env0 ;
p_cenv->env1 = env1 ;
p_cenv->cfun = __patsfun_11$cfun ;
return p_cenv ;
} /* end of [closureinit] */
ATSstaticdec()
atstype_cloptr
__patsfun_11$closurerize
(
atstype_funptr env0, atstype_funptr env1
)
{
return __patsfun_11$closureinit(ATS_MALLOC(sizeof(__patsfun_11$closure_t0ype)), env0, env1) ;
} /* end of [closurerize] */

/*
/cygdrive/c/GitHub/ats-parcc/parcc.dats: 282(line=14, offs=27) -- 330(line=15, offs=39)
*/
/*
local: 
global: succeed$0$0(level=0)
local: 
global: 
*/
ATSglobaldec()
atstype_cloptr
_057_cygdrive_057_c_057_GitHub_057_ats_055_parcc_057_parcc_056_sats__succeed(atstype_boxed arg0)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret0, atstype_funptr) ;
/* tmpvardeclst(end) */
/* funbodyinstrlst(beg) */
/*
emit_instr: loc0 = /cygdrive/c/GitHub/ats-parcc/parcc.dats: 266(line=14, offs=11) -- 330(line=15, offs=39)
*/
__patsflab_succeed:
/*
emit_instr: loc0 = /cygdrive/c/GitHub/ats-parcc/parcc.dats: 293(line=15, offs=2) -- 330(line=15, offs=39)
*/
ATSINSmove(tmpret0, ATSPMVcfunlab(-1, __patsfun_1, (arg0))) ;
/* funbodyinstrlst(end) */
ATSreturn(tmpret0) ;
} /* end of [_057_cygdrive_057_c_057_GitHub_057_ats_055_parcc_057_parcc_056_sats__succeed] */

/*
/cygdrive/c/GitHub/ats-parcc/parcc.dats: 293(line=15, offs=2) -- 330(line=15, offs=39)
*/
/*
local: 
global: __patsfun_1$0(level=1)
local: ret$63(1)(HSEtyvar(o(3723)))
global: ret$63(1)(HSEtyvar(o(3723)))
*/
ATSstaticdec()
atstype_boxed
__patsfun_1(atstype_boxed env0, stream(atstype_boxed) arg0)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret1, atstype_boxed) ;
/* tmpvardeclst(end) */
/* funbodyinstrlst(beg) */
/*
emit_instr: loc0 = /cygdrive/c/GitHub/ats-parcc/parcc.dats: 293(line=15, offs=2) -- 330(line=15, offs=39)
*/
__patsflab___patsfun_1:
/*
emit_instr: loc0 = /cygdrive/c/GitHub/ats-parcc/parcc.dats: 313(line=15, offs=22) -- 330(line=15, offs=39)
*/

ATSINSmove_con1(tmpret1, postiats_tysum_0) ;
#if(1)
ATSINSstore_con_tag(tmpret1, 0) ;
#endif
ATSINSstore_con_ofs(tmpret1, postiats_tysum_0, atslab__0, env0) ;
ATSINSstore_con_ofs(tmpret1, postiats_tysum_0, atslab__1, arg0) ;

/* funbodyinstrlst(end) */
ATSreturn(tmpret1) ;
} /* end of [__patsfun_1] */

/*
/cygdrive/c/GitHub/ats-parcc/parcc.dats: 356(line=17, offs=23) -- 496(line=22, offs=16)
*/
/*
local: 
global: literal$2$0(level=0)
local: 
global: 
*/
ATSglobaldec()
atstype_cloptr
_057_cygdrive_057_c_057_GitHub_057_ats_055_parcc_057_parcc_056_sats__literal(atstkind_type(atstype_ptrk) arg0)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret2, atstype_funptr) ;
/* tmpvardeclst(end) */
/* funbodyinstrlst(beg) */
/*
emit_instr: loc0 = /cygdrive/c/GitHub/ats-parcc/parcc.dats: 344(line=17, offs=11) -- 496(line=22, offs=16)
*/
__patsflab_literal:
/*
emit_instr: loc0 = /cygdrive/c/GitHub/ats-parcc/parcc.dats: 369(line=18, offs=2) -- 496(line=22, offs=16)
*/
ATSINSmove(tmpret2, ATSPMVcfunlab(-1, __patsfun_3, (arg0))) ;
/* funbodyinstrlst(end) */
ATSreturn(tmpret2) ;
} /* end of [_057_cygdrive_057_c_057_GitHub_057_ats_055_parcc_057_parcc_056_sats__literal] */

/*
/cygdrive/c/GitHub/ats-parcc/parcc.dats: 369(line=18, offs=2) -- 496(line=22, offs=16)
*/
/*
local: 
global: __patsfun_3$0(level=1)
local: match$65(1)(HSEapp(HSEcst(atstkind_type); HSEs2exp(S2Eextkind(atstype_ptrk))))
global: match$65(1)(HSEapp(HSEcst(atstkind_type); HSEs2exp(S2Eextkind(atstype_ptrk))))
*/
ATSstaticdec()
atstype_boxed
__patsfun_3(atstkind_type(atstype_ptrk) env0, stream(atstype_boxed) arg0)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret3, atstype_boxed) ;
ATStmpdec(tmp4, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp5, HITundef(HSEs2exp(S2EVar(3)))) ;
ATStmpdec(tmp6, atstype_boxed) ;
ATStmpdec(tmp7, stream(atstype_boxed)) ;
/* tmpvardeclst(end) */
/* funbodyinstrlst(beg) */
/*
emit_instr: loc0 = /cygdrive/c/GitHub/ats-parcc/parcc.dats: 369(line=18, offs=2) -- 496(line=22, offs=16)
*/
__patsflab___patsfun_3:
/*
emit_instr: loc0 = /cygdrive/c/GitHub/ats-parcc/parcc.dats: 403(line=19, offs=13) -- 415(line=19, offs=25)
*/
ATSINSmove(tmp5, _057_cygdrive_057_c_057_GitHub_057_ats_055_parcc_057_stream_056_sats__head(arg0)) ;

/*
emit_instr: loc0 = /cygdrive/c/GitHub/ats-parcc/parcc.dats: 396(line=19, offs=6) -- 424(line=19, offs=34)
*/
ATSINSmove(tmp4, PMVtmpltcstmat[0](equal_any_any<S2EVar(3), S2EVar(4)>)(tmp5, env0)) ;

/*
emit_instr: loc0 = /cygdrive/c/GitHub/ats-parcc/parcc.dats: 393(line=19, offs=3) -- 496(line=22, offs=16)
*/
ATSif(
tmp4
) ATSthen() {
/*
emit_instr: loc0 = /cygdrive/c/GitHub/ats-parcc/parcc.dats: 443(line=20, offs=13) -- 454(line=20, offs=24)
*/

ATSINSmove_con0(tmp6, 0) ;

/*
emit_instr: loc0 = /cygdrive/c/GitHub/ats-parcc/parcc.dats: 456(line=20, offs=26) -- 468(line=20, offs=38)
*/
ATSINSmove(tmp7, _057_cygdrive_057_c_057_GitHub_057_ats_055_parcc_057_stream_056_sats__tail(arg0)) ;

/*
emit_instr: loc0 = /cygdrive/c/GitHub/ats-parcc/parcc.dats: 434(line=20, offs=4) -- 470(line=20, offs=40)
*/

ATSINSmove_con1(tmpret3, postiats_tysum_0) ;
#if(1)
ATSINSstore_con_tag(tmpret3, 0) ;
#endif
ATSINSstore_con_ofs(tmpret3, postiats_tysum_0, atslab__0, tmp6) ;
ATSINSstore_con_ofs(tmpret3, postiats_tysum_0, atslab__1, tmp7) ;

} ATSelse() {
/*
emit_instr: loc0 = /cygdrive/c/GitHub/ats-parcc/parcc.dats: 484(line=22, offs=4) -- 495(line=22, offs=15)
*/

ATSINSmove_con1(tmpret3, postiats_tysum_2) ;
#if(1)
ATSINSstore_con_tag(tmpret3, 1) ;
#endif
ATSINSstore_con_ofs(tmpret3, postiats_tysum_2, atslab__0, arg0) ;

} /* ATSendif */
/* funbodyinstrlst(end) */
ATSreturn(tmpret3) ;
} /* end of [__patsfun_3] */

/*
/cygdrive/c/GitHub/ats-parcc/parcc.dats: 541(line=27, offs=23) -- 690(line=34, offs=6)
*/
/*
local: 
global: alt$4$0(level=0)
local: 
global: 
*/
ATSglobaldec()
atstype_cloptr
_057_cygdrive_057_c_057_GitHub_057_ats_055_parcc_057_parcc_056_sats__alt(atstype_cloptr arg0, atstype_cloptr arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret8, atstype_funptr) ;
/* tmpvardeclst(end) */
/* funbodyinstrlst(beg) */
/*
emit_instr: loc0 = /cygdrive/c/GitHub/ats-parcc/parcc.dats: 529(line=27, offs=11) -- 690(line=34, offs=6)
*/
__patsflab_alt:
/*
emit_instr: loc0 = /cygdrive/c/GitHub/ats-parcc/parcc.dats: 553(line=28, offs=2) -- 690(line=34, offs=6)
*/
ATSINSmove(tmpret8, ATSPMVcfunlab(-1, __patsfun_5, (arg0, arg1))) ;
/* funbodyinstrlst(end) */
ATSreturn(tmpret8) ;
} /* end of [_057_cygdrive_057_c_057_GitHub_057_ats_055_parcc_057_parcc_056_sats__alt] */

/*
/cygdrive/c/GitHub/ats-parcc/parcc.dats: 553(line=28, offs=2) -- 690(line=34, offs=6)
*/
/*
local: 
global: __patsfun_5$0(level=1)
local: a$67(1)(HSEfun(HSEapp(HSEcst(stream); HSEtyvar(i(3728))); HSEtybox())), b$68(1)(HSEfun(HSEapp(HSEcst(stream); HSEtyvar(i(3728))); HSEtybox()))
global: a$67(1)(HSEfun(HSEapp(HSEcst(stream); HSEtyvar(i(3728))); HSEtybox())), b$68(1)(HSEfun(HSEapp(HSEcst(stream); HSEtyvar(i(3728))); HSEtybox()))
*/
ATSstaticdec()
atstype_boxed
__patsfun_5(atstype_funptr env0, atstype_funptr env1, stream(atstype_boxed) arg0)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret9, atstype_boxed) ;
ATStmpdec(tmp10, atstype_boxed) ;
/* tmpvardeclst(end) */
/* funbodyinstrlst(beg) */
/*
emit_instr: loc0 = /cygdrive/c/GitHub/ats-parcc/parcc.dats: 553(line=28, offs=2) -- 690(line=34, offs=6)
*/
__patsflab___patsfun_5:
/*
emit_instr: loc0 = /cygdrive/c/GitHub/ats-parcc/parcc.dats: 576(line=29, offs=3) -- 690(line=34, offs=6)
*/
/*
letpush(beg)
*/
/*
emit_instr: loc0 = /cygdrive/c/GitHub/ats-parcc/parcc.dats: 593(line=30, offs=12) -- 605(line=30, offs=24)
*/
ATSINSmove(tmp10, _057_cygdrive_057_c_057_GitHub_057_ats_055_parcc_057_parcc_056_sats__apply(env0, arg0)) ;

/*
letpush(end)
*/

/*
emit_instr: loc0 = /cygdrive/c/GitHub/ats-parcc/parcc.dats: 612(line=31, offs=6) -- 683(line=33, offs=33)
*/
ATScaseofbeg()
/*
** ibranchlst-beg
*/
ATSbranchbeg() ;
/*
emit_instr: loc0 = /cygdrive/c/GitHub/ats-parcc/parcc.dats: 630(line=32, offs=6) -- 644(line=32, offs=20)
*/
__atstmplab0:
/*
emit_instr: loc0 = /cygdrive/c/GitHub/ats-parcc/parcc.dats: 593(line=30, offs=12) -- 605(line=30, offs=24)
*/
ATSifnot(ATSPATCKcon1(tmp10, 0)) { ATSgoto(__atstmplab3) ; }
/*
emit_instr: loc0 = /cygdrive/c/GitHub/ats-parcc/parcc.dats: 644(line=32, offs=20) -- 644(line=32, offs=20)
*/
__atstmplab1:
/*
emit_instr: loc0 = : 0(line=0, offs=0) -- 0(line=0, offs=0)
*/
/*
ibranch-mbody:
*/
/*
emit_instr: loc0 = /cygdrive/c/GitHub/ats-parcc/parcc.dats: 648(line=32, offs=24) -- 649(line=32, offs=25)
*/
ATSINSmove(tmpret9, tmp10) ;
ATSbranchend() ;

ATSbranchbeg() ;
/*
emit_instr: loc0 = /cygdrive/c/GitHub/ats-parcc/parcc.dats: 656(line=33, offs=6) -- 666(line=33, offs=16)
*/
__atstmplab2:
/*
emit_instr: loc0 = /cygdrive/c/GitHub/ats-parcc/parcc.dats: 593(line=30, offs=12) -- 605(line=30, offs=24)
*/
#if(0)
ATSifnot(ATSPATCKcon1(tmp10, 1)) { ATSINSdeadcode_fail() ; }
#endif
/*
emit_instr: loc0 = /cygdrive/c/GitHub/ats-parcc/parcc.dats: 666(line=33, offs=16) -- 666(line=33, offs=16)
*/
__atstmplab3:
/*
emit_instr: loc0 = : 0(line=0, offs=0) -- 0(line=0, offs=0)
*/
/*
ibranch-mbody:
*/
/*
emit_instr: loc0 = /cygdrive/c/GitHub/ats-parcc/parcc.dats: 671(line=33, offs=21) -- 683(line=33, offs=33)
*/
ATSINSmove(tmpret9, _057_cygdrive_057_c_057_GitHub_057_ats_055_parcc_057_parcc_056_sats__apply(env1, arg0)) ;

ATSbranchend() ;

/*
** ibranchlst-end
*/
ATScaseofend()

/*
emit_instr: loc0 = /cygdrive/c/GitHub/ats-parcc/parcc.dats: 576(line=29, offs=3) -- 690(line=34, offs=6)
*/
/*
INSletpop()
*/
/* funbodyinstrlst(end) */
ATSreturn(tmpret9) ;
} /* end of [__patsfun_5] */

/*
/cygdrive/c/GitHub/ats-parcc/parcc.dats: 720(line=36, offs=27) -- 824(line=39, offs=59)
*/
/*
local: 
global: seq$6$0(level=0)
local: 
global: 
*/
ATSglobaldec()
atstype_cloptr
_057_cygdrive_057_c_057_GitHub_057_ats_055_parcc_057_parcc_056_sats__seq(atstype_cloptr arg0, atstype_cloptr arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret11, atstype_cloptr) ;
/* tmpvardeclst(end) */
/* funbodyinstrlst(beg) */
/*
emit_instr: loc0 = /cygdrive/c/GitHub/ats-parcc/parcc.dats: 704(line=36, offs=11) -- 824(line=39, offs=59)
*/
__patsflab_seq:
/*
emit_instr: loc0 = /cygdrive/c/GitHub/ats-parcc/parcc.dats: 732(line=37, offs=2) -- 824(line=39, offs=59)
*/
ATSINSmove(tmpret11, _057_cygdrive_057_c_057_GitHub_057_ats_055_parcc_057_parcc_056_sats__bind(arg0, ATSPMVcfunlab(-1, __patsfun_7, (arg1)))) ;

/* funbodyinstrlst(end) */
ATSreturn(tmpret11) ;
} /* end of [_057_cygdrive_057_c_057_GitHub_057_ats_055_parcc_057_parcc_056_sats__seq] */

/*
/cygdrive/c/GitHub/ats-parcc/parcc.dats: 745(line=38, offs=3) -- 823(line=39, offs=58)
*/
/*
local: 
global: __patsfun_7$0(level=1)
local: b$72(1)(HSEfun(HSEapp(HSEcst(stream); HSEtyvar(i(3738))); HSEtybox()))
global: b$72(1)(HSEfun(HSEapp(HSEcst(stream); HSEtyvar(i(3738))); HSEtybox()))
*/
ATSstaticdec()
atstype_cloptr
__patsfun_7(atstype_funptr env0, atstype_boxed arg0)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret12, atstype_cloptr) ;
/* tmpvardeclst(end) */
/* funbodyinstrlst(beg) */
/*
emit_instr: loc0 = /cygdrive/c/GitHub/ats-parcc/parcc.dats: 745(line=38, offs=3) -- 823(line=39, offs=58)
*/
__patsflab___patsfun_7:
/*
emit_instr: loc0 = /cygdrive/c/GitHub/ats-parcc/parcc.dats: 769(line=39, offs=4) -- 823(line=39, offs=58)
*/
ATSINSmove(tmpret12, _057_cygdrive_057_c_057_GitHub_057_ats_055_parcc_057_parcc_056_sats__bind(env0, ATSPMVcfunlab(-1, __patsfun_8, (arg0)))) ;

/* funbodyinstrlst(end) */
ATSreturn(tmpret12) ;
} /* end of [__patsfun_7] */

/*
/cygdrive/c/GitHub/ats-parcc/parcc.dats: 778(line=39, offs=13) -- 822(line=39, offs=57)
*/
/*
local: 
global: __patsfun_8$0(level=2)
local: x$73(2)(HSEtyvar(o1(3741)))
global: x$73(2)(HSEtyvar(o1(3741)))
*/
ATSstaticdec()
atstype_cloptr
__patsfun_8(atstype_boxed env0, atstype_boxed arg0)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret13, atstype_cloptr) ;
ATStmpdec(tmp14, atstype_boxed) ;
/* tmpvardeclst(end) */
/* funbodyinstrlst(beg) */
/*
emit_instr: loc0 = /cygdrive/c/GitHub/ats-parcc/parcc.dats: 778(line=39, offs=13) -- 822(line=39, offs=57)
*/
__patsflab___patsfun_8:
/*
emit_instr: loc0 = /cygdrive/c/GitHub/ats-parcc/parcc.dats: 806(line=39, offs=41) -- 821(line=39, offs=56)
*/

ATSINSmove_con1(tmp14, postiats_tysum_3) ;
#if(0)
ATSINSstore_con_tag(tmp14, 0) ;
#endif
ATSINSstore_con_ofs(tmp14, postiats_tysum_3, atslab__0, env0) ;
ATSINSstore_con_ofs(tmp14, postiats_tysum_3, atslab__1, arg0) ;

/*
emit_instr: loc0 = /cygdrive/c/GitHub/ats-parcc/parcc.dats: 797(line=39, offs=32) -- 821(line=39, offs=56)
*/
ATSINSmove(tmpret13, _057_cygdrive_057_c_057_GitHub_057_ats_055_parcc_057_parcc_056_sats__succeed(tmp14)) ;

/* funbodyinstrlst(end) */
ATSreturn(tmpret13) ;
} /* end of [__patsfun_8] */

/*
/cygdrive/c/GitHub/ats-parcc/parcc.dats: 852(line=41, offs=25) -- 865(line=41, offs=38)
*/
/*
local: 
global: apply$9$0(level=0)
local: 
global: 
*/
ATSglobaldec()
atstype_boxed
_057_cygdrive_057_c_057_GitHub_057_ats_055_parcc_057_parcc_056_sats__apply(atstype_cloptr arg0, stream(atstype_boxed) arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret15, atstype_boxed) ;
/* tmpvardeclst(end) */
/* funbodyinstrlst(beg) */
/*
emit_instr: loc0 = /cygdrive/c/GitHub/ats-parcc/parcc.dats: 838(line=41, offs=11) -- 866(line=41, offs=39)
*/
__patsflab_apply:
/*
emit_instr: loc0 = /cygdrive/c/GitHub/ats-parcc/parcc.dats: 861(line=41, offs=34) -- 865(line=41, offs=38)
*/
ATSINSmove(tmpret15, ATSfunclo_clo(arg0, (atstype_cloptr, stream(atstype_boxed)), atstype_boxed)(arg0, arg1)) ;

/* funbodyinstrlst(end) */
ATSreturn(tmpret15) ;
} /* end of [_057_cygdrive_057_c_057_GitHub_057_ats_055_parcc_057_parcc_056_sats__apply] */

/*
/cygdrive/c/GitHub/ats-parcc/parcc.dats: 897(line=43, offs=28) -- 1038(line=47, offs=34)
*/
/*
local: 
global: bind$10$0(level=0)
local: 
global: 
*/
ATSglobaldec()
atstype_cloptr
_057_cygdrive_057_c_057_GitHub_057_ats_055_parcc_057_parcc_056_sats__bind(atstype_cloptr arg0, atstype_cloptr arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret16, atstype_funptr) ;
/* tmpvardeclst(end) */
/* funbodyinstrlst(beg) */
/*
emit_instr: loc0 = /cygdrive/c/GitHub/ats-parcc/parcc.dats: 880(line=43, offs=11) -- 1038(line=47, offs=34)
*/
__patsflab_bind:
/*
emit_instr: loc0 = /cygdrive/c/GitHub/ats-parcc/parcc.dats: 909(line=44, offs=2) -- 1038(line=47, offs=34)
*/
ATSINSmove(tmpret16, ATSPMVcfunlab(-1, __patsfun_11, (arg0, arg1))) ;
/* funbodyinstrlst(end) */
ATSreturn(tmpret16) ;
} /* end of [_057_cygdrive_057_c_057_GitHub_057_ats_055_parcc_057_parcc_056_sats__bind] */

/*
/cygdrive/c/GitHub/ats-parcc/parcc.dats: 909(line=44, offs=2) -- 1038(line=47, offs=34)
*/
/*
local: 
global: __patsfun_11$0(level=1)
local: p$77(1)(HSEfun(HSEapp(HSEcst(stream); HSEtyvar(i(3751))); HSEtybox())), f$78(1)(HSEfun(HSEtyvar(o1(3754)); HSEtybox()))
global: p$77(1)(HSEfun(HSEapp(HSEcst(stream); HSEtyvar(i(3751))); HSEtybox())), f$78(1)(HSEfun(HSEtyvar(o1(3754)); HSEtybox()))
*/
ATSstaticdec()
atstype_boxed
__patsfun_11(atstype_funptr env0, atstype_funptr env1, stream(atstype_boxed) arg0)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret17, atstype_boxed) ;
ATStmpdec(tmp18, atstype_boxed) ;
ATStmpdec(tmp19, atstype_boxed) ;
ATStmpdec(tmp20, stream(atstype_boxed)) ;
ATStmpdec(tmp21, stream(atstype_boxed)) ;
ATStmpdec(tmp22, atstype_cloptr) ;
/* tmpvardeclst(end) */
/* funbodyinstrlst(beg) */
/*
emit_instr: loc0 = /cygdrive/c/GitHub/ats-parcc/parcc.dats: 909(line=44, offs=2) -- 1038(line=47, offs=34)
*/
__patsflab___patsfun_11:
/*
emit_instr: loc0 = /cygdrive/c/GitHub/ats-parcc/parcc.dats: 939(line=45, offs=9) -- 952(line=45, offs=22)
*/
ATSINSmove(tmp18, _057_cygdrive_057_c_057_GitHub_057_ats_055_parcc_057_parcc_056_sats__apply(env0, arg0)) ;

/*
emit_instr: loc0 = /cygdrive/c/GitHub/ats-parcc/parcc.dats: 933(line=45, offs=3) -- 1038(line=47, offs=34)
*/
ATScaseofbeg()
/*
** ibranchlst-beg
*/
ATSbranchbeg() ;
/*
emit_instr: loc0 = /cygdrive/c/GitHub/ats-parcc/parcc.dats: 963(line=46, offs=6) -- 980(line=46, offs=23)
*/
__atstmplab4:
/*
emit_instr: loc0 = /cygdrive/c/GitHub/ats-parcc/parcc.dats: 939(line=45, offs=9) -- 952(line=45, offs=22)
*/
ATSifnot(ATSPATCKcon1(tmp18, 0)) { ATSgoto(__atstmplab7) ; }
/*
emit_instr: loc0 = /cygdrive/c/GitHub/ats-parcc/parcc.dats: 980(line=46, offs=23) -- 980(line=46, offs=23)
*/
__atstmplab5:
/*
emit_instr: loc0 = /cygdrive/c/GitHub/ats-parcc/parcc.dats: 972(line=46, offs=15) -- 975(line=46, offs=18)
*/
ATSINSmove(tmp19, ATSSELcon(tmp18, postiats_tysum_0, atslab__0)) ;
/*
emit_instr: loc0 = /cygdrive/c/GitHub/ats-parcc/parcc.dats: 977(line=46, offs=20) -- 979(line=46, offs=22)
*/
ATSINSmove(tmp20, ATSSELcon(tmp18, postiats_tysum_0, atslab__1)) ;
/*
emit_instr: loc0 = : 0(line=0, offs=0) -- 0(line=0, offs=0)
*/
/*
ibranch-mbody:
*/
/*
emit_instr: loc0 = /cygdrive/c/GitHub/ats-parcc/parcc.dats: 991(line=46, offs=34) -- 997(line=46, offs=40)
*/
ATSINSmove(tmp22, ATSfunclo_clo(env1, (atstype_cloptr, atstype_boxed), atstype_cloptr)(env1, tmp19)) ;

/*
emit_instr: loc0 = /cygdrive/c/GitHub/ats-parcc/parcc.dats: 984(line=46, offs=27) -- 1003(line=46, offs=46)
*/
ATSINSmove(tmpret17, _057_cygdrive_057_c_057_GitHub_057_ats_055_parcc_057_parcc_056_sats__apply(tmp22, tmp20)) ;

ATSbranchend() ;

ATSbranchbeg() ;
/*
emit_instr: loc0 = /cygdrive/c/GitHub/ats-parcc/parcc.dats: 1010(line=47, offs=6) -- 1021(line=47, offs=17)
*/
__atstmplab6:
/*
emit_instr: loc0 = /cygdrive/c/GitHub/ats-parcc/parcc.dats: 939(line=45, offs=9) -- 952(line=45, offs=22)
*/
#if(0)
ATSifnot(ATSPATCKcon1(tmp18, 1)) { ATSINSdeadcode_fail() ; }
#endif
/*
emit_instr: loc0 = /cygdrive/c/GitHub/ats-parcc/parcc.dats: 1021(line=47, offs=17) -- 1021(line=47, offs=17)
*/
__atstmplab7:
/*
emit_instr: loc0 = /cygdrive/c/GitHub/ats-parcc/parcc.dats: 1019(line=47, offs=15) -- 1021(line=47, offs=17)
*/
ATSINSmove(tmp21, ATSSELcon(tmp18, postiats_tysum_2, atslab__0)) ;
/*
emit_instr: loc0 = : 0(line=0, offs=0) -- 0(line=0, offs=0)
*/
/*
ibranch-mbody:
*/
/*
emit_instr: loc0 = /cygdrive/c/GitHub/ats-parcc/parcc.dats: 1026(line=47, offs=22) -- 1037(line=47, offs=33)
*/

ATSINSmove_con1(tmpret17, postiats_tysum_2) ;
#if(1)
ATSINSstore_con_tag(tmpret17, 1) ;
#endif
ATSINSstore_con_ofs(tmpret17, postiats_tysum_2, atslab__0, tmp21) ;

ATSbranchend() ;

/*
** ibranchlst-end
*/
ATScaseofend()

/* funbodyinstrlst(end) */
ATSreturn(tmpret17) ;
} /* end of [__patsfun_11] */

/*
** for initialization(dynloading)
*/
atsvoid_t0ype
_057_cygdrive_057_c_057_GitHub_057_ats_055_parcc_057_parcc_056_dats__dynload()
{
ATSdynload1(
_057_cygdrive_057_c_057_GitHub_057_ats_055_parcc_057_parcc_056_dats__dynloadflag
) ;
ATSif(
ATSCKiseqz(
_057_cygdrive_057_c_057_GitHub_057_ats_055_parcc_057_parcc_056_dats__dynloadflag
)
) ATSthen() {
ATSdynloadset(_057_cygdrive_057_c_057_GitHub_057_ats_055_parcc_057_parcc_056_dats__dynloadflag) ;
/*
dynexnlst-initize(beg)
*/
/*
dynexnlst-initize(end)
*/
} /* ATSendif */
ATSreturn_void() ;
} /* end of [*_dynload] */
