/*
**
** The C code is generated by ATS/Postiats
** The compilation time is: 2014-8-6: 19h: 5m
**
*/

/*
** include runtime header files
*/
#ifndef _ATS_CCOMP_HEADER_NONE
#include "pats_ccomp_config.h"
#include "pats_ccomp_basics.h"
#include "pats_ccomp_typedefs.h"
#include "pats_ccomp_instrset.h"
#include "pats_ccomp_memalloc.h"
#ifndef _ATS_CCOMP_EXCEPTION_NONE
#include "pats_ccomp_memalloca.h"
#include "pats_ccomp_exception.h"
#endif // end of [_ATS_CCOMP_EXCEPTION_NONE]
#endif /* _ATS_CCOMP_HEADER_NONE */


/*
** include prelude cats files
*/
#ifndef _ATS_CCOMP_PRELUDE_NONE
//
#include "prelude/CATS/basics.cats"
#include "prelude/CATS/integer.cats"
#include "prelude/CATS/pointer.cats"
#include "prelude/CATS/bool.cats"
#include "prelude/CATS/char.cats"
#include "prelude/CATS/integer_ptr.cats"
#include "prelude/CATS/integer_fixed.cats"
#include "prelude/CATS/float.cats"
#include "prelude/CATS/memory.cats"
#include "prelude/CATS/string.cats"
#include "prelude/CATS/strptr.cats"
//
#include "prelude/CATS/filebas.cats"
//
#include "prelude/CATS/list.cats"
#include "prelude/CATS/option.cats"
#include "prelude/CATS/array.cats"
#include "prelude/CATS/arrayptr.cats"
#include "prelude/CATS/arrayref.cats"
#include "prelude/CATS/matrix.cats"
#include "prelude/CATS/matrixptr.cats"
//
#endif /* _ATS_CCOMP_PRELUDE_NONE */
/*
** for user-supplied prelude
*/
#ifdef _ATS_CCOMP_PRELUDE_USER
//
#include _ATS_CCOMP_PRELUDE_USER
//
#endif /* _ATS_CCOMP_PRELUDE_USER */

/*
staload-prologues(beg)
*/
/*
/vagrant/stream.sats: 1(line=1, offs=1) -- 21(line=1, offs=21)
*/
/*
staload-prologues(end)
*/
/*
typedefs-for-tyrecs-and-tysums(beg)
*/
typedef
struct {
#if(0)
int contag ;
#endif
atstyvar_type(a) atslab__0; 
atstkind_type(atstype_ptrk) atslab__1; 
} postiats_tysum_0 ;
typedef
struct {
#if(0)
int contag ;
#endif
atstyvar_type(a) atslab__0; 
atstkind_type(atstype_ptrk) atslab__1; 
} postiats_tysum_1 ;
typedef
struct {
#if(0)
int contag ;
#endif
atstyvar_type(a) atslab__0; 
atstkind_type(atstype_ptrk) atslab__1; 
} postiats_tysum_2 ;
typedef
struct {
#if(0)
int contag ;
#endif
atstyvar_type(a) atslab__0; 
} postiats_tysum_3 ;
typedef
struct {
#if(0)
int contag ;
#endif
atstyvar_type(a) atslab__0; 
atstkind_type(atstype_ptrk) atslab__1; 
} postiats_tysum_4 ;
typedef
struct {
#if(0)
int contag ;
#endif
atstyvar_type(a) atslab__0; 
} postiats_tysum_5 ;
typedef
struct {
#if(0)
int contag ;
#endif
atstyvar_type(a) atslab__0; 
atstkind_type(atstype_ptrk) atslab__1; 
} postiats_tysum_6 ;
typedef
struct {
#if(0)
int contag ;
#endif
atstyvar_type(a) atslab__0; 
} postiats_tysum_7 ;
typedef
struct {
#if(0)
int contag ;
#endif
atstyvar_type(b) atslab__0; 
} postiats_tysum_8 ;
typedef
struct {
#if(0)
int contag ;
#endif
atstyvar_type(r) atslab__0; 
atstkind_type(atstype_ptrk) atslab__1; 
} postiats_tysum_9 ;
typedef
struct {
#if(0)
int contag ;
#endif
atstyvar_type(a) atslab__0; 
} postiats_tysum_10 ;
typedef
struct {
#if(0)
int contag ;
#endif
atstyvar_type(a) atslab__0; 
atstkind_type(atstype_ptrk) atslab__1; 
} postiats_tysum_11 ;
typedef
struct {
#if(0)
int contag ;
#endif
atstyvar_type(a) atslab__0; 
atstkind_type(atstype_ptrk) atslab__1; 
} postiats_tysum_12 ;
typedef
struct {
#if(0)
int contag ;
#endif
atstyvar_type(a) atslab__0; 
atstkind_type(atstype_ptrk) atslab__1; 
} postiats_tysum_13 ;
typedef
struct {
#if(0)
int contag ;
#endif
atstyvar_type(b) atslab__0; 
atstkind_type(atstype_ptrk) atslab__1; 
} postiats_tysum_14 ;
/*
typedefs-for-tyrecs-and-tysums(end)
*/
/*
dynconlst-declaration(beg)
*/
/*
dynconlst-declaration(end)
*/
/*
dyncstlst-declaration(beg)
*/
ATSdyncst_mac(atspre_fprint_string)
/*
dyncstlst-declaration(end)
*/
/*
dynvalist-implementation(beg)
*/
/*
dynvalist-implementation(end)
*/
/*
exnconlst-declaration(beg)
*/
#ifndef _ATS_CCOMP_EXCEPTION_NONE
extern void the_atsexncon_initize (atstype_exncon *d2c, char *exnmsg) ;
#endif // end of [_ATS_CCOMP_EXCEPTION_NONE]
/*
exnconlst-declaration(end)
*/
/*
assumelst-declaration(beg)
*/
/*
assumelst-declaration(end)
*/
/*
extypelst-declaration(beg)
*/
/*
extypelst-declaration(end)
*/
#if(0)
#if(0)
ATSglobaldec()
atstkind_type(atstype_ptrk)
_057_vagrant_057_stream_056_sats__interleave__0(atstkind_type(atstype_ptrk), atstkind_type(atstype_ptrk)) ;
#endif // end of [QUALIFIED]
#endif // end of [TEMPLATE]

#if(0)
ATSstaticdec()
atstype_boxed
__patsfun_1__1(atstkind_type(atstype_ptrk), atstkind_type(atstype_ptrk)) ;
#endif // end of [TEMPLATE]

#if(0)
#if(0)
ATSglobaldec()
atstkind_type(atstype_ptrk)
_057_vagrant_057_stream_056_sats__merge__2(atstkind_type(atstype_ptrk), atstkind_type(atstype_ptrk), atstype_cloptr) ;
#endif // end of [QUALIFIED]
#endif // end of [TEMPLATE]

#if(0)
ATSstaticdec()
atstype_boxed
__patsfun_3__3(atstkind_type(atstype_ptrk), atstkind_type(atstype_ptrk), atstype_funptr) ;
#endif // end of [TEMPLATE]

#if(0)
#if(0)
ATSglobaldec()
atstype_boxed
_057_vagrant_057_stream_056_sats__head__4(atstkind_type(atstype_ptrk)) ;
#endif // end of [QUALIFIED]
#endif // end of [TEMPLATE]

#if(0)
#if(0)
ATSglobaldec()
atstkind_type(atstype_ptrk)
_057_vagrant_057_stream_056_sats__tail__5(atstkind_type(atstype_ptrk)) ;
#endif // end of [QUALIFIED]
#endif // end of [TEMPLATE]

#if(0)
ATSstaticdec()
atstype_boxed
__patsfun_6__6() ;
#endif // end of [TEMPLATE]

#if(0)
#if(0)
ATSglobaldec()
atstkind_type(atstype_ptrk)
_057_vagrant_057_stream_056_sats__drop__7(atstkind_type(atstype_ptrk), atstkind_t0ype(atstype_int)) ;
#endif // end of [QUALIFIED]
#endif // end of [TEMPLATE]

#if(0)
#if(0)
ATSglobaldec()
atstkind_type(atstype_ptrk)
_057_vagrant_057_stream_056_sats__take__8(atstkind_type(atstype_ptrk), atstkind_t0ype(atstype_int)) ;
#endif // end of [QUALIFIED]
#endif // end of [TEMPLATE]

#if(0)
ATSstaticdec()
atstype_boxed
__patsfun_9__9() ;
#endif // end of [TEMPLATE]

#if(0)
ATSstaticdec()
atstype_boxed
__patsfun_10__10() ;
#endif // end of [TEMPLATE]

#if(0)
ATSstaticdec()
atstype_boxed
__patsfun_11__11(atstkind_type(atstype_ptrk), atstkind_t0ype(atstype_int), atstyvar_type(a)) ;
#endif // end of [TEMPLATE]

#if(0)
#if(0)
ATSglobaldec()
atstype_boxed
_057_vagrant_057_stream_056_sats__get__12(atstkind_type(atstype_ptrk), atstkind_t0ype(atstype_int)) ;
#endif // end of [QUALIFIED]
#endif // end of [TEMPLATE]

#if(0)
#if(0)
ATSglobaldec()
atstkind_type(atstype_ptrk)
_057_vagrant_057_stream_056_sats__zip__13(atstkind_type(atstype_ptrk), atstkind_type(atstype_ptrk), atstype_cloptr) ;
#endif // end of [QUALIFIED]
#endif // end of [TEMPLATE]

#if(0)
ATSstaticdec()
atstype_boxed
__patsfun_14__14() ;
#endif // end of [TEMPLATE]

#if(0)
ATSstaticdec()
atstype_boxed
__patsfun_15__15() ;
#endif // end of [TEMPLATE]

#if(0)
ATSstaticdec()
atstype_boxed
__patsfun_16__16(atstkind_type(atstype_ptrk), atstkind_type(atstype_ptrk), atstype_funptr, atstyvar_type(a), atstyvar_type(b)) ;
#endif // end of [TEMPLATE]

#if(0)
#if(0)
ATSglobaldec()
atstkind_type(atstype_ptrk)
_057_vagrant_057_stream_056_sats__filter__17(atstkind_type(atstype_ptrk), atstype_cloptr) ;
#endif // end of [QUALIFIED]
#endif // end of [TEMPLATE]

#if(0)
ATSstaticdec()
atstype_boxed
__patsfun_18__18() ;
#endif // end of [TEMPLATE]

#if(0)
ATSstaticdec()
atstype_boxed
__patsfun_19__19(atstkind_type(atstype_ptrk), atstype_funptr, atstyvar_type(a)) ;
#endif // end of [TEMPLATE]

#if(0)
#if(0)
ATSglobaldec()
atsvoid_t0ype
_057_vagrant_057_stream_056_sats__fprint_stream__20(atstkind_type(atstype_ptrk), atstkind_type(atstype_ptrk), atstkind_t0ype(atstype_int), atstype_funptr) ;
#endif // end of [QUALIFIED]
#endif // end of [TEMPLATE]

#if(0)
#if(0)
ATSglobaldec()
atstkind_type(atstype_ptrk)
_057_vagrant_057_stream_056_sats__map__21(atstkind_type(atstype_ptrk), atstype_cloptr) ;
#endif // end of [QUALIFIED]
#endif // end of [TEMPLATE]

#if(0)
ATSstaticdec()
atstype_boxed
__patsfun_22__22() ;
#endif // end of [TEMPLATE]

#if(0)
ATSstaticdec()
atstype_boxed
__patsfun_23__23(atstype_funptr, atstyvar_type(a), atstkind_type(atstype_ptrk)) ;
#endif // end of [TEMPLATE]

#if(0)
/*
/vagrant/stream.dats: 121(line=8, offs=26) -- 230(line=13, offs=3)
*/
/*
local: 
global: interleave$0$0(level=0)
local: 
global: 
*/
ATSglobaldec()
/*
imparg = a(3847)
tmparg = S2Evar(a(3847))
tmpsub = None()
*/
atstkind_type(atstype_ptrk)
_057_vagrant_057_stream_056_sats__interleave__0(atstkind_type(atstype_ptrk) arg0, atstkind_type(atstype_ptrk) arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret0, atstkind_type(atstype_ptrk)) ;
/* tmpvardeclst(end) */
/* funbodyinstrlst(beg) */
/*
emit_instr: loc0 = /vagrant/stream.dats: 110(line=8, offs=15) -- 230(line=13, offs=3)
*/
ATSINSlab(__patsflab_interleave):
/*
emit_instr: loc0 = /vagrant/stream.dats: 135(line=9, offs=2) -- 230(line=13, offs=3)
*/
ATSINSmove_delay(tmpret0, atstype_boxed, ATSPMVcfunlab(-1, __patsfun_1__1, (arg0, arg1))) ;
/* funbodyinstrlst(end) */
ATSreturn(tmpret0) ;
} /* end of [_057_vagrant_057_stream_056_sats__interleave__0] */
#endif // end of [TEMPLATE]

#if(0)
/*
/vagrant/stream.dats: 135(line=9, offs=2) -- 230(line=13, offs=3)
*/
/*
local: 
global: __patsfun_1$0(level=1)
local: xs$62(1)(HSEapp(HSEcst(atstkind_type); HSEs2exp(S2Eextkind(atstype_ptrk)))), ys$63(1)(HSEapp(HSEcst(atstkind_type); HSEs2exp(S2Eextkind(atstype_ptrk))))
global: xs$62(1)(HSEapp(HSEcst(atstkind_type); HSEs2exp(S2Eextkind(atstype_ptrk)))), ys$63(1)(HSEapp(HSEcst(atstkind_type); HSEs2exp(S2Eextkind(atstype_ptrk))))
*/
ATSstaticdec()
atstype_boxed
__patsfun_1__1(atstkind_type(atstype_ptrk) env0, atstkind_type(atstype_ptrk) env1)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret1, atstype_boxed) ;
ATStmpdec(tmp2, atstype_boxed) ;
ATStmpdec(tmp3, atstyvar_type(a)) ;
ATStmpdec(tmp4, atstkind_type(atstype_ptrk)) ;
ATStmpdec(tmp5, atstkind_type(atstype_ptrk)) ;
/* tmpvardeclst(end) */
/* funbodyinstrlst(beg) */
/*
emit_instr: loc0 = /vagrant/stream.dats: 135(line=9, offs=2) -- 230(line=13, offs=3)
*/
ATSINSlab(__patsflab___patsfun_1):
/*
emit_instr: loc0 = /vagrant/stream.dats: 153(line=10, offs=9) -- 156(line=10, offs=12)
*/
ATSINSmove_lazyeval(tmp2, atstype_boxed, env0) ;
/*
emit_instr: loc0 = /vagrant/stream.dats: 147(line=10, offs=3) -- 226(line=12, offs=18)
*/
ATScaseofbeg()
/*
** ibranchlst-beg
*/
ATSbranchbeg() ;
/*
emit_instr: loc0 = /vagrant/stream.dats: 165(line=11, offs=5) -- 177(line=11, offs=17)
*/
__atstmplab0:
/*
emit_instr: loc0 = /vagrant/stream.dats: 153(line=10, offs=9) -- 156(line=10, offs=12)
*/
if (ATSCKptrisnull(tmp2)) { ATSgoto(__atstmplab3) ; }
/*
emit_instr: loc0 = /vagrant/stream.dats: 177(line=11, offs=17) -- 177(line=11, offs=17)
*/
__atstmplab1:
/*
emit_instr: loc0 = /vagrant/stream.dats: 171(line=11, offs=11) -- 172(line=11, offs=12)
*/
ATSINSmove(tmp3, ATSSELcon(tmp2, postiats_tysum_0, atslab__0)) ;
/*
emit_instr: loc0 = /vagrant/stream.dats: 174(line=11, offs=14) -- 176(line=11, offs=16)
*/
ATSINSmove(tmp4, ATSSELcon(tmp2, postiats_tysum_0, atslab__1)) ;
/*
emit_instr: loc0 = : 0(line=0, offs=0) -- 0(line=0, offs=0)
*/
/*
ibranch-mbody:
*/
/*
emit_instr: loc0 = /vagrant/stream.dats: 187(line=11, offs=27) -- 206(line=11, offs=46)
*/
ATSINSmove(tmp5, PMVtmpltcst(interleave<S2Evar(a(3847))>)(env1, tmp4)) ;

/*
emit_instr: loc0 = /vagrant/stream.dats: 182(line=11, offs=22) -- 206(line=11, offs=46)
*/

ATSINSmove_con1(tmpret1, postiats_tysum_0) ;
#if(0)
ATSINSstore_con_tag(tmpret1, 0) ;
#endif
ATSINSstore_con_ofs(tmpret1, postiats_tysum_0, atslab__0, tmp3) ;
ATSINSstore_con_ofs(tmpret1, postiats_tysum_0, atslab__1, tmp5) ;

ATSbranchend() ;

ATSbranchbeg() ;
/*
emit_instr: loc0 = /vagrant/stream.dats: 213(line=12, offs=5) -- 219(line=12, offs=11)
*/
__atstmplab2:
/*
emit_instr: loc0 = /vagrant/stream.dats: 153(line=10, offs=9) -- 156(line=10, offs=12)
*/
#if(0)
if (ATSCKptriscons(tmp2)) { ATSINSdeadcode_fail() ; }
#endif
/*
emit_instr: loc0 = /vagrant/stream.dats: 219(line=12, offs=11) -- 219(line=12, offs=11)
*/
__atstmplab3:
/*
emit_instr: loc0 = : 0(line=0, offs=0) -- 0(line=0, offs=0)
*/
/*
ibranch-mbody:
*/
/*
emit_instr: loc0 = /vagrant/stream.dats: 223(line=12, offs=15) -- 226(line=12, offs=18)
*/
ATSINSmove_lazyeval(tmpret1, atstype_boxed, env1) ;
ATSbranchend() ;

/*
** ibranchlst-end
*/
ATScaseofend()

/* funbodyinstrlst(end) */
ATSreturn(tmpret1) ;
} /* end of [__patsfun_1__1] */
#endif // end of [TEMPLATE]

#if(0)
/*
/vagrant/stream.dats: 255(line=15, offs=21) -- 456(line=24, offs=3)
*/
/*
local: 
global: merge$2$0(level=0)
local: 
global: 
*/
ATSglobaldec()
/*
imparg = a(3850)
tmparg = S2Evar(a(3850))
tmpsub = None()
*/
atstkind_type(atstype_ptrk)
_057_vagrant_057_stream_056_sats__merge__2(atstkind_type(atstype_ptrk) arg0, atstkind_type(atstype_ptrk) arg1, atstype_cloptr arg2)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret6, atstkind_type(atstype_ptrk)) ;
/* tmpvardeclst(end) */
/* funbodyinstrlst(beg) */
/*
emit_instr: loc0 = /vagrant/stream.dats: 249(line=15, offs=15) -- 456(line=24, offs=3)
*/
ATSINSlab(__patsflab_merge):
/*
emit_instr: loc0 = /vagrant/stream.dats: 272(line=16, offs=2) -- 456(line=24, offs=3)
*/
ATSINSmove_delay(tmpret6, atstype_boxed, ATSPMVcfunlab(-1, __patsfun_3__3, (arg0, arg1, arg2))) ;
/* funbodyinstrlst(end) */
ATSreturn(tmpret6) ;
} /* end of [_057_vagrant_057_stream_056_sats__merge__2] */
#endif // end of [TEMPLATE]

#if(0)
/*
/vagrant/stream.dats: 272(line=16, offs=2) -- 456(line=24, offs=3)
*/
/*
local: 
global: __patsfun_3$0(level=1)
local: xs$66(1)(HSEapp(HSEcst(atstkind_type); HSEs2exp(S2Eextkind(atstype_ptrk)))), ys$67(1)(HSEapp(HSEcst(atstkind_type); HSEs2exp(S2Eextkind(atstype_ptrk)))), f$68(1)(HSEfun(HSEtyvar(a(3850)), HSEtyvar(a(3850)); HSEapp(HSEcst(atstkind_t0ype); HSEs2exp(S2Eextkind(atstype_int)))))
global: xs$66(1)(HSEapp(HSEcst(atstkind_type); HSEs2exp(S2Eextkind(atstype_ptrk)))), ys$67(1)(HSEapp(HSEcst(atstkind_type); HSEs2exp(S2Eextkind(atstype_ptrk)))), f$68(1)(HSEfun(HSEtyvar(a(3850)), HSEtyvar(a(3850)); HSEapp(HSEcst(atstkind_t0ype); HSEs2exp(S2Eextkind(atstype_int)))))
*/
ATSstaticdec()
atstype_boxed
__patsfun_3__3(atstkind_type(atstype_ptrk) env0, atstkind_type(atstype_ptrk) env1, atstype_funptr env2)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret7, atstype_boxed) ;
ATStmpdec(tmp8, atstype_boxed) ;
ATStmpdec(tmp9, atstyvar_type(a)) ;
ATStmpdec(tmp10, atstkind_type(atstype_ptrk)) ;
ATStmpdec(tmp11, atstype_boxed) ;
ATStmpdec(tmp12, atstyvar_type(a)) ;
ATStmpdec(tmp13, atstkind_type(atstype_ptrk)) ;
ATStmpdec(tmp14, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp15, atstkind_t0ype(atstype_int)) ;
ATStmpdec(tmp16, atstkind_type(atstype_ptrk)) ;
ATStmpdec(tmp17, atstkind_type(atstype_ptrk)) ;
/* tmpvardeclst(end) */
/* funbodyinstrlst(beg) */
/*
emit_instr: loc0 = /vagrant/stream.dats: 272(line=16, offs=2) -- 456(line=24, offs=3)
*/
ATSINSlab(__patsflab___patsfun_3):
/*
emit_instr: loc0 = /vagrant/stream.dats: 284(line=17, offs=3) -- 452(line=23, offs=6)
*/
/*
letpush(beg)
*/
/*
emit_instr: loc0 = /vagrant/stream.dats: 313(line=18, offs=25) -- 316(line=18, offs=28)
*/
ATSINSmove_lazyeval(tmp8, atstype_boxed, env0) ;
/*
emit_instr: loc0 = /vagrant/stream.dats: 297(line=18, offs=9) -- 310(line=18, offs=22)
*/
if (ATSCKptrisnull(tmp8)) { ATSINScaseof_fail("/vagrant/stream.dats: 297(line=18, offs=9) -- 316(line=18, offs=28)") ; }
/*
emit_instr: loc0 = /vagrant/stream.dats: 303(line=18, offs=15) -- 304(line=18, offs=16)
*/
ATSINSmove(tmp9, ATSSELcon(tmp8, postiats_tysum_1, atslab__0)) ;
/*
emit_instr: loc0 = /vagrant/stream.dats: 306(line=18, offs=18) -- 309(line=18, offs=21)
*/
ATSINSmove(tmp10, ATSSELcon(tmp8, postiats_tysum_1, atslab__1)) ;
/*
emit_instr: loc0 = /vagrant/stream.dats: 342(line=19, offs=25) -- 345(line=19, offs=28)
*/
ATSINSmove_lazyeval(tmp11, atstype_boxed, env1) ;
/*
emit_instr: loc0 = /vagrant/stream.dats: 326(line=19, offs=9) -- 339(line=19, offs=22)
*/
if (ATSCKptrisnull(tmp11)) { ATSINScaseof_fail("/vagrant/stream.dats: 326(line=19, offs=9) -- 345(line=19, offs=28)") ; }
/*
emit_instr: loc0 = /vagrant/stream.dats: 332(line=19, offs=15) -- 333(line=19, offs=16)
*/
ATSINSmove(tmp12, ATSSELcon(tmp11, postiats_tysum_1, atslab__0)) ;
/*
emit_instr: loc0 = /vagrant/stream.dats: 335(line=19, offs=18) -- 338(line=19, offs=21)
*/
ATSINSmove(tmp13, ATSSELcon(tmp11, postiats_tysum_1, atslab__1)) ;
/*
letpush(end)
*/

/*
emit_instr: loc0 = /vagrant/stream.dats: 355(line=20, offs=9) -- 363(line=20, offs=17)
*/
ATSINSmove(tmp15, ATSfunclo_clo(env2, (atstype_cloptr, atstyvar_type(a), atstyvar_type(a)), atstkind_t0ype(atstype_int))(env2, tmp9, tmp12)) ;

/*
emit_instr: loc0 = /vagrant/stream.dats: 355(line=20, offs=9) -- 367(line=20, offs=21)
*/
ATSINSmove(tmp14, PMVtmpltcst(lt_g0int_int<S2Eextkind(atstype_int)>)(tmp15, ATSPMVi0nt(0))) ;

/*
emit_instr: loc0 = /vagrant/stream.dats: 352(line=20, offs=6) -- 445(line=22, offs=37)
*/
ATSif(
tmp14
) ATSthen() {
/*
emit_instr: loc0 = /vagrant/stream.dats: 387(line=21, offs=18) -- 405(line=21, offs=36)
*/
ATSINSmove(tmp16, PMVtmpltcst(merge<S2Evar(a(3850))>)(tmp10, env1, env2)) ;

/*
emit_instr: loc0 = /vagrant/stream.dats: 378(line=21, offs=9) -- 406(line=21, offs=37)
*/

ATSINSmove_con1(tmpret7, postiats_tysum_1) ;
#if(0)
ATSINSstore_con_tag(tmpret7, 0) ;
#endif
ATSINSstore_con_ofs(tmpret7, postiats_tysum_1, atslab__0, tmp9) ;
ATSINSstore_con_ofs(tmpret7, postiats_tysum_1, atslab__1, tmp16) ;

} ATSelse() {
/*
emit_instr: loc0 = /vagrant/stream.dats: 426(line=22, offs=18) -- 444(line=22, offs=36)
*/
ATSINSmove(tmp17, PMVtmpltcst(merge<S2Evar(a(3850))>)(tmp13, env0, env2)) ;

/*
emit_instr: loc0 = /vagrant/stream.dats: 417(line=22, offs=9) -- 445(line=22, offs=37)
*/

ATSINSmove_con1(tmpret7, postiats_tysum_1) ;
#if(0)
ATSINSstore_con_tag(tmpret7, 0) ;
#endif
ATSINSstore_con_ofs(tmpret7, postiats_tysum_1, atslab__0, tmp12) ;
ATSINSstore_con_ofs(tmpret7, postiats_tysum_1, atslab__1, tmp17) ;

} /* ATSendif */
/*
emit_instr: loc0 = /vagrant/stream.dats: 284(line=17, offs=3) -- 452(line=23, offs=6)
*/
/*
INSletpop()
*/
/* funbodyinstrlst(end) */
ATSreturn(tmpret7) ;
} /* end of [__patsfun_3__3] */
#endif // end of [TEMPLATE]

#if(0)
/*
/vagrant/stream.dats: 479(line=26, offs=20) -- 552(line=28, offs=24)
*/
/*
local: 
global: head$4$0(level=0)
local: 
global: 
*/
ATSglobaldec()
/*
imparg = a(3853)
tmparg = S2Evar(a(3853))
tmpsub = None()
*/
atstype_boxed
_057_vagrant_057_stream_056_sats__head__4(atstkind_type(atstype_ptrk) arg0)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret18, atstype_boxed) ;
ATStmpdec(tmp19, atstype_boxed) ;
ATStmpdec(tmp20, atstyvar_type(a)) ;
/* tmpvardeclst(end) */
/* funbodyinstrlst(beg) */
/*
emit_instr: loc0 = /vagrant/stream.dats: 474(line=26, offs=15) -- 552(line=28, offs=24)
*/
ATSINSlab(__patsflab_head):
/*
emit_instr: loc0 = /vagrant/stream.dats: 492(line=26, offs=33) -- 495(line=26, offs=36)
*/
ATSINSmove_lazyeval(tmp19, atstype_boxed, arg0) ;
/*
emit_instr: loc0 = /vagrant/stream.dats: 486(line=26, offs=27) -- 552(line=28, offs=24)
*/
ATScaseofbeg()
/*
** ibranchlst-beg
*/
ATSbranchbeg() ;
/*
emit_instr: loc0 = /vagrant/stream.dats: 503(line=27, offs=4) -- 515(line=27, offs=16)
*/
__atstmplab4:
/*
emit_instr: loc0 = /vagrant/stream.dats: 492(line=26, offs=33) -- 495(line=26, offs=36)
*/
if (ATSCKptrisnull(tmp19)) { ATSgoto(__atstmplab7) ; }
/*
emit_instr: loc0 = /vagrant/stream.dats: 515(line=27, offs=16) -- 515(line=27, offs=16)
*/
__atstmplab5:
/*
emit_instr: loc0 = /vagrant/stream.dats: 509(line=27, offs=10) -- 510(line=27, offs=11)
*/
ATSINSmove(tmp20, ATSSELcon(tmp19, postiats_tysum_2, atslab__0)) ;
/*
emit_instr: loc0 = : 0(line=0, offs=0) -- 0(line=0, offs=0)
*/
/*
ibranch-mbody:
*/
/*
emit_instr: loc0 = /vagrant/stream.dats: 519(line=27, offs=20) -- 526(line=27, offs=27)
*/

ATSINSmove_con1(tmpret18, postiats_tysum_3) ;
#if(0)
ATSINSstore_con_tag(tmpret18, 1) ;
#endif
ATSINSstore_con_ofs(tmpret18, postiats_tysum_3, atslab__0, tmp20) ;

ATSbranchend() ;

ATSbranchbeg() ;
/*
emit_instr: loc0 = /vagrant/stream.dats: 532(line=28, offs=4) -- 538(line=28, offs=10)
*/
__atstmplab6:
/*
emit_instr: loc0 = /vagrant/stream.dats: 492(line=26, offs=33) -- 495(line=26, offs=36)
*/
#if(0)
if (ATSCKptriscons(tmp19)) { ATSINSdeadcode_fail() ; }
#endif
/*
emit_instr: loc0 = /vagrant/stream.dats: 538(line=28, offs=10) -- 538(line=28, offs=10)
*/
__atstmplab7:
/*
emit_instr: loc0 = : 0(line=0, offs=0) -- 0(line=0, offs=0)
*/
/*
ibranch-mbody:
*/
/*
emit_instr: loc0 = /vagrant/stream.dats: 542(line=28, offs=14) -- 552(line=28, offs=24)
*/

ATSINSmove_con0(tmpret18, 0) ;

ATSbranchend() ;

/*
** ibranchlst-end
*/
ATScaseofend()

/* funbodyinstrlst(end) */
ATSreturn(tmpret18) ;
} /* end of [_057_vagrant_057_stream_056_sats__head__4] */
#endif // end of [TEMPLATE]

#if(0)
/*
/vagrant/stream.dats: 576(line=30, offs=20) -- 648(line=32, offs=29)
*/
/*
local: 
global: tail$5$0(level=0)
local: 
global: 
*/
ATSglobaldec()
/*
imparg = a(3856)
tmparg = S2Evar(a(3856))
tmpsub = None()
*/
atstkind_type(atstype_ptrk)
_057_vagrant_057_stream_056_sats__tail__5(atstkind_type(atstype_ptrk) arg0)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret22, atstkind_type(atstype_ptrk)) ;
ATStmpdec(tmp23, atstype_boxed) ;
ATStmpdec(tmp25, atstkind_type(atstype_ptrk)) ;
/* tmpvardeclst(end) */
/* funbodyinstrlst(beg) */
/*
emit_instr: loc0 = /vagrant/stream.dats: 571(line=30, offs=15) -- 648(line=32, offs=29)
*/
ATSINSlab(__patsflab_tail):
/*
emit_instr: loc0 = /vagrant/stream.dats: 589(line=30, offs=33) -- 592(line=30, offs=36)
*/
ATSINSmove_lazyeval(tmp23, atstype_boxed, arg0) ;
/*
emit_instr: loc0 = /vagrant/stream.dats: 583(line=30, offs=27) -- 648(line=32, offs=29)
*/
ATScaseofbeg()
/*
** ibranchlst-beg
*/
ATSbranchbeg() ;
/*
emit_instr: loc0 = /vagrant/stream.dats: 600(line=31, offs=4) -- 612(line=31, offs=16)
*/
__atstmplab8:
/*
emit_instr: loc0 = /vagrant/stream.dats: 589(line=30, offs=33) -- 592(line=30, offs=36)
*/
if (ATSCKptrisnull(tmp23)) { ATSgoto(__atstmplab11) ; }
/*
emit_instr: loc0 = /vagrant/stream.dats: 612(line=31, offs=16) -- 612(line=31, offs=16)
*/
__atstmplab9:
/*
emit_instr: loc0 = /vagrant/stream.dats: 609(line=31, offs=13) -- 611(line=31, offs=15)
*/
ATSINSmove(tmp25, ATSSELcon(tmp23, postiats_tysum_4, atslab__1)) ;
/*
emit_instr: loc0 = : 0(line=0, offs=0) -- 0(line=0, offs=0)
*/
/*
ibranch-mbody:
*/
/*
emit_instr: loc0 = /vagrant/stream.dats: 616(line=31, offs=20) -- 618(line=31, offs=22)
*/
ATSINSmove(tmpret22, tmp25) ;
ATSbranchend() ;

ATSbranchbeg() ;
/*
emit_instr: loc0 = /vagrant/stream.dats: 623(line=32, offs=4) -- 629(line=32, offs=10)
*/
__atstmplab10:
/*
emit_instr: loc0 = /vagrant/stream.dats: 589(line=30, offs=33) -- 592(line=30, offs=36)
*/
#if(0)
if (ATSCKptriscons(tmp23)) { ATSINSdeadcode_fail() ; }
#endif
/*
emit_instr: loc0 = /vagrant/stream.dats: 629(line=32, offs=10) -- 629(line=32, offs=10)
*/
__atstmplab11:
/*
emit_instr: loc0 = : 0(line=0, offs=0) -- 0(line=0, offs=0)
*/
/*
ibranch-mbody:
*/
/*
emit_instr: loc0 = /vagrant/stream.dats: 633(line=32, offs=14) -- 648(line=32, offs=29)
*/
ATSINSmove_delay(tmpret22, atstype_boxed, ATSPMVcfunlab(-1, __patsfun_6__6, ())) ;
ATSbranchend() ;

/*
** ibranchlst-end
*/
ATScaseofend()

/* funbodyinstrlst(end) */
ATSreturn(tmpret22) ;
} /* end of [_057_vagrant_057_stream_056_sats__tail__5] */
#endif // end of [TEMPLATE]

#if(0)
/*
/vagrant/stream.dats: 633(line=32, offs=14) -- 648(line=32, offs=29)
*/
/*
local: 
global: __patsfun_6$0(level=1)
local: 
global: 
*/
ATSstaticdec()
atstype_boxed
__patsfun_6__6()
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret26, atstype_boxed) ;
/* tmpvardeclst(end) */
/* funbodyinstrlst(beg) */
/*
emit_instr: loc0 = /vagrant/stream.dats: 633(line=32, offs=14) -- 648(line=32, offs=29)
*/
ATSINSlab(__patsflab___patsfun_6):
/*
emit_instr: loc0 = /vagrant/stream.dats: 641(line=32, offs=22) -- 647(line=32, offs=28)
*/

ATSINSmove_con0(tmpret26, 0) ;

/* funbodyinstrlst(end) */
ATSreturn(tmpret26) ;
} /* end of [__patsfun_6__6] */
#endif // end of [TEMPLATE]

#if(0)
/*
/vagrant/stream.dats: 672(line=34, offs=20) -- 733(line=37, offs=28)
*/
/*
local: 
global: drop$7$0(level=0)
local: 
global: 
*/
ATSglobaldec()
/*
imparg = a(3859)
tmparg = S2Evar(a(3859))
tmpsub = None()
*/
atstkind_type(atstype_ptrk)
_057_vagrant_057_stream_056_sats__drop__7(atstkind_type(atstype_ptrk) arg0, atstkind_t0ype(atstype_int) arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec(argx0, atstkind_type(atstype_ptrk)) ;
ATStmpdec(argx1, atstkind_t0ype(atstype_int)) ;
ATStmpdec(tmpret27, atstkind_type(atstype_ptrk)) ;
ATStmpdec(tmp28, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp29, atstkind_type(atstype_ptrk)) ;
ATStmpdec(tmp30, atstkind_t0ype(atstype_int)) ;
/* tmpvardeclst(end) */
/* funbodyinstrlst(beg) */
/*
emit_instr: loc0 = /vagrant/stream.dats: 667(line=34, offs=15) -- 733(line=37, offs=28)
*/
ATSINSlab(__patsflab_drop):
/*
emit_instr: loc0 = /vagrant/stream.dats: 687(line=35, offs=5) -- 693(line=35, offs=11)
*/
ATSINSmove(tmp28, PMVtmpltcst(lte_g0int_int<S2Eextkind(atstype_int)>)(arg1, ATSPMVi0nt(0))) ;

/*
emit_instr: loc0 = /vagrant/stream.dats: 684(line=35, offs=2) -- 733(line=37, offs=28)
*/
ATSif(
tmp28
) ATSthen() {
/*
emit_instr: loc0 = /vagrant/stream.dats: 701(line=36, offs=7) -- 703(line=36, offs=9)
*/
ATSINSmove(tmpret27, arg0) ;
} ATSelse() {
/*
emit_instr: loc0 = /vagrant/stream.dats: 718(line=37, offs=13) -- 726(line=37, offs=21)
*/
ATSINSmove(tmp29, PMVtmpltcst(tail<S2Evar(a(3859))>)(arg0)) ;

/*
emit_instr: loc0 = /vagrant/stream.dats: 729(line=37, offs=24) -- 732(line=37, offs=27)
*/
ATSINSmove(tmp30, PMVtmpltcst(g0int_sub<S2Eextkind(atstype_int)>)(arg1, ATSPMVi0nt(1))) ;

/*
emit_instr: loc0 = /vagrant/stream.dats: 712(line=37, offs=7) -- 733(line=37, offs=28)
*/
ATStailcalbeg()
ATSINSmove_tlcal(argx0, tmp29) ;
ATSINSmove_tlcal(argx1, tmp30) ;
ATSINSargmove_tlcal(arg0, argx0) ;
ATSINSargmove_tlcal(arg1, argx1) ;
ATSgoto(__patsflab_drop) ;
ATStailcalend()

} /* ATSendif */
/* funbodyinstrlst(end) */
ATSreturn(tmpret27) ;
} /* end of [_057_vagrant_057_stream_056_sats__drop__7] */
#endif // end of [TEMPLATE]

#if(0)
/*
/vagrant/stream.dats: 756(line=39, offs=20) -- 916(line=44, offs=52)
*/
/*
local: 
global: take$8$0(level=0)
local: 
global: 
*/
ATSglobaldec()
/*
imparg = a(3860)
tmparg = S2Evar(a(3860))
tmpsub = None()
*/
atstkind_type(atstype_ptrk)
_057_vagrant_057_stream_056_sats__take__8(atstkind_type(atstype_ptrk) arg0, atstkind_t0ype(atstype_int) arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret31, atstkind_type(atstype_ptrk)) ;
ATStmpdec(tmp32, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp34, atstype_boxed) ;
ATStmpdec(tmp35, atstyvar_type(a)) ;
/* tmpvardeclst(end) */
/* funbodyinstrlst(beg) */
/*
emit_instr: loc0 = /vagrant/stream.dats: 751(line=39, offs=15) -- 916(line=44, offs=52)
*/
ATSINSlab(__patsflab_take):
/*
emit_instr: loc0 = /vagrant/stream.dats: 772(line=40, offs=5) -- 778(line=40, offs=11)
*/
ATSINSmove(tmp32, PMVtmpltcst(lte_g0int_int<S2Eextkind(atstype_int)>)(arg1, ATSPMVi0nt(0))) ;

/*
emit_instr: loc0 = /vagrant/stream.dats: 769(line=40, offs=2) -- 916(line=44, offs=52)
*/
ATSif(
tmp32
) ATSthen() {
/*
emit_instr: loc0 = /vagrant/stream.dats: 787(line=41, offs=7) -- 802(line=41, offs=22)
*/
ATSINSmove_delay(tmpret31, atstype_boxed, ATSPMVcfunlab(-1, __patsfun_9__9, ())) ;
} ATSelse() {
/*
emit_instr: loc0 = /vagrant/stream.dats: 816(line=42, offs=13) -- 824(line=42, offs=21)
*/
ATSINSmove(tmp34, PMVtmpltcst(head<S2Evar(a(3860))>)(arg0)) ;

/*
emit_instr: loc0 = /vagrant/stream.dats: 810(line=42, offs=7) -- 916(line=44, offs=52)
*/
ATScaseofbeg()
/*
** ibranchlst-beg
*/
ATSbranchbeg() ;
/*
emit_instr: loc0 = /vagrant/stream.dats: 834(line=43, offs=5) -- 844(line=43, offs=15)
*/
__atstmplab12:
/*
emit_instr: loc0 = /vagrant/stream.dats: 816(line=42, offs=13) -- 824(line=42, offs=21)
*/
if (ATSCKptriscons(tmp34)) { ATSgoto(__atstmplab15) ; }
/*
emit_instr: loc0 = /vagrant/stream.dats: 844(line=43, offs=15) -- 844(line=43, offs=15)
*/
__atstmplab13:
/*
emit_instr: loc0 = : 0(line=0, offs=0) -- 0(line=0, offs=0)
*/
/*
ibranch-mbody:
*/
/*
emit_instr: loc0 = /vagrant/stream.dats: 848(line=43, offs=19) -- 863(line=43, offs=34)
*/
ATSINSmove_delay(tmpret31, atstype_boxed, ATSPMVcfunlab(-1, __patsfun_10__10, ())) ;
ATSbranchend() ;

ATSbranchbeg() ;
/*
emit_instr: loc0 = /vagrant/stream.dats: 869(line=44, offs=5) -- 876(line=44, offs=12)
*/
__atstmplab14:
/*
emit_instr: loc0 = /vagrant/stream.dats: 816(line=42, offs=13) -- 824(line=42, offs=21)
*/
#if(0)
if (ATSCKptrisnull(tmp34)) { ATSINSdeadcode_fail() ; }
#endif
/*
emit_instr: loc0 = /vagrant/stream.dats: 876(line=44, offs=12) -- 876(line=44, offs=12)
*/
__atstmplab15:
/*
emit_instr: loc0 = /vagrant/stream.dats: 875(line=44, offs=11) -- 876(line=44, offs=12)
*/
ATSINSmove(tmp35, ATSSELcon(tmp34, postiats_tysum_5, atslab__0)) ;
/*
emit_instr: loc0 = : 0(line=0, offs=0) -- 0(line=0, offs=0)
*/
/*
ibranch-mbody:
*/
/*
emit_instr: loc0 = /vagrant/stream.dats: 881(line=44, offs=17) -- 916(line=44, offs=52)
*/
ATSINSmove_delay(tmpret31, atstype_boxed, ATSPMVcfunlab(-1, __patsfun_11__11, (arg0, arg1, tmp35))) ;
ATSbranchend() ;

/*
** ibranchlst-end
*/
ATScaseofend()

} /* ATSendif */
/* funbodyinstrlst(end) */
ATSreturn(tmpret31) ;
} /* end of [_057_vagrant_057_stream_056_sats__take__8] */
#endif // end of [TEMPLATE]

#if(0)
/*
/vagrant/stream.dats: 787(line=41, offs=7) -- 802(line=41, offs=22)
*/
/*
local: 
global: __patsfun_9$0(level=1)
local: 
global: 
*/
ATSstaticdec()
atstype_boxed
__patsfun_9__9()
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret33, atstype_boxed) ;
/* tmpvardeclst(end) */
/* funbodyinstrlst(beg) */
/*
emit_instr: loc0 = /vagrant/stream.dats: 787(line=41, offs=7) -- 802(line=41, offs=22)
*/
ATSINSlab(__patsflab___patsfun_9):
/*
emit_instr: loc0 = /vagrant/stream.dats: 795(line=41, offs=15) -- 801(line=41, offs=21)
*/

ATSINSmove_con0(tmpret33, 0) ;

/* funbodyinstrlst(end) */
ATSreturn(tmpret33) ;
} /* end of [__patsfun_9__9] */
#endif // end of [TEMPLATE]

#if(0)
/*
/vagrant/stream.dats: 848(line=43, offs=19) -- 863(line=43, offs=34)
*/
/*
local: 
global: __patsfun_10$0(level=1)
local: 
global: 
*/
ATSstaticdec()
atstype_boxed
__patsfun_10__10()
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret36, atstype_boxed) ;
/* tmpvardeclst(end) */
/* funbodyinstrlst(beg) */
/*
emit_instr: loc0 = /vagrant/stream.dats: 848(line=43, offs=19) -- 863(line=43, offs=34)
*/
ATSINSlab(__patsflab___patsfun_10):
/*
emit_instr: loc0 = /vagrant/stream.dats: 856(line=43, offs=27) -- 862(line=43, offs=33)
*/

ATSINSmove_con0(tmpret36, 0) ;

/* funbodyinstrlst(end) */
ATSreturn(tmpret36) ;
} /* end of [__patsfun_10__10] */
#endif // end of [TEMPLATE]

#if(0)
/*
/vagrant/stream.dats: 881(line=44, offs=17) -- 916(line=44, offs=52)
*/
/*
local: 
global: __patsfun_11$0(level=1)
local: xs$80(1)(HSEapp(HSEcst(atstkind_type); HSEs2exp(S2Eextkind(atstype_ptrk)))), n$81(1)(HSEapp(HSEcst(atstkind_t0ype); HSEs2exp(S2Eextkind(atstype_int)))), x$82(1)(HSEtyvar(a(3860)))
global: xs$80(1)(HSEapp(HSEcst(atstkind_type); HSEs2exp(S2Eextkind(atstype_ptrk)))), n$81(1)(HSEapp(HSEcst(atstkind_t0ype); HSEs2exp(S2Eextkind(atstype_int)))), x$82(1)(HSEtyvar(a(3860)))
*/
ATSstaticdec()
atstype_boxed
__patsfun_11__11(atstkind_type(atstype_ptrk) env0, atstkind_t0ype(atstype_int) env1, atstyvar_type(a) env2)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret37, atstype_boxed) ;
ATStmpdec(tmp38, atstkind_type(atstype_ptrk)) ;
ATStmpdec(tmp39, atstkind_type(atstype_ptrk)) ;
ATStmpdec(tmp40, atstkind_t0ype(atstype_int)) ;
/* tmpvardeclst(end) */
/* funbodyinstrlst(beg) */
/*
emit_instr: loc0 = /vagrant/stream.dats: 881(line=44, offs=17) -- 916(line=44, offs=52)
*/
ATSINSlab(__patsflab___patsfun_11):
/*
emit_instr: loc0 = /vagrant/stream.dats: 900(line=44, offs=36) -- 908(line=44, offs=44)
*/
ATSINSmove(tmp39, PMVtmpltcst(tail<S2Evar(a(3860))>)(env0)) ;

/*
emit_instr: loc0 = /vagrant/stream.dats: 911(line=44, offs=47) -- 914(line=44, offs=50)
*/
ATSINSmove(tmp40, PMVtmpltcst(g0int_sub<S2Eextkind(atstype_int)>)(env1, ATSPMVi0nt(1))) ;

/*
emit_instr: loc0 = /vagrant/stream.dats: 894(line=44, offs=30) -- 915(line=44, offs=51)
*/
ATSINSmove(tmp38, PMVtmpltcst(take<S2Evar(a(3860))>)(tmp39, tmp40)) ;

/*
emit_instr: loc0 = /vagrant/stream.dats: 889(line=44, offs=25) -- 915(line=44, offs=51)
*/

ATSINSmove_con1(tmpret37, postiats_tysum_6) ;
#if(0)
ATSINSstore_con_tag(tmpret37, 0) ;
#endif
ATSINSstore_con_ofs(tmpret37, postiats_tysum_6, atslab__0, env2) ;
ATSINSstore_con_ofs(tmpret37, postiats_tysum_6, atslab__1, tmp38) ;

/* funbodyinstrlst(end) */
ATSreturn(tmpret37) ;
} /* end of [__patsfun_11__11] */
#endif // end of [TEMPLATE]

#if(0)
/*
/vagrant/stream.dats: 939(line=46, offs=19) -- 1066(line=51, offs=28)
*/
/*
local: 
global: get$12$0(level=0)
local: 
global: 
*/
ATSglobaldec()
/*
imparg = a(3863)
tmparg = S2Evar(a(3863))
tmpsub = None()
*/
atstype_boxed
_057_vagrant_057_stream_056_sats__get__12(atstkind_type(atstype_ptrk) arg0, atstkind_t0ype(atstype_int) arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec(argx0, atstkind_type(atstype_ptrk)) ;
ATStmpdec(argx1, atstkind_t0ype(atstype_int)) ;
ATStmpdec(tmpret41, atstype_boxed) ;
ATStmpdec(tmp42, atstype_boxed) ;
ATStmpdec(tmp43, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp44, atstkind_type(atstype_ptrk)) ;
ATStmpdec(tmp45, atstkind_t0ype(atstype_int)) ;
/* tmpvardeclst(end) */
/* funbodyinstrlst(beg) */
/*
emit_instr: loc0 = /vagrant/stream.dats: 935(line=46, offs=15) -- 1066(line=51, offs=28)
*/
ATSINSlab(__patsflab_get):
/*
emit_instr: loc0 = /vagrant/stream.dats: 955(line=46, offs=35) -- 958(line=46, offs=38)
*/
ATSINSmove_lazyeval(tmp42, atstype_boxed, arg0) ;
/*
emit_instr: loc0 = /vagrant/stream.dats: 949(line=46, offs=29) -- 1066(line=51, offs=28)
*/
ATScaseofbeg()
/*
** ibranchlst-beg
*/
ATSbranchbeg() ;
/*
emit_instr: loc0 = /vagrant/stream.dats: 967(line=47, offs=4) -- 973(line=47, offs=10)
*/
__atstmplab16:
/*
emit_instr: loc0 = /vagrant/stream.dats: 955(line=46, offs=35) -- 958(line=46, offs=38)
*/
if (ATSCKptriscons(tmp42)) { ATSgoto(__atstmplab19) ; }
/*
emit_instr: loc0 = /vagrant/stream.dats: 973(line=47, offs=10) -- 973(line=47, offs=10)
*/
__atstmplab17:
/*
emit_instr: loc0 = : 0(line=0, offs=0) -- 0(line=0, offs=0)
*/
/*
ibranch-mbody:
*/
/*
emit_instr: loc0 = /vagrant/stream.dats: 977(line=47, offs=14) -- 987(line=47, offs=24)
*/

ATSINSmove_con0(tmpret41, 0) ;

ATSbranchend() ;

ATSbranchbeg() ;
/*
emit_instr: loc0 = /vagrant/stream.dats: 992(line=48, offs=4) -- 1003(line=48, offs=15)
*/
__atstmplab18:
/*
emit_instr: loc0 = /vagrant/stream.dats: 955(line=46, offs=35) -- 958(line=46, offs=38)
*/
#if(0)
if (ATSCKptrisnull(tmp42)) { ATSINSdeadcode_fail() ; }
#endif
/*
emit_instr: loc0 = /vagrant/stream.dats: 1003(line=48, offs=15) -- 1003(line=48, offs=15)
*/
__atstmplab19:
/*
emit_instr: loc0 = : 0(line=0, offs=0) -- 0(line=0, offs=0)
*/
/*
ibranch-mbody:
*/
/*
emit_instr: loc0 = /vagrant/stream.dats: 1013(line=49, offs=6) -- 1018(line=49, offs=11)
*/
ATSINSmove(tmp43, PMVtmpltcst(eq_g0int_int<S2Eextkind(atstype_int)>)(arg1, ATSPMVi0nt(0))) ;

/*
emit_instr: loc0 = /vagrant/stream.dats: 1010(line=49, offs=3) -- 1066(line=51, offs=28)
*/
ATSif(
tmp43
) ATSthen() {
/*
emit_instr: loc0 = /vagrant/stream.dats: 1028(line=50, offs=8) -- 1036(line=50, offs=16)
*/
ATSINSmove(tmpret41, PMVtmpltcst(head<S2Evar(a(3863))>)(arg0)) ;

} ATSelse() {
/*
emit_instr: loc0 = /vagrant/stream.dats: 1051(line=51, offs=13) -- 1059(line=51, offs=21)
*/
ATSINSmove(tmp44, PMVtmpltcst(tail<S2Evar(a(3863))>)(arg0)) ;

/*
emit_instr: loc0 = /vagrant/stream.dats: 1062(line=51, offs=24) -- 1065(line=51, offs=27)
*/
ATSINSmove(tmp45, PMVtmpltcst(g0int_sub<S2Eextkind(atstype_int)>)(arg1, ATSPMVi0nt(1))) ;

/*
emit_instr: loc0 = /vagrant/stream.dats: 1046(line=51, offs=8) -- 1066(line=51, offs=28)
*/
ATStailcalbeg()
ATSINSmove_tlcal(argx0, tmp44) ;
ATSINSmove_tlcal(argx1, tmp45) ;
ATSINSargmove_tlcal(arg0, argx0) ;
ATSINSargmove_tlcal(arg1, argx1) ;
ATSgoto(__patsflab_get) ;
ATStailcalend()

} /* ATSendif */
ATSbranchend() ;

/*
** ibranchlst-end
*/
ATScaseofend()

/* funbodyinstrlst(end) */
ATSreturn(tmpret41) ;
} /* end of [_057_vagrant_057_stream_056_sats__get__12] */
#endif // end of [TEMPLATE]

#if(0)
/*
/vagrant/stream.dats: 1095(line=53, offs=25) -- 1303(line=59, offs=67)
*/
/*
local: 
global: zip$13$0(level=0)
local: 
global: 
*/
ATSglobaldec()
/*
imparg = a(3866), b(3867), r(3868)
tmparg = S2Evar(a(3866)), S2Evar(b(3867)); S2Evar(r(3868))
tmpsub = None()
*/
atstkind_type(atstype_ptrk)
_057_vagrant_057_stream_056_sats__zip__13(atstkind_type(atstype_ptrk) arg0, atstkind_type(atstype_ptrk) arg1, atstype_cloptr arg2)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret46, atstkind_type(atstype_ptrk)) ;
ATStmpdec(tmp47, atstype_boxed) ;
ATStmpdec(tmp48, atstyvar_type(a)) ;
ATStmpdec(tmp50, atstype_boxed) ;
ATStmpdec(tmp51, atstyvar_type(b)) ;
/* tmpvardeclst(end) */
/* funbodyinstrlst(beg) */
/*
emit_instr: loc0 = /vagrant/stream.dats: 1091(line=53, offs=21) -- 1303(line=59, offs=67)
*/
ATSINSlab(__patsflab_zip):
/*
emit_instr: loc0 = /vagrant/stream.dats: 1118(line=54, offs=8) -- 1126(line=54, offs=16)
*/
ATSINSmove(tmp47, PMVtmpltcst(head<S2Evar(a(3866))>)(arg0)) ;

/*
emit_instr: loc0 = /vagrant/stream.dats: 1112(line=54, offs=2) -- 1303(line=59, offs=67)
*/
ATScaseofbeg()
/*
** ibranchlst-beg
*/
ATSbranchbeg() ;
/*
emit_instr: loc0 = /vagrant/stream.dats: 1136(line=55, offs=4) -- 1146(line=55, offs=14)
*/
__atstmplab20:
/*
emit_instr: loc0 = /vagrant/stream.dats: 1118(line=54, offs=8) -- 1126(line=54, offs=16)
*/
if (ATSCKptriscons(tmp47)) { ATSgoto(__atstmplab23) ; }
/*
emit_instr: loc0 = /vagrant/stream.dats: 1146(line=55, offs=14) -- 1146(line=55, offs=14)
*/
__atstmplab21:
/*
emit_instr: loc0 = : 0(line=0, offs=0) -- 0(line=0, offs=0)
*/
/*
ibranch-mbody:
*/
/*
emit_instr: loc0 = /vagrant/stream.dats: 1150(line=55, offs=18) -- 1163(line=55, offs=31)
*/
ATSINSmove_delay(tmpret46, atstype_boxed, ATSPMVcfunlab(-1, __patsfun_14__14, ())) ;
ATSbranchend() ;

ATSbranchbeg() ;
/*
emit_instr: loc0 = /vagrant/stream.dats: 1168(line=56, offs=4) -- 1175(line=56, offs=11)
*/
__atstmplab22:
/*
emit_instr: loc0 = /vagrant/stream.dats: 1118(line=54, offs=8) -- 1126(line=54, offs=16)
*/
#if(0)
if (ATSCKptrisnull(tmp47)) { ATSINSdeadcode_fail() ; }
#endif
/*
emit_instr: loc0 = /vagrant/stream.dats: 1175(line=56, offs=11) -- 1175(line=56, offs=11)
*/
__atstmplab23:
/*
emit_instr: loc0 = /vagrant/stream.dats: 1174(line=56, offs=10) -- 1175(line=56, offs=11)
*/
ATSINSmove(tmp48, ATSSELcon(tmp47, postiats_tysum_7, atslab__0)) ;
/*
emit_instr: loc0 = : 0(line=0, offs=0) -- 0(line=0, offs=0)
*/
/*
ibranch-mbody:
*/
/*
emit_instr: loc0 = /vagrant/stream.dats: 1189(line=57, offs=9) -- 1197(line=57, offs=17)
*/
ATSINSmove(tmp50, PMVtmpltcst(head<S2Evar(b(3867))>)(arg1)) ;

/*
emit_instr: loc0 = /vagrant/stream.dats: 1183(line=57, offs=3) -- 1303(line=59, offs=67)
*/
ATScaseofbeg()
/*
** ibranchlst-beg
*/
ATSbranchbeg() ;
/*
emit_instr: loc0 = /vagrant/stream.dats: 1208(line=58, offs=5) -- 1218(line=58, offs=15)
*/
__atstmplab24:
/*
emit_instr: loc0 = /vagrant/stream.dats: 1189(line=57, offs=9) -- 1197(line=57, offs=17)
*/
if (ATSCKptriscons(tmp50)) { ATSgoto(__atstmplab27) ; }
/*
emit_instr: loc0 = /vagrant/stream.dats: 1218(line=58, offs=15) -- 1218(line=58, offs=15)
*/
__atstmplab25:
/*
emit_instr: loc0 = : 0(line=0, offs=0) -- 0(line=0, offs=0)
*/
/*
ibranch-mbody:
*/
/*
emit_instr: loc0 = /vagrant/stream.dats: 1222(line=58, offs=19) -- 1235(line=58, offs=32)
*/
ATSINSmove_delay(tmpret46, atstype_boxed, ATSPMVcfunlab(-1, __patsfun_15__15, ())) ;
ATSbranchend() ;

ATSbranchbeg() ;
/*
emit_instr: loc0 = /vagrant/stream.dats: 1241(line=59, offs=5) -- 1248(line=59, offs=12)
*/
__atstmplab26:
/*
emit_instr: loc0 = /vagrant/stream.dats: 1189(line=57, offs=9) -- 1197(line=57, offs=17)
*/
#if(0)
if (ATSCKptrisnull(tmp50)) { ATSINSdeadcode_fail() ; }
#endif
/*
emit_instr: loc0 = /vagrant/stream.dats: 1248(line=59, offs=12) -- 1248(line=59, offs=12)
*/
__atstmplab27:
/*
emit_instr: loc0 = /vagrant/stream.dats: 1247(line=59, offs=11) -- 1248(line=59, offs=12)
*/
ATSINSmove(tmp51, ATSSELcon(tmp50, postiats_tysum_8, atslab__0)) ;
/*
emit_instr: loc0 = : 0(line=0, offs=0) -- 0(line=0, offs=0)
*/
/*
ibranch-mbody:
*/
/*
emit_instr: loc0 = /vagrant/stream.dats: 1253(line=59, offs=17) -- 1303(line=59, offs=67)
*/
ATSINSmove_delay(tmpret46, atstype_boxed, ATSPMVcfunlab(-1, __patsfun_16__16, (arg0, arg1, arg2, tmp48, tmp51))) ;
ATSbranchend() ;

/*
** ibranchlst-end
*/
ATScaseofend()

ATSbranchend() ;

/*
** ibranchlst-end
*/
ATScaseofend()

/* funbodyinstrlst(end) */
ATSreturn(tmpret46) ;
} /* end of [_057_vagrant_057_stream_056_sats__zip__13] */
#endif // end of [TEMPLATE]

#if(0)
/*
/vagrant/stream.dats: 1150(line=55, offs=18) -- 1163(line=55, offs=31)
*/
/*
local: 
global: __patsfun_14$0(level=1)
local: 
global: 
*/
ATSstaticdec()
atstype_boxed
__patsfun_14__14()
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret49, atstype_boxed) ;
/* tmpvardeclst(end) */
/* funbodyinstrlst(beg) */
/*
emit_instr: loc0 = /vagrant/stream.dats: 1150(line=55, offs=18) -- 1163(line=55, offs=31)
*/
ATSINSlab(__patsflab___patsfun_14):
/*
emit_instr: loc0 = /vagrant/stream.dats: 1157(line=55, offs=25) -- 1163(line=55, offs=31)
*/

ATSINSmove_con0(tmpret49, 0) ;

/* funbodyinstrlst(end) */
ATSreturn(tmpret49) ;
} /* end of [__patsfun_14__14] */
#endif // end of [TEMPLATE]

#if(0)
/*
/vagrant/stream.dats: 1222(line=58, offs=19) -- 1235(line=58, offs=32)
*/
/*
local: 
global: __patsfun_15$0(level=1)
local: 
global: 
*/
ATSstaticdec()
atstype_boxed
__patsfun_15__15()
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret52, atstype_boxed) ;
/* tmpvardeclst(end) */
/* funbodyinstrlst(beg) */
/*
emit_instr: loc0 = /vagrant/stream.dats: 1222(line=58, offs=19) -- 1235(line=58, offs=32)
*/
ATSINSlab(__patsflab___patsfun_15):
/*
emit_instr: loc0 = /vagrant/stream.dats: 1229(line=58, offs=26) -- 1235(line=58, offs=32)
*/

ATSINSmove_con0(tmpret52, 0) ;

/* funbodyinstrlst(end) */
ATSreturn(tmpret52) ;
} /* end of [__patsfun_15__15] */
#endif // end of [TEMPLATE]

#if(0)
/*
/vagrant/stream.dats: 1253(line=59, offs=17) -- 1303(line=59, offs=67)
*/
/*
local: 
global: __patsfun_16$0(level=1)
local: xs$85(1)(HSEapp(HSEcst(atstkind_type); HSEs2exp(S2Eextkind(atstype_ptrk)))), ys$86(1)(HSEapp(HSEcst(atstkind_type); HSEs2exp(S2Eextkind(atstype_ptrk)))), f$87(1)(HSEfun(HSEtyvar(a(3866)), HSEtyvar(b(3867)); HSEtyvar(r(3868)))), x$88(1)(HSEtyvar(a(3866))), y$89(1)(HSEtyvar(b(3867)))
global: xs$85(1)(HSEapp(HSEcst(atstkind_type); HSEs2exp(S2Eextkind(atstype_ptrk)))), ys$86(1)(HSEapp(HSEcst(atstkind_type); HSEs2exp(S2Eextkind(atstype_ptrk)))), f$87(1)(HSEfun(HSEtyvar(a(3866)), HSEtyvar(b(3867)); HSEtyvar(r(3868)))), x$88(1)(HSEtyvar(a(3866))), y$89(1)(HSEtyvar(b(3867)))
*/
ATSstaticdec()
atstype_boxed
__patsfun_16__16(atstkind_type(atstype_ptrk) env0, atstkind_type(atstype_ptrk) env1, atstype_funptr env2, atstyvar_type(a) env3, atstyvar_type(b) env4)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret53, atstype_boxed) ;
ATStmpdec(tmp54, atstyvar_type(r)) ;
ATStmpdec(tmp55, atstkind_type(atstype_ptrk)) ;
ATStmpdec(tmp56, atstkind_type(atstype_ptrk)) ;
ATStmpdec(tmp57, atstkind_type(atstype_ptrk)) ;
/* tmpvardeclst(end) */
/* funbodyinstrlst(beg) */
/*
emit_instr: loc0 = /vagrant/stream.dats: 1253(line=59, offs=17) -- 1303(line=59, offs=67)
*/
ATSINSlab(__patsflab___patsfun_16):
/*
emit_instr: loc0 = /vagrant/stream.dats: 1261(line=59, offs=25) -- 1269(line=59, offs=33)
*/
ATSINSmove(tmp54, ATSfunclo_clo(env2, (atstype_cloptr, atstyvar_type(a), atstyvar_type(b)), atstyvar_type(r))(env2, env3, env4)) ;

/*
emit_instr: loc0 = /vagrant/stream.dats: 1278(line=59, offs=42) -- 1286(line=59, offs=50)
*/
ATSINSmove(tmp56, PMVtmpltcst(tail<S2Evar(a(3866))>)(env0)) ;

/*
emit_instr: loc0 = /vagrant/stream.dats: 1289(line=59, offs=53) -- 1297(line=59, offs=61)
*/
ATSINSmove(tmp57, PMVtmpltcst(tail<S2Evar(b(3867))>)(env1)) ;

/*
emit_instr: loc0 = /vagrant/stream.dats: 1273(line=59, offs=37) -- 1302(line=59, offs=66)
*/
ATSINSmove(tmp55, PMVtmpltcst(zip<S2Evar(a(3866)), S2Evar(b(3867))><S2Evar(r(3868))>)(tmp56, tmp57, env2)) ;

/*
emit_instr: loc0 = /vagrant/stream.dats: 1261(line=59, offs=25) -- 1302(line=59, offs=66)
*/

ATSINSmove_con1(tmpret53, postiats_tysum_9) ;
#if(0)
ATSINSstore_con_tag(tmpret53, 0) ;
#endif
ATSINSstore_con_ofs(tmpret53, postiats_tysum_9, atslab__0, tmp54) ;
ATSINSstore_con_ofs(tmpret53, postiats_tysum_9, atslab__1, tmp55) ;

/* funbodyinstrlst(end) */
ATSreturn(tmpret53) ;
} /* end of [__patsfun_16__16] */
#endif // end of [TEMPLATE]

#if(0)
/*
/vagrant/stream.dats: 1329(line=61, offs=22) -- 1494(line=67, offs=29)
*/
/*
local: 
global: filter$17$0(level=0)
local: 
global: 
*/
ATSglobaldec()
/*
imparg = a(3873)
tmparg = S2Evar(a(3873))
tmpsub = None()
*/
atstkind_type(atstype_ptrk)
_057_vagrant_057_stream_056_sats__filter__17(atstkind_type(atstype_ptrk) arg0, atstype_cloptr arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec(argx0, atstkind_type(atstype_ptrk)) ;
ATStmpdec(argx1, atstype_cloptr) ;
ATStmpdec(tmpret58, atstkind_type(atstype_ptrk)) ;
ATStmpdec(tmp59, atstype_boxed) ;
ATStmpdec(tmp60, atstyvar_type(a)) ;
ATStmpdec(tmp62, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp66, atstkind_type(atstype_ptrk)) ;
/* tmpvardeclst(end) */
/* funbodyinstrlst(beg) */
/*
emit_instr: loc0 = /vagrant/stream.dats: 1322(line=61, offs=15) -- 1494(line=67, offs=29)
*/
ATSINSlab(__patsflab_filter):
/*
emit_instr: loc0 = /vagrant/stream.dats: 1348(line=62, offs=8) -- 1355(line=62, offs=15)
*/
ATSINSmove(tmp59, PMVtmpltcst(head<S2Evar(a(3873))>)(arg0)) ;

/*
emit_instr: loc0 = /vagrant/stream.dats: 1342(line=62, offs=2) -- 1494(line=67, offs=29)
*/
ATScaseofbeg()
/*
** ibranchlst-beg
*/
ATSbranchbeg() ;
/*
emit_instr: loc0 = /vagrant/stream.dats: 1364(line=63, offs=4) -- 1374(line=63, offs=14)
*/
__atstmplab28:
/*
emit_instr: loc0 = /vagrant/stream.dats: 1348(line=62, offs=8) -- 1355(line=62, offs=15)
*/
if (ATSCKptriscons(tmp59)) { ATSgoto(__atstmplab31) ; }
/*
emit_instr: loc0 = /vagrant/stream.dats: 1374(line=63, offs=14) -- 1374(line=63, offs=14)
*/
__atstmplab29:
/*
emit_instr: loc0 = : 0(line=0, offs=0) -- 0(line=0, offs=0)
*/
/*
ibranch-mbody:
*/
/*
emit_instr: loc0 = /vagrant/stream.dats: 1378(line=63, offs=18) -- 1391(line=63, offs=31)
*/
ATSINSmove_delay(tmpret58, atstype_boxed, ATSPMVcfunlab(-1, __patsfun_18__18, ())) ;
ATSbranchend() ;

ATSbranchbeg() ;
/*
emit_instr: loc0 = /vagrant/stream.dats: 1396(line=64, offs=4) -- 1403(line=64, offs=11)
*/
__atstmplab30:
/*
emit_instr: loc0 = /vagrant/stream.dats: 1348(line=62, offs=8) -- 1355(line=62, offs=15)
*/
#if(0)
if (ATSCKptrisnull(tmp59)) { ATSINSdeadcode_fail() ; }
#endif
/*
emit_instr: loc0 = /vagrant/stream.dats: 1403(line=64, offs=11) -- 1403(line=64, offs=11)
*/
__atstmplab31:
/*
emit_instr: loc0 = /vagrant/stream.dats: 1402(line=64, offs=10) -- 1403(line=64, offs=11)
*/
ATSINSmove(tmp60, ATSSELcon(tmp59, postiats_tysum_10, atslab__0)) ;
/*
emit_instr: loc0 = : 0(line=0, offs=0) -- 0(line=0, offs=0)
*/
/*
ibranch-mbody:
*/
/*
emit_instr: loc0 = /vagrant/stream.dats: 1414(line=65, offs=6) -- 1418(line=65, offs=10)
*/
ATSINSmove(tmp62, ATSfunclo_clo(arg1, (atstype_cloptr, atstyvar_type(a)), atstkind_t0ype(atstype_bool))(arg1, tmp60)) ;

/*
emit_instr: loc0 = /vagrant/stream.dats: 1411(line=65, offs=3) -- 1494(line=67, offs=29)
*/
ATSif(
tmp62
) ATSthen() {
/*
emit_instr: loc0 = /vagrant/stream.dats: 1429(line=66, offs=8) -- 1464(line=66, offs=43)
*/
ATSINSmove_delay(tmpret58, atstype_boxed, ATSPMVcfunlab(-1, __patsfun_19__19, (arg0, arg1, tmp60))) ;
} ATSelse() {
/*
emit_instr: loc0 = /vagrant/stream.dats: 1481(line=67, offs=16) -- 1489(line=67, offs=24)
*/
ATSINSmove(tmp66, PMVtmpltcst(tail<S2Evar(a(3873))>)(arg0)) ;

/*
emit_instr: loc0 = /vagrant/stream.dats: 1473(line=67, offs=8) -- 1494(line=67, offs=29)
*/
ATStailcalbeg()
ATSINSmove_tlcal(argx0, tmp66) ;
ATSINSmove_tlcal(argx1, arg1) ;
ATSINSargmove_tlcal(arg0, argx0) ;
ATSINSargmove_tlcal(arg1, argx1) ;
ATSgoto(__patsflab_filter) ;
ATStailcalend()

} /* ATSendif */
ATSbranchend() ;

/*
** ibranchlst-end
*/
ATScaseofend()

/* funbodyinstrlst(end) */
ATSreturn(tmpret58) ;
} /* end of [_057_vagrant_057_stream_056_sats__filter__17] */
#endif // end of [TEMPLATE]

#if(0)
/*
/vagrant/stream.dats: 1378(line=63, offs=18) -- 1391(line=63, offs=31)
*/
/*
local: 
global: __patsfun_18$0(level=1)
local: 
global: 
*/
ATSstaticdec()
atstype_boxed
__patsfun_18__18()
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret61, atstype_boxed) ;
/* tmpvardeclst(end) */
/* funbodyinstrlst(beg) */
/*
emit_instr: loc0 = /vagrant/stream.dats: 1378(line=63, offs=18) -- 1391(line=63, offs=31)
*/
ATSINSlab(__patsflab___patsfun_18):
/*
emit_instr: loc0 = /vagrant/stream.dats: 1385(line=63, offs=25) -- 1391(line=63, offs=31)
*/

ATSINSmove_con0(tmpret61, 0) ;

/* funbodyinstrlst(end) */
ATSreturn(tmpret61) ;
} /* end of [__patsfun_18__18] */
#endif // end of [TEMPLATE]

#if(0)
/*
/vagrant/stream.dats: 1429(line=66, offs=8) -- 1464(line=66, offs=43)
*/
/*
local: 
global: __patsfun_19$0(level=1)
local: xs$90(1)(HSEapp(HSEcst(atstkind_type); HSEs2exp(S2Eextkind(atstype_ptrk)))), f$91(1)(HSEfun(HSEtyvar(a(3873)); HSEapp(HSEcst(atstkind_t0ype); HSEs2exp(S2Eextkind(atstype_bool))))), x$92(1)(HSEtyvar(a(3873)))
global: xs$90(1)(HSEapp(HSEcst(atstkind_type); HSEs2exp(S2Eextkind(atstype_ptrk)))), f$91(1)(HSEfun(HSEtyvar(a(3873)); HSEapp(HSEcst(atstkind_t0ype); HSEs2exp(S2Eextkind(atstype_bool))))), x$92(1)(HSEtyvar(a(3873)))
*/
ATSstaticdec()
atstype_boxed
__patsfun_19__19(atstkind_type(atstype_ptrk) env0, atstype_funptr env1, atstyvar_type(a) env2)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret63, atstype_boxed) ;
ATStmpdec(tmp64, atstkind_type(atstype_ptrk)) ;
ATStmpdec(tmp65, atstkind_type(atstype_ptrk)) ;
/* tmpvardeclst(end) */
/* funbodyinstrlst(beg) */
/*
emit_instr: loc0 = /vagrant/stream.dats: 1429(line=66, offs=8) -- 1464(line=66, offs=43)
*/
ATSINSlab(__patsflab___patsfun_19):
/*
emit_instr: loc0 = /vagrant/stream.dats: 1450(line=66, offs=29) -- 1458(line=66, offs=37)
*/
ATSINSmove(tmp65, PMVtmpltcst(tail<S2Evar(a(3873))>)(env0)) ;

/*
emit_instr: loc0 = /vagrant/stream.dats: 1442(line=66, offs=21) -- 1463(line=66, offs=42)
*/
ATSINSmove(tmp64, PMVtmpltcst(filter<S2Evar(a(3873))>)(tmp65, env1)) ;

/*
emit_instr: loc0 = /vagrant/stream.dats: 1437(line=66, offs=16) -- 1463(line=66, offs=42)
*/

ATSINSmove_con1(tmpret63, postiats_tysum_11) ;
#if(0)
ATSINSstore_con_tag(tmpret63, 0) ;
#endif
ATSINSstore_con_ofs(tmpret63, postiats_tysum_11, atslab__0, env2) ;
ATSINSstore_con_ofs(tmpret63, postiats_tysum_11, atslab__1, tmp64) ;

/* funbodyinstrlst(end) */
ATSreturn(tmpret63) ;
} /* end of [__patsfun_19__19] */
#endif // end of [TEMPLATE]

#if(0)
/*
/vagrant/stream.dats: 1527(line=69, offs=29) -- 1746(line=77, offs=4)
*/
/*
local: 
global: fprint_stream$20$0(level=0)
local: 
global: 
*/
ATSglobaldec()
/*
imparg = a(3876)
tmparg = S2Evar(a(3876))
tmpsub = None()
*/
atsvoid_t0ype
_057_vagrant_057_stream_056_sats__fprint_stream__20(atstkind_type(atstype_ptrk) arg0, atstkind_type(atstype_ptrk) arg1, atstkind_t0ype(atstype_int) arg2, atstype_funptr arg3)
{
/* tmpvardeclst(beg) */
ATStmpdec_void(tmpret67, atsvoid_t0ype) ;
ATStmpdec(tmp68, atstype_boxed) ;
ATStmpdec(tmp69, atstyvar_type(a)) ;
ATStmpdec(tmp70, atstkind_type(atstype_ptrk)) ;
ATStmpdec(tmp71, atstkind_t0ype(atstype_bool)) ;
ATStmpdec_void(tmp72, atsvoid_t0ype) ;
ATStmpdec_void(tmp73, atsvoid_t0ype) ;
ATStmpdec_void(tmp74, atsvoid_t0ype) ;
ATStmpdec(tmp75, atstkind_t0ype(atstype_int)) ;
/* tmpvardeclst(end) */
/* funbodyinstrlst(beg) */
/*
emit_instr: loc0 = /vagrant/stream.dats: 1513(line=69, offs=15) -- 1746(line=77, offs=4)
*/
ATSINSlab(__patsflab_fprint_stream):
/*
emit_instr: loc0 = /vagrant/stream.dats: 1553(line=69, offs=55) -- 1556(line=69, offs=58)
*/
ATSINSmove_lazyeval(tmp68, atstype_boxed, arg1) ;
/*
emit_instr: loc0 = /vagrant/stream.dats: 1547(line=69, offs=49) -- 1746(line=77, offs=4)
*/
ATScaseofbeg()
/*
** ibranchlst-beg
*/
ATSbranchbeg() ;
/*
emit_instr: loc0 = /vagrant/stream.dats: 1565(line=70, offs=4) -- 1571(line=70, offs=10)
*/
__atstmplab32:
/*
emit_instr: loc0 = /vagrant/stream.dats: 1553(line=69, offs=55) -- 1556(line=69, offs=58)
*/
if (ATSCKptriscons(tmp68)) { ATSgoto(__atstmplab35) ; }
/*
emit_instr: loc0 = /vagrant/stream.dats: 1571(line=70, offs=10) -- 1571(line=70, offs=10)
*/
__atstmplab33:
/*
emit_instr: loc0 = : 0(line=0, offs=0) -- 0(line=0, offs=0)
*/
/*
ibranch-mbody:
*/
/*
emit_instr: loc0 = /vagrant/stream.dats: 1575(line=70, offs=14) -- 1594(line=70, offs=33)
*/
ATSINSmove_void(tmpret67, atspre_fprint_string(arg0, ATSPMVstring("nil"))) ;

ATSbranchend() ;

ATSbranchbeg() ;
/*
emit_instr: loc0 = /vagrant/stream.dats: 1599(line=71, offs=4) -- 1611(line=71, offs=16)
*/
__atstmplab34:
/*
emit_instr: loc0 = /vagrant/stream.dats: 1553(line=69, offs=55) -- 1556(line=69, offs=58)
*/
#if(0)
if (ATSCKptrisnull(tmp68)) { ATSINSdeadcode_fail() ; }
#endif
/*
emit_instr: loc0 = /vagrant/stream.dats: 1611(line=71, offs=16) -- 1611(line=71, offs=16)
*/
__atstmplab35:
/*
emit_instr: loc0 = /vagrant/stream.dats: 1605(line=71, offs=10) -- 1606(line=71, offs=11)
*/
ATSINSmove(tmp69, ATSSELcon(tmp68, postiats_tysum_12, atslab__0)) ;
/*
emit_instr: loc0 = /vagrant/stream.dats: 1608(line=71, offs=13) -- 1610(line=71, offs=15)
*/
ATSINSmove(tmp70, ATSSELcon(tmp68, postiats_tysum_12, atslab__1)) ;
/*
emit_instr: loc0 = : 0(line=0, offs=0) -- 0(line=0, offs=0)
*/
/*
ibranch-mbody:
*/
/*
emit_instr: loc0 = /vagrant/stream.dats: 1622(line=72, offs=6) -- 1629(line=72, offs=13)
*/
ATSINSmove(tmp71, PMVtmpltcst(gt_g0int_int<S2Eextkind(atstype_int)>)(arg2, ATSPMVi0nt(0))) ;

/*
emit_instr: loc0 = /vagrant/stream.dats: 1619(line=72, offs=3) -- 1746(line=77, offs=4)
*/
ATSif(
tmp71
) ATSthen() {
/*
emit_instr: loc0 = /vagrant/stream.dats: 1639(line=73, offs=8) -- 1746(line=77, offs=4)
*/
/*
letpush(beg)
*/
/*
emit_instr: loc0 = /vagrant/stream.dats: 1662(line=74, offs=12) -- 1672(line=74, offs=22)
*/
ATSINSmove_void(tmp72, ATSfunclo_fun(arg3, (atstkind_type(atstype_ptrk), atstyvar_type(a)), atsvoid_t0ype)(arg0, tmp69)) ;

/*
emit_instr: loc0 = /vagrant/stream.dats: 1685(line=75, offs=12) -- 1702(line=75, offs=29)
*/
ATSINSmove_void(tmp73, atspre_fprint_string(arg0, ATSPMVstring(":"))) ;

/*
emit_instr: loc0 = /vagrant/stream.dats: 1732(line=76, offs=29) -- 1737(line=76, offs=34)
*/
ATSINSmove(tmp75, PMVtmpltcst(g0int_sub<S2Eextkind(atstype_int)>)(arg2, ATSPMVi0nt(1))) ;

/*
emit_instr: loc0 = /vagrant/stream.dats: 1715(line=76, offs=12) -- 1741(line=76, offs=38)
*/
ATSINSmove_void(tmp74, PMVtmpltcst(fprint_stream<S2Evar(a(3876))>)(arg0, tmp70, tmp75, arg3)) ;

/*
letpush(end)
*/

/*
emit_instr: loc0 = /vagrant/stream.dats: 1639(line=73, offs=8) -- 1641(line=73, offs=10)
*/
ATSINSmove_void(tmpret67, ATSempty()) ;
/*
emit_instr: loc0 = /vagrant/stream.dats: 1639(line=73, offs=8) -- 1746(line=77, offs=4)
*/
/*
INSletpop()
*/
} ATSelse() {
/*
emit_instr: loc0 = /vagrant/stream.dats: 1746(line=77, offs=4) -- 1746(line=77, offs=4)
*/
ATSINSmove_void(tmpret67, ATSempty()) ;
} /* ATSendif */
ATSbranchend() ;

/*
** ibranchlst-end
*/
ATScaseofend()

/* funbodyinstrlst(end) */
ATSreturn_void(tmpret67) ;
} /* end of [_057_vagrant_057_stream_056_sats__fprint_stream__20] */
#endif // end of [TEMPLATE]

#if(0)
/*
/vagrant/stream.dats: 1772(line=79, offs=23) -- 1873(line=81, offs=48)
*/
/*
local: 
global: map$21$0(level=0)
local: 
global: 
*/
ATSglobaldec()
/*
imparg = a(3879), b(3880)
tmparg = S2Evar(a(3879)); S2Evar(b(3880))
tmpsub = None()
*/
atstkind_type(atstype_ptrk)
_057_vagrant_057_stream_056_sats__map__21(atstkind_type(atstype_ptrk) arg0, atstype_cloptr arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret76, atstkind_type(atstype_ptrk)) ;
ATStmpdec(tmp77, atstype_boxed) ;
ATStmpdec(tmp78, atstyvar_type(a)) ;
ATStmpdec(tmp79, atstkind_type(atstype_ptrk)) ;
/* tmpvardeclst(end) */
/* funbodyinstrlst(beg) */
/*
emit_instr: loc0 = /vagrant/stream.dats: 1768(line=79, offs=19) -- 1873(line=81, offs=48)
*/
ATSINSlab(__patsflab_map):
/*
emit_instr: loc0 = /vagrant/stream.dats: 1788(line=79, offs=39) -- 1791(line=79, offs=42)
*/
ATSINSmove_lazyeval(tmp77, atstype_boxed, arg0) ;
/*
emit_instr: loc0 = /vagrant/stream.dats: 1782(line=79, offs=33) -- 1873(line=81, offs=48)
*/
ATScaseofbeg()
/*
** ibranchlst-beg
*/
ATSbranchbeg() ;
/*
emit_instr: loc0 = /vagrant/stream.dats: 1800(line=80, offs=4) -- 1806(line=80, offs=10)
*/
__atstmplab36:
/*
emit_instr: loc0 = /vagrant/stream.dats: 1788(line=79, offs=39) -- 1791(line=79, offs=42)
*/
if (ATSCKptriscons(tmp77)) { ATSgoto(__atstmplab39) ; }
/*
emit_instr: loc0 = /vagrant/stream.dats: 1806(line=80, offs=10) -- 1806(line=80, offs=10)
*/
__atstmplab37:
/*
emit_instr: loc0 = : 0(line=0, offs=0) -- 0(line=0, offs=0)
*/
/*
ibranch-mbody:
*/
/*
emit_instr: loc0 = /vagrant/stream.dats: 1810(line=80, offs=14) -- 1823(line=80, offs=27)
*/
ATSINSmove_delay(tmpret76, atstype_boxed, ATSPMVcfunlab(-1, __patsfun_22__22, ())) ;
ATSbranchend() ;

ATSbranchbeg() ;
/*
emit_instr: loc0 = /vagrant/stream.dats: 1829(line=81, offs=4) -- 1841(line=81, offs=16)
*/
__atstmplab38:
/*
emit_instr: loc0 = /vagrant/stream.dats: 1788(line=79, offs=39) -- 1791(line=79, offs=42)
*/
#if(0)
if (ATSCKptrisnull(tmp77)) { ATSINSdeadcode_fail() ; }
#endif
/*
emit_instr: loc0 = /vagrant/stream.dats: 1841(line=81, offs=16) -- 1841(line=81, offs=16)
*/
__atstmplab39:
/*
emit_instr: loc0 = /vagrant/stream.dats: 1835(line=81, offs=10) -- 1836(line=81, offs=11)
*/
ATSINSmove(tmp78, ATSSELcon(tmp77, postiats_tysum_13, atslab__0)) ;
/*
emit_instr: loc0 = /vagrant/stream.dats: 1838(line=81, offs=13) -- 1840(line=81, offs=15)
*/
ATSINSmove(tmp79, ATSSELcon(tmp77, postiats_tysum_13, atslab__1)) ;
/*
emit_instr: loc0 = : 0(line=0, offs=0) -- 0(line=0, offs=0)
*/
/*
ibranch-mbody:
*/
/*
emit_instr: loc0 = /vagrant/stream.dats: 1845(line=81, offs=20) -- 1873(line=81, offs=48)
*/
ATSINSmove_delay(tmpret76, atstype_boxed, ATSPMVcfunlab(-1, __patsfun_23__23, (arg1, tmp78, tmp79))) ;
ATSbranchend() ;

/*
** ibranchlst-end
*/
ATScaseofend()

/* funbodyinstrlst(end) */
ATSreturn(tmpret76) ;
} /* end of [_057_vagrant_057_stream_056_sats__map__21] */
#endif // end of [TEMPLATE]

#if(0)
/*
/vagrant/stream.dats: 1810(line=80, offs=14) -- 1823(line=80, offs=27)
*/
/*
local: 
global: __patsfun_22$0(level=1)
local: 
global: 
*/
ATSstaticdec()
atstype_boxed
__patsfun_22__22()
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret80, atstype_boxed) ;
/* tmpvardeclst(end) */
/* funbodyinstrlst(beg) */
/*
emit_instr: loc0 = /vagrant/stream.dats: 1810(line=80, offs=14) -- 1823(line=80, offs=27)
*/
ATSINSlab(__patsflab___patsfun_22):
/*
emit_instr: loc0 = /vagrant/stream.dats: 1817(line=80, offs=21) -- 1823(line=80, offs=27)
*/

ATSINSmove_con0(tmpret80, 0) ;

/* funbodyinstrlst(end) */
ATSreturn(tmpret80) ;
} /* end of [__patsfun_22__22] */
#endif // end of [TEMPLATE]

#if(0)
/*
/vagrant/stream.dats: 1845(line=81, offs=20) -- 1873(line=81, offs=48)
*/
/*
local: 
global: __patsfun_23$0(level=1)
local: f$100(1)(HSEfun(HSEtyvar(a(3879)); HSEtyvar(b(3880)))), x$101(1)(HSEtyvar(a(3879))), xs$102(1)(HSEapp(HSEcst(atstkind_type); HSEs2exp(S2Eextkind(atstype_ptrk))))
global: f$100(1)(HSEfun(HSEtyvar(a(3879)); HSEtyvar(b(3880)))), x$101(1)(HSEtyvar(a(3879))), xs$102(1)(HSEapp(HSEcst(atstkind_type); HSEs2exp(S2Eextkind(atstype_ptrk))))
*/
ATSstaticdec()
atstype_boxed
__patsfun_23__23(atstype_funptr env0, atstyvar_type(a) env1, atstkind_type(atstype_ptrk) env2)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret81, atstype_boxed) ;
ATStmpdec(tmp82, atstyvar_type(b)) ;
ATStmpdec(tmp83, atstkind_type(atstype_ptrk)) ;
/* tmpvardeclst(end) */
/* funbodyinstrlst(beg) */
/*
emit_instr: loc0 = /vagrant/stream.dats: 1845(line=81, offs=20) -- 1873(line=81, offs=48)
*/
ATSINSlab(__patsflab___patsfun_23):
/*
emit_instr: loc0 = /vagrant/stream.dats: 1853(line=81, offs=28) -- 1856(line=81, offs=31)
*/
ATSINSmove(tmp82, ATSfunclo_clo(env0, (atstype_cloptr, atstyvar_type(a)), atstyvar_type(b))(env0, env1)) ;

/*
emit_instr: loc0 = /vagrant/stream.dats: 1861(line=81, offs=36) -- 1872(line=81, offs=47)
*/
ATSINSmove(tmp83, PMVtmpltcst(map<S2Evar(a(3879))><S2Evar(b(3880))>)(env2, env0)) ;

/*
emit_instr: loc0 = /vagrant/stream.dats: 1853(line=81, offs=28) -- 1872(line=81, offs=47)
*/

ATSINSmove_con1(tmpret81, postiats_tysum_14) ;
#if(0)
ATSINSstore_con_tag(tmpret81, 0) ;
#endif
ATSINSstore_con_ofs(tmpret81, postiats_tysum_14, atslab__0, tmp82) ;
ATSINSstore_con_ofs(tmpret81, postiats_tysum_14, atslab__1, tmp83) ;

/* funbodyinstrlst(end) */
ATSreturn(tmpret81) ;
} /* end of [__patsfun_23__23] */
#endif // end of [TEMPLATE]

#if(0)
/*
** for initialization(dynloading)
*/
atsvoid_t0ype
_057_vagrant_057_stream_056_dats__dynload()
{
ATSdynload0(
_057_vagrant_057_stream_056_dats__dynloadflag
) ;
ATSif(
ATSCKiseqz(
_057_vagrant_057_stream_056_dats__dynloadflag
)
) ATSthen() {
ATSdynloadset(_057_vagrant_057_stream_056_dats__dynloadflag) ;
/*
dynexnlst-initize(beg)
*/
/*
dynexnlst-initize(end)
*/
} /* ATSendif */
ATSreturn_void() ;
} /* end of [*_dynload] */
#endif // end of [#if(0)]
