/*
**
** The C code is generated by ATS/Postiats
** The compilation time is: 2014-8-6: 19h: 5m
**
*/

/*
** include runtime header files
*/
#ifndef _ATS_CCOMP_HEADER_NONE
#include "pats_ccomp_config.h"
#include "pats_ccomp_basics.h"
#include "pats_ccomp_typedefs.h"
#include "pats_ccomp_instrset.h"
#include "pats_ccomp_memalloc.h"
#ifndef _ATS_CCOMP_EXCEPTION_NONE
#include "pats_ccomp_memalloca.h"
#include "pats_ccomp_exception.h"
#endif // end of [_ATS_CCOMP_EXCEPTION_NONE]
#endif /* _ATS_CCOMP_HEADER_NONE */


/*
** include prelude cats files
*/
#ifndef _ATS_CCOMP_PRELUDE_NONE
//
#include "prelude/CATS/basics.cats"
#include "prelude/CATS/integer.cats"
#include "prelude/CATS/pointer.cats"
#include "prelude/CATS/bool.cats"
#include "prelude/CATS/char.cats"
#include "prelude/CATS/integer_ptr.cats"
#include "prelude/CATS/integer_fixed.cats"
#include "prelude/CATS/float.cats"
#include "prelude/CATS/memory.cats"
#include "prelude/CATS/string.cats"
#include "prelude/CATS/strptr.cats"
//
#include "prelude/CATS/filebas.cats"
//
#include "prelude/CATS/list.cats"
#include "prelude/CATS/option.cats"
#include "prelude/CATS/array.cats"
#include "prelude/CATS/arrayptr.cats"
#include "prelude/CATS/arrayref.cats"
#include "prelude/CATS/matrix.cats"
#include "prelude/CATS/matrixptr.cats"
//
#endif /* _ATS_CCOMP_PRELUDE_NONE */
/*
** for user-supplied prelude
*/
#ifdef _ATS_CCOMP_PRELUDE_USER
//
#include _ATS_CCOMP_PRELUDE_USER
//
#endif /* _ATS_CCOMP_PRELUDE_USER */

/*
staload-prologues(beg)
*/
/*
/ats2/libc/SATS/stdio.sats: 1380(line=35, offs=1) -- 1418(line=37, offs=3)
*/

#include "libc/CATS/stdio.cats"
/*
/ats2/libc/SATS/stdio.sats: 1791(line=56, offs=1) -- 1833(line=58, offs=27)
*/
/*
/ats2/libc/sys/SATS/types.sats: 1390(line=36, offs=1) -- 1432(line=38, offs=3)
*/

#include "libc/sys/CATS/types.cats"
/*
/vagrant/token.sats: 1(line=1, offs=1) -- 20(line=1, offs=20)
*/
/*
/vagrant/token.sats: 22(line=2, offs=1) -- 45(line=2, offs=24)
*/
/*
staload-prologues(end)
*/
/*
typedefs-for-tyrecs-and-tysums(beg)
*/
typedef
struct {
#if(1)
int contag ;
#endif
atstkind_type(atstype_ptrk) atslab__0; 
atstype_boxed atslab__1; 
} postiats_tysum_0 ;
typedef
struct {
#if(1)
int contag ;
#endif
atstype_boxed atslab__0; 
} postiats_tysum_1 ;
typedef
struct {
#if(1)
int contag ;
#endif
atstkind_t0ype(atstype_char) atslab__0; 
atstype_boxed atslab__1; 
} postiats_tysum_2 ;
typedef
struct {
#if(1)
int contag ;
#endif
atstkind_t0ype(atstype_int) atslab__0; 
atstype_boxed atslab__1; 
} postiats_tysum_3 ;
/*
typedefs-for-tyrecs-and-tysums(end)
*/
/*
dynconlst-declaration(beg)
*/
/*
dynconlst-declaration(end)
*/
/*
dyncstlst-declaration(beg)
*/
ATSdyncst_mac(atspre_fprint_string)
ATSdyncst_extfun(_057_vagrant_057_location_056_sats__fprint_location, (atstkind_type(atstype_ptrk), atstype_boxed), atsvoid_t0ype) ;
/*
dyncstlst-declaration(end)
*/
/*
dynvalist-implementation(beg)
*/
/*
dynvalist-implementation(end)
*/
/*
exnconlst-declaration(beg)
*/
#ifndef _ATS_CCOMP_EXCEPTION_NONE
extern void the_atsexncon_initize (atstype_exncon *d2c, char *exnmsg) ;
#endif // end of [_ATS_CCOMP_EXCEPTION_NONE]
/*
exnconlst-declaration(end)
*/
/*
assumelst-declaration(beg)
*/
/*
assumelst-declaration(end)
*/
/*
extypelst-declaration(beg)
*/
/*
extypelst-declaration(end)
*/
#if(0)
ATSglobaldec()
atsvoid_t0ype
_057_vagrant_057_token_056_sats__fprint_token(atstkind_type(atstype_ptrk), atstype_boxed) ;
#endif // end of [QUALIFIED]

/*
/vagrant/token.dats: 132(line=6, offs=24) -- 970(line=33, offs=3)
*/
/*
local: 
global: fprint_token$0$0(level=0)
local: 
global: 
*/
ATSglobaldec()
atsvoid_t0ype
_057_vagrant_057_token_056_sats__fprint_token(atstkind_type(atstype_ptrk) arg0, atstype_boxed arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec_void(tmpret0, atsvoid_t0ype) ;
ATStmpdec(tmp1, atstkind_type(atstype_ptrk)) ;
ATStmpdec(tmp2, atstype_boxed) ;
ATStmpdec(tmp3, atstype_boxed) ;
ATStmpdec(tmp4, atstkind_t0ype(atstype_char)) ;
ATStmpdec(tmp5, atstype_boxed) ;
ATStmpdec(tmp6, atstkind_type(atstype_ptrk)) ;
ATStmpdec(tmp7, atstype_boxed) ;
ATStmpdec(tmp8, atstkind_type(atstype_ptrk)) ;
ATStmpdec(tmp9, atstype_boxed) ;
ATStmpdec(tmp10, atstkind_t0ype(atstype_int)) ;
ATStmpdec(tmp11, atstype_boxed) ;
ATStmpdec_void(tmp12, atsvoid_t0ype) ;
ATStmpdec_void(tmp13, atsvoid_t0ype) ;
ATStmpdec_void(tmp14, atsvoid_t0ype) ;
ATStmpdec_void(tmp15, atsvoid_t0ype) ;
ATStmpdec_void(tmp16, atsvoid_t0ype) ;
ATStmpdec_void(tmp17, atsvoid_t0ype) ;
ATStmpdec_void(tmp18, atsvoid_t0ype) ;
ATStmpdec_void(tmp19, atsvoid_t0ype) ;
ATStmpdec_void(tmp20, atsvoid_t0ype) ;
ATStmpdec_void(tmp21, atsvoid_t0ype) ;
ATStmpdec_void(tmp22, atsvoid_t0ype) ;
ATStmpdec_void(tmp23, atsvoid_t0ype) ;
/* tmpvardeclst(end) */
/* funbodyinstrlst(beg) */
/*
emit_instr: loc0 = /vagrant/token.dats: 119(line=6, offs=11) -- 970(line=33, offs=3)
*/
ATSINSlab(__patsflab_fprint_token):
/*
emit_instr: loc0 = /vagrant/token.dats: 146(line=7, offs=2) -- 970(line=33, offs=3)
*/
ATScaseofbeg()
/*
** ibranchlst-beg
*/
ATSbranchbeg() ;
/*
emit_instr: loc0 = /vagrant/token.dats: 162(line=8, offs=4) -- 170(line=8, offs=12)
*/
__atstmplab0:
/*
emit_instr: loc0 = /vagrant/token.dats: 138(line=6, offs=30) -- 139(line=6, offs=31)
*/
ATSifnot(ATSPATCKcon0(arg1, 0)) { ATSgoto(__atstmplab2) ; }
/*
emit_instr: loc0 = /vagrant/token.dats: 170(line=8, offs=12) -- 170(line=8, offs=12)
*/
__atstmplab1:
/*
emit_instr: loc0 = : 0(line=0, offs=0) -- 0(line=0, offs=0)
*/
/*
ibranch-mbody:
*/
/*
emit_instr: loc0 = /vagrant/token.dats: 174(line=8, offs=16) -- 195(line=8, offs=37)
*/
ATSINSmove_void(tmpret0, atspre_fprint_string(arg0, ATSPMVstring("TNone"))) ;

ATSbranchend() ;

ATSbranchbeg() ;
/*
emit_instr: loc0 = /vagrant/token.dats: 200(line=9, offs=4) -- 207(line=9, offs=11)
*/
__atstmplab2:
/*
emit_instr: loc0 = /vagrant/token.dats: 138(line=6, offs=30) -- 139(line=6, offs=31)
*/
ATSifnot(ATSPATCKcon0(arg1, 1)) { ATSgoto(__atstmplab4) ; }
/*
emit_instr: loc0 = /vagrant/token.dats: 207(line=9, offs=11) -- 207(line=9, offs=11)
*/
__atstmplab3:
/*
emit_instr: loc0 = : 0(line=0, offs=0) -- 0(line=0, offs=0)
*/
/*
ibranch-mbody:
*/
/*
emit_instr: loc0 = /vagrant/token.dats: 211(line=9, offs=15) -- 231(line=9, offs=35)
*/
ATSINSmove_void(tmpret0, atspre_fprint_string(arg0, ATSPMVstring("TEof"))) ;

ATSbranchend() ;

ATSbranchbeg() ;
/*
emit_instr: loc0 = /vagrant/token.dats: 236(line=10, offs=4) -- 251(line=10, offs=19)
*/
__atstmplab4:
/*
emit_instr: loc0 = /vagrant/token.dats: 138(line=6, offs=30) -- 139(line=6, offs=31)
*/
ATSifnot(ATSPATCKcon1(arg1, 2)) { ATSgoto(__atstmplab6) ; }
/*
emit_instr: loc0 = /vagrant/token.dats: 251(line=10, offs=19) -- 251(line=10, offs=19)
*/
__atstmplab5:
/*
emit_instr: loc0 = /vagrant/token.dats: 246(line=10, offs=14) -- 247(line=10, offs=15)
*/
ATSINSmove(tmp1, ATSSELcon(arg1, postiats_tysum_0, atslab__0)) ;
/*
emit_instr: loc0 = /vagrant/token.dats: 249(line=10, offs=17) -- 250(line=10, offs=18)
*/
ATSINSmove(tmp2, ATSSELcon(arg1, postiats_tysum_0, atslab__1)) ;
/*
emit_instr: loc0 = : 0(line=0, offs=0) -- 0(line=0, offs=0)
*/
/*
ibranch-mbody:
*/
/*
emit_instr: loc0 = /vagrant/token.dats: 255(line=10, offs=23) -- 364(line=13, offs=3)
*/
/*
letpush(beg)
*/
/*
emit_instr: loc0 = /vagrant/token.dats: 277(line=11, offs=11) -- 333(line=11, offs=67)
*/
ATSINSmove_void(tmp12, fprintf(arg0, ATSPMVstring("TComment (%s) at "), tmp1)) ;
/*
emit_instr: loc0 = /vagrant/token.dats: 345(line=12, offs=11) -- 360(line=12, offs=26)
*/
ATSINSmove_void(tmp13, _057_vagrant_057_location_056_sats__fprint_location(arg0, tmp2)) ;

/*
letpush(end)
*/

/*
emit_instr: loc0 = /vagrant/token.dats: 255(line=10, offs=23) -- 257(line=10, offs=25)
*/
ATSINSmove_void(tmpret0, ATSempty()) ;
/*
emit_instr: loc0 = /vagrant/token.dats: 255(line=10, offs=23) -- 364(line=13, offs=3)
*/
/*
INSletpop()
*/
ATSbranchend() ;

ATSbranchbeg() ;
/*
emit_instr: loc0 = /vagrant/token.dats: 369(line=14, offs=4) -- 378(line=14, offs=13)
*/
__atstmplab6:
/*
emit_instr: loc0 = /vagrant/token.dats: 138(line=6, offs=30) -- 139(line=6, offs=31)
*/
ATSifnot(ATSPATCKcon1(arg1, 3)) { ATSgoto(__atstmplab8) ; }
/*
emit_instr: loc0 = /vagrant/token.dats: 378(line=14, offs=13) -- 378(line=14, offs=13)
*/
__atstmplab7:
/*
emit_instr: loc0 = /vagrant/token.dats: 377(line=14, offs=12) -- 378(line=14, offs=13)
*/
ATSINSmove(tmp3, ATSSELcon(arg1, postiats_tysum_1, atslab__0)) ;
/*
emit_instr: loc0 = : 0(line=0, offs=0) -- 0(line=0, offs=0)
*/
/*
ibranch-mbody:
*/
/*
emit_instr: loc0 = /vagrant/token.dats: 383(line=14, offs=18) -- 462(line=17, offs=3)
*/
/*
letpush(beg)
*/
/*
emit_instr: loc0 = /vagrant/token.dats: 405(line=15, offs=11) -- 431(line=15, offs=37)
*/
ATSINSmove_void(tmp14, atspre_fprint_string(arg0, ATSPMVstring("TSpace at "))) ;

/*
emit_instr: loc0 = /vagrant/token.dats: 443(line=16, offs=11) -- 458(line=16, offs=26)
*/
ATSINSmove_void(tmp15, _057_vagrant_057_location_056_sats__fprint_location(arg0, tmp3)) ;

/*
letpush(end)
*/

/*
emit_instr: loc0 = /vagrant/token.dats: 383(line=14, offs=18) -- 385(line=14, offs=20)
*/
ATSINSmove_void(tmpret0, ATSempty()) ;
/*
emit_instr: loc0 = /vagrant/token.dats: 383(line=14, offs=18) -- 462(line=17, offs=3)
*/
/*
INSletpop()
*/
ATSbranchend() ;

ATSbranchbeg() ;
/*
emit_instr: loc0 = /vagrant/token.dats: 467(line=18, offs=4) -- 479(line=18, offs=16)
*/
__atstmplab8:
/*
emit_instr: loc0 = /vagrant/token.dats: 138(line=6, offs=30) -- 139(line=6, offs=31)
*/
ATSifnot(ATSPATCKcon1(arg1, 4)) { ATSgoto(__atstmplab10) ; }
/*
emit_instr: loc0 = /vagrant/token.dats: 479(line=18, offs=16) -- 479(line=18, offs=16)
*/
__atstmplab9:
/*
emit_instr: loc0 = /vagrant/token.dats: 474(line=18, offs=11) -- 475(line=18, offs=12)
*/
ATSINSmove(tmp4, ATSSELcon(arg1, postiats_tysum_2, atslab__0)) ;
/*
emit_instr: loc0 = /vagrant/token.dats: 477(line=18, offs=14) -- 478(line=18, offs=15)
*/
ATSINSmove(tmp5, ATSSELcon(arg1, postiats_tysum_2, atslab__1)) ;
/*
emit_instr: loc0 = : 0(line=0, offs=0) -- 0(line=0, offs=0)
*/
/*
ibranch-mbody:
*/
/*
emit_instr: loc0 = /vagrant/token.dats: 483(line=18, offs=20) -- 589(line=21, offs=3)
*/
/*
letpush(beg)
*/
/*
emit_instr: loc0 = /vagrant/token.dats: 505(line=19, offs=11) -- 558(line=19, offs=64)
*/
ATSINSmove_void(tmp16, fprintf(arg0, ATSPMVstring("TChar (%c) at "), tmp4)) ;
/*
emit_instr: loc0 = /vagrant/token.dats: 570(line=20, offs=11) -- 585(line=20, offs=26)
*/
ATSINSmove_void(tmp17, _057_vagrant_057_location_056_sats__fprint_location(arg0, tmp5)) ;

/*
letpush(end)
*/

/*
emit_instr: loc0 = /vagrant/token.dats: 483(line=18, offs=20) -- 485(line=18, offs=22)
*/
ATSINSmove_void(tmpret0, ATSempty()) ;
/*
emit_instr: loc0 = /vagrant/token.dats: 483(line=18, offs=20) -- 589(line=21, offs=3)
*/
/*
INSletpop()
*/
ATSbranchend() ;

ATSbranchbeg() ;
/*
emit_instr: loc0 = /vagrant/token.dats: 594(line=22, offs=4) -- 608(line=22, offs=18)
*/
__atstmplab10:
/*
emit_instr: loc0 = /vagrant/token.dats: 138(line=6, offs=30) -- 139(line=6, offs=31)
*/
ATSifnot(ATSPATCKcon1(arg1, 5)) { ATSgoto(__atstmplab12) ; }
/*
emit_instr: loc0 = /vagrant/token.dats: 608(line=22, offs=18) -- 608(line=22, offs=18)
*/
__atstmplab11:
/*
emit_instr: loc0 = /vagrant/token.dats: 603(line=22, offs=13) -- 604(line=22, offs=14)
*/
ATSINSmove(tmp6, ATSSELcon(arg1, postiats_tysum_0, atslab__0)) ;
/*
emit_instr: loc0 = /vagrant/token.dats: 606(line=22, offs=16) -- 607(line=22, offs=17)
*/
ATSINSmove(tmp7, ATSSELcon(arg1, postiats_tysum_0, atslab__1)) ;
/*
emit_instr: loc0 = : 0(line=0, offs=0) -- 0(line=0, offs=0)
*/
/*
ibranch-mbody:
*/
/*
emit_instr: loc0 = /vagrant/token.dats: 612(line=22, offs=22) -- 720(line=25, offs=3)
*/
/*
letpush(beg)
*/
/*
emit_instr: loc0 = /vagrant/token.dats: 634(line=23, offs=11) -- 689(line=23, offs=66)
*/
ATSINSmove_void(tmp18, fprintf(arg0, ATSPMVstring("TString (%s) at "), tmp6)) ;
/*
emit_instr: loc0 = /vagrant/token.dats: 701(line=24, offs=11) -- 716(line=24, offs=26)
*/
ATSINSmove_void(tmp19, _057_vagrant_057_location_056_sats__fprint_location(arg0, tmp7)) ;

/*
letpush(end)
*/

/*
emit_instr: loc0 = /vagrant/token.dats: 612(line=22, offs=22) -- 614(line=22, offs=24)
*/
ATSINSmove_void(tmpret0, ATSempty()) ;
/*
emit_instr: loc0 = /vagrant/token.dats: 612(line=22, offs=22) -- 720(line=25, offs=3)
*/
/*
INSletpop()
*/
ATSbranchend() ;

ATSbranchbeg() ;
/*
emit_instr: loc0 = /vagrant/token.dats: 725(line=26, offs=4) -- 736(line=26, offs=15)
*/
__atstmplab12:
/*
emit_instr: loc0 = /vagrant/token.dats: 138(line=6, offs=30) -- 139(line=6, offs=31)
*/
ATSifnot(ATSPATCKcon1(arg1, 6)) { ATSgoto(__atstmplab14) ; }
/*
emit_instr: loc0 = /vagrant/token.dats: 736(line=26, offs=15) -- 736(line=26, offs=15)
*/
__atstmplab13:
/*
emit_instr: loc0 = /vagrant/token.dats: 730(line=26, offs=9) -- 732(line=26, offs=11)
*/
ATSINSmove(tmp8, ATSSELcon(arg1, postiats_tysum_0, atslab__0)) ;
/*
emit_instr: loc0 = /vagrant/token.dats: 734(line=26, offs=13) -- 735(line=26, offs=14)
*/
ATSINSmove(tmp9, ATSSELcon(arg1, postiats_tysum_0, atslab__1)) ;
/*
emit_instr: loc0 = : 0(line=0, offs=0) -- 0(line=0, offs=0)
*/
/*
ibranch-mbody:
*/
/*
emit_instr: loc0 = /vagrant/token.dats: 740(line=26, offs=19) -- 845(line=29, offs=3)
*/
/*
letpush(beg)
*/
/*
emit_instr: loc0 = /vagrant/token.dats: 762(line=27, offs=11) -- 814(line=27, offs=63)
*/
ATSINSmove_void(tmp20, fprintf(arg0, ATSPMVstring("TId (%s) at "), tmp8)) ;
/*
emit_instr: loc0 = /vagrant/token.dats: 826(line=28, offs=11) -- 841(line=28, offs=26)
*/
ATSINSmove_void(tmp21, _057_vagrant_057_location_056_sats__fprint_location(arg0, tmp9)) ;

/*
letpush(end)
*/

/*
emit_instr: loc0 = /vagrant/token.dats: 740(line=26, offs=19) -- 742(line=26, offs=21)
*/
ATSINSmove_void(tmpret0, ATSempty()) ;
/*
emit_instr: loc0 = /vagrant/token.dats: 740(line=26, offs=19) -- 845(line=29, offs=3)
*/
/*
INSletpop()
*/
ATSbranchend() ;

ATSbranchbeg() ;
/*
emit_instr: loc0 = /vagrant/token.dats: 850(line=30, offs=4) -- 861(line=30, offs=15)
*/
__atstmplab14:
/*
emit_instr: loc0 = /vagrant/token.dats: 138(line=6, offs=30) -- 139(line=6, offs=31)
*/
#if(0)
ATSifnot(ATSPATCKcon1(arg1, 7)) { ATSINSdeadcode_fail() ; }
#endif
/*
emit_instr: loc0 = /vagrant/token.dats: 861(line=30, offs=15) -- 861(line=30, offs=15)
*/
__atstmplab15:
/*
emit_instr: loc0 = /vagrant/token.dats: 856(line=30, offs=10) -- 857(line=30, offs=11)
*/
ATSINSmove(tmp10, ATSSELcon(arg1, postiats_tysum_3, atslab__0)) ;
/*
emit_instr: loc0 = /vagrant/token.dats: 859(line=30, offs=13) -- 860(line=30, offs=14)
*/
ATSINSmove(tmp11, ATSSELcon(arg1, postiats_tysum_3, atslab__1)) ;
/*
emit_instr: loc0 = : 0(line=0, offs=0) -- 0(line=0, offs=0)
*/
/*
ibranch-mbody:
*/
/*
emit_instr: loc0 = /vagrant/token.dats: 865(line=30, offs=19) -- 970(line=33, offs=3)
*/
/*
letpush(beg)
*/
/*
emit_instr: loc0 = /vagrant/token.dats: 887(line=31, offs=11) -- 939(line=31, offs=63)
*/
ATSINSmove_void(tmp22, fprintf(arg0, ATSPMVstring("TInt (%d) at "), tmp10)) ;
/*
emit_instr: loc0 = /vagrant/token.dats: 951(line=32, offs=11) -- 966(line=32, offs=26)
*/
ATSINSmove_void(tmp23, _057_vagrant_057_location_056_sats__fprint_location(arg0, tmp11)) ;

/*
letpush(end)
*/

/*
emit_instr: loc0 = /vagrant/token.dats: 865(line=30, offs=19) -- 867(line=30, offs=21)
*/
ATSINSmove_void(tmpret0, ATSempty()) ;
/*
emit_instr: loc0 = /vagrant/token.dats: 865(line=30, offs=19) -- 970(line=33, offs=3)
*/
/*
INSletpop()
*/
ATSbranchend() ;

/*
** ibranchlst-end
*/
ATScaseofend()

/* funbodyinstrlst(end) */
ATSreturn_void(tmpret0) ;
} /* end of [_057_vagrant_057_token_056_sats__fprint_token] */

#if(0)
/*
** for initialization(dynloading)
*/
atsvoid_t0ype
_057_vagrant_057_token_056_dats__dynload()
{
ATSdynload0(
_057_vagrant_057_token_056_dats__dynloadflag
) ;
ATSif(
ATSCKiseqz(
_057_vagrant_057_token_056_dats__dynloadflag
)
) ATSthen() {
ATSdynloadset(_057_vagrant_057_token_056_dats__dynloadflag) ;
/*
dynexnlst-initize(beg)
*/
/*
dynexnlst-initize(end)
*/
} /* ATSendif */
ATSreturn_void() ;
} /* end of [*_dynload] */
#endif // end of [#if(0)]
